# Pre-processing Workflow for diat.barcode Database
diat.barcode Version: 12.4 [('2024-05-28-Diat.barcode_release-version 12.4.xlsx', v17.0)](https://entrepot.recherche.data.gouv.fr/file.xhtml?persistentId=doi:10.57745/O5BFF7&version=17.0), published on 05/06/2024.

This Jupyter Notebook contains all the pre-processing step to extract 2 separate dataset from the original diat.barcode database:
1. diat_barcode-sequence-v12.tsv: This file contains the sequence, sequence ID and the respective species nominal identification.
2. diar_barcode-taxonomy-v12.tsv: This file contains the taxonomic lineage of all the sequences and the respective sequence ID.

In [1]:
import pandas as pd
# Imports

## Read and Exploratory Analysis

In [2]:
diat = pd.read_csv('diat-barcode_v12.tsv', sep='\t')

/tmp/ipykernel_6180/588815404.py:1: DtypeWarning: Columns (1,9,28) have mixed types. Specify dtype option on import or set low_memory=False.
  diat = pd.read_csv('diat-barcode_v12.tsv', sep='\t')

In [3]:
diat.head()

,Sequence ID,GenBank Acc,Sequence,Amplified region,Primer names,Sequencing project,Strain (or sample) sampling ID,Short sequence,Code court de sequence pour fasta,Sequence aligned - rbcl only - aligned june 2021,...,Zig-zag colony,Rosette colony,Ribbon colony,Stellate colony,"arbuscular colony (0: pas observé mais possible, 1: déjà observé)",other kind of colony,High profile guild adapted from Passy (2007) v2,Low profile guild adapted from Passy (2007) v2,Motile guild adapted from Passy (2007) = Mobiles rapides jamais accrochées et biraphidées : Naviculales+Bacillariales (sauf Diadesmis et Diploneis) v2,Euplanctonic guild v2 (centrics)
0,TCC6-18S-1,NaN,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,onema,TCC6-27.10.2009,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCC7a-18S-1,NaN,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC7a-27.10.2009,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,TCC9-18S-1,NaN,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC9-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TCC26-18S-1,NaN,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,onema,TCC26-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TCC27-18S-1,NaN,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC27-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Get the dataframe shape
diat.shape

(9234, 113)

In [5]:
# Remove columns and rows with all NaN values
diat.dropna(how='all', axis=1, inplace=True)
diat.dropna(how='all', axis=0, inplace=True)

In [6]:
# No difference in shape -> No empty columns/rows were found
diat.shape

(9234, 113)

## Extract the sequence dataset

In [7]:
# Select relevant columns
diat_barcode_seq = diat[['Sequence ID', 'Sequence', 'Species']]

In [8]:
# Confirm the selection
diat_barcode_seq

,Sequence ID,Sequence,Species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,Fragilaria sp.
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,Scenedesmus quadricauda
...,...,...,...
9229,PP073739,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,Nitzschia nandorii
9230,PP073741,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,Nitzschia nandorii
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,Sellaphora pupula
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,Amphora copulata
9233,NaN,NaN,NaN

In [9]:
# Remove empty rows
diat_barcode_seq.dropna(how='all', axis=0, inplace=True)

/tmp/ipykernel_6180/3331494130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diat_barcode_seq.dropna(how='all', axis=0, inplace=True)

In [10]:
# Check shape
diat_barcode_seq.shape

(9233, 3)

In [11]:
# Rename columns for machine readability
diat_barcode_seq.columns = ['seq_ID', 'sequence', 'species']

In [26]:
# Write to file
diat_barcode_seq.to_csv('../../data/input_data/diat_barcode_sequence.csv', sep='\t', index=False)

## Extract Taxonomy Dataset

In [12]:
col_names = diat.columns.to_list()
# col_names

### Extract Tradicional Taxonomy

In [15]:
# Select columns refering to traditional taxonomy
diat_barcode_tax_1990 = diat[['Species',
                                'Genus',
                                'Family (following Round, Crawford & Mann 1990)',
                                'Order (following Round, Crawford & Mann 1990)',
                                'Class (following Round, Crawford & Mann 1990)',
                                'Phylum (following Algaebase 2018)',
                                'Subkingdom (following Algaebase 2018)',
                                'Kingdom (following Algaebase 2018)',
                                'Empire (following Algaebase 2018)']]

In [16]:
# Rename columns for machine readability
diat_barcode_tax_1990.columns = ['Species',
                                'Genus',
                                'Family',
                                'Order',
                                'Class',
                                'Phylum',
                                'Subkingdom',
                                'Kingdom',
                                'Empire']

In [17]:
diat_barcode_tax_1990.head()

,Species,Genus,Family,Order,Class,Phylum,Subkingdom,Kingdom,Empire
0,Chlorogonium elongatum,Chlorogonium,Haematococcaceae,Volvocales,Chlorophyceae,Chlorophyta,Viridiplantae,Plantae,Eukaryota
1,Fragilaria sp.,Fragilaria,Fragilariaceae,Fragilariales,Fragilariophyceae,Bacillariophyta,Chromobiota,Chromista,Eukaryota
2,Pandorina morum,Pandorina,Volvocaceae,Volvocales,Chlorophyceae,Chlorophyta,Viridiplantae,Plantae,Eukaryota
3,Scenedesmus spinosus,Scenedesmus,Scenedesmaceae,Chlorococcales,Chlorophyceae,Chlorophyta,Viridiplantae,Plantae,Eukaryota
4,Scenedesmus quadricauda,Scenedesmus,Scenedesmaceae,Chlorococcales,Chlorophyceae,Chlorophyta,Viridiplantae,Plantae,Eukaryota

In [18]:
diat_barcode_tax_1990.shape

(9234, 9)

In [21]:
diat_barcode_tax_1990.to_csv('../../data/input_data/diat_barcode_taxonomy_1990.tsv', sep='\t', index=False)

### Extract Modern Taxonomy

In [13]:
# Select columns refering to modern taxonomy
diat_barcode_tax_2019 = diat[['Species',
                                'Genus',
                                'Family (following Adl et al. 2019)',
                                'Order (following Adl et al. 2019)',
                                'Subclass (following Adl et al. 2019)',
                                'Class (following Adl et al. 2019)',
                                'Subphylum (following Adl et al. 2019)',
                                'Subkingdom (following Adl et al. 2019)',
                                'Kingdom (following Adl et al. 2019)']]

In [14]:
diat_barcode_tax_2019.columns = [['Species',
                                'Genus',
                                'Family',
                                'Order',
                                'Subclass',
                                'Class',
                                'Subphylum',
                                'Subkingdom',
                                'Kingdom']]

In [19]:
diat_barcode_tax_2019.head()

,Species,Genus,Family,Order,Subclass,Class,Subphylum,Subkingdom,Kingdom
0,Chlorogonium elongatum,Chlorogonium,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fragilaria sp.,Fragilaria,Fragilariaceae,Fragilariales,Fragilariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista
2,Pandorina morum,Pandorina,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Scenedesmus spinosus,Scenedesmus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Scenedesmus quadricauda,Scenedesmus,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
diat_barcode_tax_2019.shape

(9234, 9)

In [22]:
diat_barcode_tax_2019.to_csv('../../data/input_data/diat_barcode_taxonomy_2019.tsv', sep='\t', index=False)