In [3]:
# Files
database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-primers.tsv"
run_name = 'DAI-TEST'
otl_folder = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia'

In [4]:
# Intake data
from src.reference_database.sequence_import import *

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta(database_file, check_taxid=False)
data = custom_fasta_import.data
data.head()

,seq_id,sequence,length,taxa_info
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...

In [5]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta_database()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda

In [6]:
database_processed_path = custom_fasta_import.database_fasta_file

In [7]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification(database_processed_path, run_name=run_name)
insil.run_in_silico_analysis(primer_table)

mozaiko INFO: Checking if cutadapt is installed...
mozaiko INFO: cutadapt is installed.
mozaiko INFO: Checking if CRABS is installed...
mozaiko INFO: CRABS is installed.
mozaiko INFO: To continue the analysis, a set of primers is needed. This information should be uploaded as a TSV table and it should contain the following fields: ['target_group', 'barcode_region', 'assay_name', 'fwd_seq', 'rev_seq']
mozaiko INFO: All set. Running in-silico amplification...
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/DAI-TEST/amplicon/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/DAI-TEST/insert/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 646F_998R.
   --------   1/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-1.
   --------   2/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-2.
   --------   3/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-1.
   --------   4/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-2.
   --------   5/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-1.
   --------   6/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-2.
   --------   7/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/amplicon/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/DAI-TEST/insert/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F-DEG_R3-DEG.
   --------   8/8 processed   --------
mozaiko ERROR: Folder not found: data/output_data/DAI-TEST/all_complete_pbs/filtered
mozaiko ERROR: Folder not found: data/output_data/DAI-TEST/all_complete_pbs/filtered/filtered_intersection
mozaiko ERROR: Folder not found: data/output_data/DAI-TEST/incomplete_pbs/filtered
mozaiko ERROR: Folder not found: data/output_data/DAI-TEST/incomplete_pbs/filtered/filtered_intersection
mozaiko INFO: Number of inserts that were amplified successfully...
    For rbcL_708F1_R3-1, 4508 were retained.
    For rbcL_708F2_R3-2, 4652 were retained.
    For rbcL_708F-DEG_R3-DEG, 4774 were retained.
    For rbcL_708F1_R3-2, 4504 were retained.
    For rbcL_646F_998R, 4357 were retained.
    For rbcL_708F2_R3-1, 4656 were retained.
    For rbcL_708F3_R3-2, 4212 were retained.
    For rbcL_708F3_R3-1, 4214 were retained.
mozaiko INFO: Number of inserts with complete PBS that were not amplified...
    For rbcL_708F1_R3-1: 300 sequences were retained.
    For rbcL_708F2_R3-2: 300 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 300 sequences were retained.
    For rbcL_708F1_R3-2: 300 sequences were retained.
    For rbcL_646F_998R: 181 sequences were retained.
    For rbcL_708F2_R3-1: 300 sequences were retained.
    For rbcL_708F3_R3-2: 300 sequences were retained.
    For rbcL_708F3_R3-1: 300 sequences were retained.
    For rbcL_708F1_R3-1: 290 sequences were retained.
    For rbcL_708F2_R3-2: 146 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 24 sequences were retained.
    For rbcL_708F1_R3-2: 294 sequences were retained.
    For rbcL_646F_998R: 17 sequences were retained.
    For rbcL_708F2_R3-1: 142 sequences were retained.
    For rbcL_708F3_R3-2: 586 sequences were retained.
    For rbcL_708F3_R3-1: 584 sequences were retained.
mozaiko INFO: Number of inserts with incomplete PBS...
    For rbcL_708F1_R3-1: 590 sequences were retained.
    For rbcL_708F2_R3-2: 446 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 324 sequences were retained.
    For rbcL_708F1_R3-2: 594 sequences were retained.
    For rbcL_646F_998R: 198 sequences were retained.
    For rbcL_708F2_R3-1: 442 sequences were retained.
    For rbcL_708F3_R3-2: 886 sequences were retained.
    For rbcL_708F3_R3-1: 884 sequences were retained.
mozaiko INFO: In-silico amplification analysis completed.

In [8]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed'

for otl in os.listdir(otl_folder):
    otl_path = os.path.join(otl_folder, otl)

    country_name = otl.split('_')[0]
    output_path = os.path.join(output_folder, country_name + '_ranked_primers.tsv')
    print(" ---------------------")
    print("Processing OTL:", otl)
    mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
    ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)
    mex.sort_otl_level_results(subdirectory_name=country_name)

 ---------------------
Processing OTL: Germany_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: Retrieving primer-PBS statistics.
mozaiko INFO: Retriving information on the Reference Database Quality.
mozaiko INFO: Calculating the number of barcodes per FASTA.
mozaiko INFO: Calculating the number of barcodes per FASTA.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/incomplete_pbs/filtered/filtered_intersection.
mozaico WARNING: Incorrect header format: AM710433|Luticola goeppertiana|Luticola goeppertiana Bleisch D.G.Mann 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Diadesmidaceae|Luticola. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: KY777685|Didymosphenia geminata|Didymosphenia geminatum Lyngbye M.Schmidt 1899|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Cymbellaceae|Didymosphenia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1066|Tryblionella debilis|Tryblionella debilis Arnott ex OMeara 1873|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Tryblionella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710503|Pinnularia substreptoraphe|Pinnularia substreptoraphe K.Krammer 2000|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OL794292|Minutocellus sp.|Minutocellus G.R.Hasle H.A.von Stosch  E.E.Syvertsen 1983|genus|Chromista|Ochrophyta|Bacillariophyceae|Cymatosirales|Cymatosiraceae|Minutocellus. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710491|Pinnularia mesolepta|Pinnularia mesolepta Ehrenberg W.Smith 1853|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: MK639355|Achnanthidium straubianum|Achnanthidium straubianum Lange-Bertalot Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OP354492|Craticula importuna|Craticula importuna Hustedt K.Bruder  Hinz 2008|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337595|Sellaphora pupula|Sellaphora pupula Kutzing Mereschkovsky 1902|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337585|Pseudo-nitzschia subcurvata|Pseudo-nitzschia subcurvata G.R.Hasle G.A.Fryxell 1993|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Pseudo-nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337592|Sellaphora obesa|Sellaphora obesa D.G.Mann  M.M.Bayer 2004|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1054|Surirella lacrimula|Surirella lacrimula J.D.English 2012|species|Chromista|Ochrophyta|Bacillariophyceae|Surirellales|Surirellaceae|Surirella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710482|Navicula cryptotenella|Navicula cryptotenella Lange-Bertalot|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1070|Nitzschia amphibia|Nitzschia amphibia Grunow 1862|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OK669066|Nitzschia vermicularis|Nitzschia vermicularis Kutzing Hantzsch 1860|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Amphipleuraceae|Frustulia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710509|Gomphonema truncatum|Gomphonema truncatum Ehrenberg 1832|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Gomphonemataceae|Gomphonema. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337604|Sellaphora pupula|Sellaphora pupula Kutzing Mereschkovsky 1902|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: SGAM-ASV34|Ulnaria ulna|Ulnaria ulna Nitzsch P.Compere 2001|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Synedra. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: FR990844|Cocconeis sp.|Cocconeis C.G.Ehrenberg 1837|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Cocconeidaceae|Cocconeis. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710476|Cymbella excisa|Cymbella excisa Schmidt 1881|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Cymbellaceae|Cymbella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: MACM-ASV8|Nitzschia soratensis|Nitzschia soratensis E.A.Morales  M.L.Vis 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OK669060|Fragilaria crotonensis|Fragilaria crotonensis Kitton 1869|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Fragilaria. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OK669061|Stephanocyclus meneghinianus|Stephanocyclus meneghinianus Kutz. Skab.|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiosirales|Stephanodiscaceae|Cyclotella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337561|Nitzschia promare|Nitzschia promare Medlin 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337557|Psammodictyon constrictum|Psammodictyon constrictum Gregory D.G.Mann 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Tryblionella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OP183210|Gomphonema seminulum|Gomphonema C.G.Ehrenberg 1832|genus|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Gomphonemataceae|Gomphonema. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710450|Pinnularia microstauron|Pinnularia microstauron Mayer 1913|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710445|Pinnularia subcapitata|Pinnularia subcapitata W.Gregory 1856|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1064-2|Ulnaria ulna|Ulnaria ulna Nitzsch P.Compere 2001|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Synedra. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC954-5|Epithemia hirudiniformis|Epithemia hirudiniformis O.Muller Rimet D.G.Mann R.Trobajo J.Zimmermann  R.Jahn 2018|species|Chromista|Ochrophyta|Bacillariophyceae|Rhopalodiales|Rhopalodiaceae|Epithemia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OK669067|Fragilaria gracilis|Fragilaria gracilis strup 1910|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Fragilaria. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710489|Amphora aff. atomoides|Amphora atomoides Levkov 2009|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1058|Diatoma mesodon|Diatoma mesodon Ehrenberg Kutzing 1844|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Diatoma. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: FR990845|Cocconeis sp.|Cocconeis C.G.Ehrenberg 1837|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Cocconeidaceae|Cocconeis. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337570|Fragilariopsis cylindrus|Fragilariopsis cylindrus Grunow Krieger 1954|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Fragilariopsis. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337553|Navicula salinicola|Navicula salinicola Hustedt|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1044|Sellaphora nigri|Sellaphora nigri De Notaris C.E.Wetzel  L.Ector 2015|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1059|Diatoma mesodon|Diatoma mesodon Ehrenberg Kutzing 1844|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Diatoma. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1069|Nitzschia inconspicua|Nitzschia inconspicua Grunow 1862|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710446|Pinnularia anglica|Pinnularia anglica K.Krammer 1992|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: KY777686|Didymosphenia geminata|Didymosphenia geminatum Lyngbye M.Schmidt 1899|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Cymbellaceae|Didymosphenia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1038|Gomphonema minutum|Gomphonema minutum C.Agardh C.Agardh 1831|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Gomphonemataceae|Gomphonema. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: LR537019|Pseudo-nitzschia mannii|Pseudo-nitzschia mannii Amato  Montresor 2008|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Pseudo-nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337559|Psammodictyon laevis|Psammodictyon D.G.Mann 1990|genus|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Psammodictyon. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1092|Sellaphora nigri|Sellaphora nigri De Notaris C.E.Wetzel  L.Ector 2015|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1077-1|Terpsinoe musica|Terpsinoe musica Ehrenberg 1843|species|Chromista|Ochrophyta|Bacillariophyceae|Biddulphiales|Biddulphiaceae|Terpsinoe. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC954-4|Epithemia hirudiniformis|Epithemia hirudiniformis O.Muller Rimet D.G.Mann R.Trobajo J.Zimmermann  R.Jahn 2018|species|Chromista|Ochrophyta|Bacillariophyceae|Rhopalodiales|Rhopalodiaceae|Epithemia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1090|Navicula symmetrica|Navicula symmetrica Patrick|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: GLDM-ASV40|Nitzschia fonticola|Nitzschia fonticola Grunow Grunow 1881|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Nitzschia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710436|Navicula veneta|Navicula veneta Kutzing|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: KY777689|Didymosphenia geminata|Didymosphenia geminatum Lyngbye M.Schmidt 1899|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Cymbellaceae|Didymosphenia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337565|Fragilariopsis cylindrus|Fragilariopsis cylindrus Grunow Krieger 1954|species|Chromista|Ochrophyta|Bacillariophyceae|Bacillariales|Bacillariaceae|Fragilariopsis. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1084|Navicula incarum|Navicula incarum U.Rumrich  Lange-Bertalot|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM778962|Stephanocyclus choctawhatcheeanus|Stephanocyclus A.P.Skabitschevsky 1975|genus|Chromista|Ochrophyta|Bacillariophyceae|Thalassiosirales|Thalassiosiraceae|Stephanocyclus. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710449|Pinnularia microstauron|Pinnularia microstauron Mayer 1913|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337554|Navicula salinicola|Navicula salinicola Hustedt|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710434|Mayamaea atomus|Mayamaea atomus Kutzing Lange-Bertalot 1997|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337597|Sellaphora pupula|Sellaphora pupula Kutzing Mereschkovsky 1902|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: JQ432374|Navicula rhynchocephala var. hankensis|Navicula rhynchocephala f. hankensis Skvortzow 1929|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1025|Sellaphora nigri|Sellaphora nigri De Notaris C.E.Wetzel  L.Ector 2015|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: MK639352|Eunotia perpusilla|Eunotia perpusilla Grunow 1881|species|Chromista|Ochrophyta|Bacillariophyceae|Eunotiales|Eunotiaceae|Eunotia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC1085|Navicula incarum|Navicula incarum U.Rumrich  Lange-Bertalot|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: MH125189|Skeletonema sp.|Skeletonema R.K.Greville 1865|genus|Chromista|Ochrophyta|Bacillariophyceae|Thalassiosirales|Skeletonemaceae|Skeletonema. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: TCC954-8|Epithemia hirudiniformis|Epithemia hirudiniformis O.Muller Rimet D.G.Mann R.Trobajo J.Zimmermann  R.Jahn 2018|species|Chromista|Ochrophyta|Bacillariophyceae|Rhopalodiales|Rhopalodiaceae|Epithemia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: BPAL-ASV37|Cymbella tropica|Cymbella tropica Krammer 2002|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Cymbellaceae|Cymbella. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OQ361707|Fragilaria saxoplanctonica|Fragilaria saxoplanctonica H.Lange-Bertalot  S.Ulrich 2014|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Fragilaria. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: OR699475|Navicula sanctaemargaritae|Navicula sanctamargaritae Beauger|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337600|Sellaphora pupula|Sellaphora pupula Kutzing Mereschkovsky 1902|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337613|Sellaphora pupula|Sellaphora pupula Kutzing Mereschkovsky 1902|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: HQ337591|Sellaphora caput|Sellaphora caput K.M.Evans  D.G.Mann 2009|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Sellaphoraceae|Sellaphora. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710492|Prestauroneis integra|Prestauroneis integra W.Smith K.Bruder 2008|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710470|Caloneis budensis|Caloneis budensis Grunow Krammer 1985|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula. Check if the header hasbeen through harmonization.
mozaico WARNING: Incorrect header format: AM710461|Pinnularia mesolepta|Pinnularia mesolepta Ehrenberg W.Smith 1853|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Pinnulariaceae|Pinnularia. Check if the header hasbeen through harmonization.

KeyboardInterrupt: