In [43]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.data

,seq_id,sequence,length,taxa_info
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,
...,...,...,...,...
9228,OX258991,GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...,998,
9229,PP073739,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,1155,
9230,PP073741,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,1155,
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,729,
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,626,

In [44]:
pre_processed = dt_class.pre_process_harmonized_fasta()
pre_processed

AttributeError: 'CustomFastaImport' object has no attribute 'pre_process_harmonized_fasta'

In [16]:
import pandas as pd
dt_class.data = pd.concat(
            [dt_class.data, dt_class.data["taxa_info"].str.split("|", expand=True)], axis=1
        )

In [17]:
dt_class.data.columns = [
            "seq_id",
            "sequence",
            "length",
            "all_taxa_info",
            "original_taxa_info",
            "scientificName",
            "rank",
            "kingdom",
            "phylum",
            "class",
            "order",
            "family",
            "genus"
        ]

In [4]:
dt_class.data[dt_class.data['rank'] == 'CLASS']

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus
1263,AY485503,ACTGCGAATGGCTCATTATATCAGTTATAGTTTATTTGATAATTCC...,1632,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
1840,X85389,AACCTGGTTGATCCTGCCAGTAGTCATACGCTCGTCTCAAAGATTA...,1798,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
1852,AM502026,TAGTCATACGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTAC...,1721,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
2585,FJ002126,ATAATGGGTTATTGGGATGCTTCATACTCAGTAAAAGCTACTGATG...,1054,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
2811,AM710493,ATACAACAGACCACTTCTTTGCTTTTATCGCATACGAATGTGATTT...,683,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4271,KJ011623,AGTAGTCATACGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGT...,1597,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4454,KM197150,GCTCGTAGTTGGATTTGTGGCAGTCGCGTGCGGCCCGGCATTCGTG...,330,Bacillariophyceae sp.|Bacillariophyceae|CLASS|...,Bacillariophyceae sp.,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4493,KJ011806,AGTGACCGTTACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTT...,1401,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-

In [18]:
dt_class.data['rank'] = dt_class.data['rank'].str.lower()

In [19]:
non_interest_ranks = ['kingdom', 'phylum', 'class', 'order']
dt_class.data = dt_class.data = dt_class.data[~dt_class.data['rank'].isin(non_interest_ranks)]

In [7]:
dt_class.data[dt_class.data['rank'] == 'class']

Empty DataFrame
Columns: [seq_id, sequence, length, all_taxa_info, original_taxa_info, scientificName, rank, kingdom, phylum, class, order, family, genus]
Index: []

In [20]:
import numpy as np
dt_class.data = dt_class.data.replace("-", np.nan)

In [9]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus
55,TCC162-18S-1,TGCATGTCTAAGTATAAACTGCTTTATACTGTGAAACTGCGAATGG...,1676,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,TCC208-18S-1,GAGTTTTCTCTGAATCTGCGAATGGCTCATTATATCAGTTATAGTT...,1663,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,TCC212-18S-1,TATAAGCAAATTTATACGTGAAACTGCGAATGGCTCATTATATCAG...,1627,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099,TCC715-Rbcl-1,ATTAAAGTGACCGTTACGAATCTGGTGTAATTCCTTACGCTAAAAT...,1445,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1213,TCC812-28S-1,CCCGCTGGAATTTAAGCATATAATTAAGCGGAGGAAAAGAAACTAA...,577,Nitzschia sp.|-|-|-|-|-|-|-|-,Nitzschia sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8927,OP297455,GACCGTTACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACT...,1121,Nitzschia sp.|-|-|-|-|-|-|-|-,Nitzschia sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9080,OR066516,ATCTGGYGTAATTCCTTACGCTAAAATGGGTTACTGGGATGCTTCA...,985,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9081,OR066517,ATCTGGYGTAATTCCTTACGCTAAAATGGGTTACTGGGATGCTTCA...,985,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9229,PP073739,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-,Nitzschia nandorii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9230,PP073741,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-,Nitzschia nandorii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
dt_class.data = dt_class.data.dropna(subset=["scientificName"], how="all")

In [11]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

Empty DataFrame
Columns: [seq_id, sequence, length, all_taxa_info, original_taxa_info, scientificName, rank, kingdom, phylum, class, order, family, genus]
Index: []

In [22]:
species_variants = ['species', 'form', 'variety', 'subspecies']
dt_class.data['species'] = np.where(
    dt_class.data['rank'].str.lower().isin(species_variants),
    dt_class.data['scientificName'],  # Assign scientificName if condition is met
    np.nan  # Assign NaN otherwise
)
dt_class.data['species'] = dt_class.data['species'].str.split(' ').str[0] + ' ' + dt_class.data['species'].str.split(' ').str[1]

In [23]:
dt_class.data

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9226,OX258989,AGTGACCGTGACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTT...,1005,Planothidium wetzelii|Planothidium F.E.Round ...,Planothidium wetzelii,Planothidium F.E.Round L.Bukhtiyarova 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Planothidium,NaN
9227,OX258990,GTAATCCCTTACGCTAAAATGGGTTACTGGGATGCTTCATACGCAG...,986,Psammothidium papilio|Psammothidium L.Bukhtiya...,Psammothidium papilio,Psammothidium L.Bukhtiyarova F.E.Round 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Psammothidium,NaN
9228,OX258991,GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...,998,Navicula concordia|Navicula concordia Witkowsk...,Navicula concordia,Navicula concordia Witkowski Riaux-Gobin Dani...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Naviculaceae,Navicula,Navicula concordia
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,729,Sellaphora pupula|Sellaphora pupula Kutzing Me...,Sellaphora pupula,Sellaphora pupula Kutzing Mereschkovsky 1902,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Sellaphoraceae,Sellaphora,Sellaphora pupula
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,626,Amphora copulata|Amphora copulata Kutzing Scho...,Amphora copulata,Amphora copulata Kutzing Schoeman R.E.M.Archi...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Amphipleuraceae,Frustulia,Amphora copulata

In [3]:
otl_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

In [ ]:
from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl_path)

otl = otl_handler.import_otl()
otl

In [3]:
tax = all_comp['taxa_info']
unq_taxa = tax.unique()
len(unq_taxa)

NameError: name 'all_comp' is not defined

In [5]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "../data/test_data/fasta_example_file.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.get_sequences()
dt_class.data

No TaxIDs found in the fasta file. Starting lineage file upload process.

        --------------------------------- help message ---------------------------------------
        Taxonomic information is needed to continue the in-silico analysis.
        The inputed FASTA file does not contain Taxonomic IDs.
        Please upload a TSV file containing the sequence IDs and taxonomic lineage.

        The TSV file must contain the columns:
        [seq_id, species, genus, family, order, class, phylum, subkingdom, kingdom, empire].
        Please make sure columns follow the same order before uploading.

        For the taxonomic levels where no assignment is available, please leave the cells blank.

        If your FASTA file does contain Taxonomic IDs for all sequences, please make sure these
        are present in each sequence header.
        For correct reading, these must be identified with 'taxid=' beforehand.
        For example: 'CM074756.1;taxid=8481'.
        ---------------------------------------------------------------------------------------

Operation canceled. Data currently in memory:

        seq_id             sequence  length
0   CM074756.1     GTTATTGTAGCTTATC      16
1  NC_088426.1  GCATAAAGCATGGCACTGA      19
2   PP475397.1             GTTATTGA       8

In [3]:
dt_class.get_mapping_between_seq_id_taxonomy()

{'CM074756.1': '', 'NC_088426.1': '', 'PP475397.1': ''}

In [9]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
diat_data_df = dt_class.data
diat_data_df.to_csv("try.csv")

In [13]:
dt_class.get_sequence_ids()

['CM074756.1', 'NC_088426.1', 'PP475397.1']

In [14]:
dt_class.get_sequence_lengths()

[16, 19, 8]

-----------

In [ ]:
from src.reference_database.sequence_import import *

In [8]:
fasta= '../data/input_data/diat-barcode.fasta'
cls = CustomFastaImport(fasta)
cls.read_fasta(fasta)

No TaxIDs found in the fasta file. Starting lineage file upload process.

        --------------------------------- help message ---------------------------------------
        Taxonomic information is needed to continue the in-silico analysis.
        The inputed FASTA file does not contain Taxonomic IDs.
        Please upload a TSV file containing the sequence IDs and taxonomic lineage.

        The TSV file must contain the columns:
        [seq_id, species, genus, family, order, class, phylum, subkingdom, kingdom, empire].
        Please make sure columns follow the same order before uploading.

        For the taxonomic levels where no assignment is available, please leave the cells blank.

        If your FASTA file does contain Taxonomic IDs for all sequences, please make sure these
        are present in each sequence header.
        For correct reading, these must be identified with 'taxid=' beforehand.
        For example: 'CM074756.1;taxid=8481'.
        ---------------------------------------------------------------------------------------

File uploaded successfully.

           seq_id                                           sequence  length
0      TCC6-18S-1  TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...    1688
1     TCC7a-18S-1  TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...    1680
2      TCC9-18S-1  GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...    1659
3     TCC26-18S-1  CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...    1636
4     TCC27-18S-1  TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...    1638
...           ...                                                ...     ...
9228     OX258991  GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...     998
9229     PP073739  GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...    1155
9230     PP073741  TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...    1155
9231     PP196581  TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...     729
9232     PP196582  GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...     626

[9233 rows x 3 columns]

In [9]:
dt_class.lineage_file

In [18]:
dt_class.lineage_file.columns.to_list()

AttributeError: 'NoneType' object has no attribute 'columns'

In [ ]:
from src.reference_database.db_curation import *
crabs = CrabsScriptGenerator()
json_file = "../src/reference_database/assign_tax_parameters.json"
crabs.run_assign_tax_command(json_file)

## Test with Trial example
Issue: Fasta is not formatted as it should. Should not have tax id separated by ID -> affecting how PGA reads sequences

In [ ]:
def clean_fasta_headers(input_file, output_file):
    unique_tax = set()
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        for line in infile:
            if line.startswith('>'):
                header = line.split(";", 2)
                seq_id = header[0].strip()
                tax_id = header[1].strip()
                unique_tax.add(tax_id)
                formatted_header = seq_id + " | " + tax_id + "\n"
                # print(formatted_header)
                outfile.write(formatted_header)
            else:
                outfile.write(line)

        print(len(unique_tax))

clean_fasta_headers("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference.fasta", "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta")

402

In [1]:
from src.in_silico_analysis.amplification import InSilicoAmplification
data = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"
run_name = "diat-barcode-testimport"
cutadapt = InSilicoAmplification(data, run_name=run_name)
cutadapt.run_in_silico_analysis(primer_table=primer_table)

ModuleNotFoundError: No module named 'src.in_silico_analysis'

### MultiBarcodeTools

In [2]:
from src.marker_scoring.scoring_utils import create_MultiBarcodeTools_input

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/insert/filtered"
output_dir = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/diat-multibarcode-insert.tsv"
create_MultiBarcodeTools_input(insert_path, output_dir)

Conversion complete. Output written to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/diat-multibarcode-insert.tsv

#### With joined incomplete pbs

In [1]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered/filtered_intersection and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  1060 species
2: rbcL_646F_998R, resolve additional 40 species
3: rbcL_708F1_R3_2, resolve additional 3 species
4: rbcL_708F3_R3_2, resolve additional 2 species
5: rbcL_708F2_R3_2, resolve additional 2 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode

,primer,additional_resolved_species,cumulative_resolved_species
0,rbcL_708F_DEG_R3_DEG,1060,1060
1,rbcL_646F_998R,40,1100
2,rbcL_708F1_R3_2,3,1103
3,rbcL_708F3_R3_2,2,1105
4,rbcL_708F2_R3_2,2,1107

In [2]:
from src.marker_scoring.metrics_system import *

trait.get_taxonomic_resolution(otl_total_taxa_count=1500)

,primer,additional_resolved_species,cumulative_resolved_species,taxonomic_resolution_percentage
0,rbcL_708F_DEG_R3_DEG,1060,1060,70.67
1,rbcL_646F_998R,40,1100,73.33
2,rbcL_708F1_R3_2,3,1103,73.53
3,rbcL_708F3_R3_2,2,1105,73.67
4,rbcL_708F2_R3_2,2,1107,73.80

In [3]:
trait.load_nucleotide_distance()

,Species,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Chilomonas_paramecium,-,85,-,-,-,-,-,-
1,Hannaea_arcus,2,2,2,2,2,2,2,2
2,Stauroneis_gracilior,11,17,11,11,11,11,11,11
3,Hyalosira_tropicalis,14,15,14,14,14,14,14,14
4,Adlafia_bryophila,33,39,37,37,38,38,38,38
...,...,...,...,...,...,...,...,...,...
1405,Amphora_beaufortiana,6,6,6,6,6,6,6,6
1406,Pseudo_nitzschia_multistriata,24,26,24,14,24,24,24,14
1407,Planktoniella_sol,19,36,-,-,19,19,-,-
1408,Tetramphora_chilensis,26,32,26,-,26,26,26,-
1409,Pinnularia_subgibba_var_sublinearis,1,1,1,1,1,1,1,1

#### without joined incomplete PBS

In [1]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/insert/filtered and amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/amplicon/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  1020 species
2: rbcL_646F_998R, resolve additional 31 species
3: rbcL_708F3_R3_2, resolve additional 2 species
4: rbcL_708F1_R3_2, resolve additional 1 species
5: rbcL_708F2_R3_2, resolve additional 1 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode

,primer,additional_resolved_species,cumulative_resolved_species
0,rbcL_708F_DEG_R3_DEG,1020,1020
1,rbcL_646F_998R,31,1051
2,rbcL_708F3_R3_2,2,1053
3,rbcL_708F1_R3_2,1,1054
4,rbcL_708F2_R3_2,1,1055

In [ ]:
from src.reference_database.sequence_import import CustomFastaImport

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/all_inserts/rbcL_646F_998R.fasta"
cls = CustomFastaImport()
cls.read_fasta(insert_path)

,seq_id,taxa_info,sequence,length
0,TCC7a-Rbcl-1,Fragilaria sp.,TTATACTGTATGGAAGGTATCAATCGTGCTGCAGCTGCAACAGGTG...,331
1,TCC134-Rbcl-1,Ulnaria acus,TTAAACTGTATGGAAGGTATTAACCGTGCGTCAGCTGCAACAGGTG...,331
2,TCC425-Rbcl-1,Nitzschia palea,TTAAACTGTATGGAAGGTATTAACCGTGCTTCAGCTGCAACAGGTG...,331
3,TCC426-Rbcl-1,Gomphonema parvulum,TTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
4,TCC429-Rbcl-1,Gomphonema lagenula,TTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
...,...,...,...,...
4599,OX258989,Planothidium wetzelii,TTATACTGTATGGAAGGTATTAACCGTGCTTCTTCAGCTACAGGTG...,331
4600,OX258990,Psammothidium papilio,TTAAACTGTATGGAAGGTATCAACCGTGCTTCTTCAGCTACAGGTG...,331
4601,OX258991,Navicula concordia,TTATACTGTATGGAAGGTATTAACCGTGCATCAGCAGCTACAGGTG...,331
4602,PP073739,Nitzschia nandorii,CTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
4603,PP073741,Nitzschia nandorii,CTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331

### Binding

In [12]:
from src.marker_scoring.metrics_system import MetricsSystemExecutor

#output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data"
otl1 = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Portugal_taxonlist_diatoms_harmonized.tsv"

cls = MetricsSystemExecutor(results_folder=output_folder, otl=otl1, primer_table='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-primers.tsv')

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/incomplete_pbs/filtered/filtered_intersection.

In [2]:
cls.sort_otl_level_results()

mozaiko INFO: Processing OTL-level results in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/otl_level_results
mozaiko INFO: Divergence score file: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/otl_level_results/divergence_score_per_taxon.tsv
mozaiko INFO: Divergence score columns: Index(['family', 'genus', 'species', 'rank', 'rbcL_708F_DEG_R3_DEG',
       'rbcL_646F_998R', 'rbcL_708F1_R3_2', 'rbcL_708F2_R3_2',
       'rbcL_708F3_R3_2', 'rbcL_708F2_R3_1', 'rbcL_708F1_R3_1',
       'rbcL_708F3_R3_1'],
      dtype='object')
mozaiko INFO: Required columns found in divergence score file.
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F3_R3-2.tsv...
mozaiko INFO: Primer name: rbcL_708F3_R3_2
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F-DEG_R3-DEG.tsv...
mozaiko INFO: Primer name: rbcL_708F_DEG_R3_DEG
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F2_R3-2.tsv...
mozaiko INFO: Primer name: rbcL_708F2_R3_2
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F1_R3-2.tsv...
mozaiko INFO: Primer name: rbcL_708F1_R3_2
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_646F_998R.tsv...
mozaiko INFO: Primer name: rbcL_646F_998R
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F3_R3-1.tsv...
mozaiko INFO: Primer name: rbcL_708F3_R3_1
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F1_R3-1.tsv...
mozaiko INFO: Primer name: rbcL_708F1_R3_1
mozaiko INFO: Processing----- binding_otl_level_results_rbcL_708F2_R3-1.tsv...
mozaiko INFO: Primer name: rbcL_708F2_R3_1
mozaiko INFO: Successfully processed OTL-level files: binding_otl_level_results_rbcL_708F3_R3-2.tsv, binding_otl_level_results_rbcL_708F-DEG_R3-DEG.tsv, binding_otl_level_results_rbcL_708F2_R3-2.tsv, binding_otl_level_results_rbcL_708F1_R3-2.tsv, binding_otl_level_results_rbcL_646F_998R.tsv, binding_otl_level_results_rbcL_708F3_R3-1.tsv, binding_otl_level_results_rbcL_708F1_R3-1.tsv, binding_otl_level_results_rbcL_708F2_R3-1.tsv

In [2]:
abc = cls.get_reference_database_quality()
abc

                      barcoded_taxa_one_plus  ratio_barcoded_taxa
rbcL_708F1_R3-1                        30.64                 0.36
rbcL_708F2_R3-2                        30.64                 0.35
rbcL_708F-DEG_R3-DEG                   31.24                 0.36
rbcL_708F1_R3-2                        30.64                 0.36
rbcL_646F_998R                         29.60                 0.34
rbcL_708F2_R3-1                        30.64                 0.35
rbcL_708F3_R3-2                        29.45                 0.36
rbcL_708F3_R3-1                        29.45                 0.36

In [3]:
primer_pbs, gc = cls.get_primer_pbs_analysis()

mozaiko INFO: Retrieving primer-PBS statistics.

In [4]:
primerex = primer_pbs['rbcL_646F_998R']

In [5]:
primerex

,seq_id,taxon,family,genus,species,rank,full_len_mismatch_sum,three_end_mismatch_sum,gc_matches_fwd,gc_matches_rev,min_tm,delta_tm
0,TCC7a-Rbcl-1,Fragilaria H.C.Lyngbye 1819,Fragilariaceae,Fragilaria,nan,genus,0,0,0,0,50.86,2.01
1,TCC134-Rbcl-1,Ulnaria acus Kutzing M.Aboal 2003,Fragilariaceae,Synedra,Ulnaria acus,species,0,0,0,0,50.86,2.01
2,TCC425-Rbcl-1,Nitzschia palea Kutzing W.Smith 1856,Bacillariaceae,Nitzschia,Nitzschia palea,species,0,0,0,0,50.86,2.01
3,TCC426-Rbcl-1,Gomphonema parvulum Kutzing Kutzing 1849,Gomphonemataceae,Gomphonema,Gomphonema parvulum,species,0,0,0,0,52.81,0.06
4,TCC429-Rbcl-1,Gomphonema lagenula,Gomphonemataceae,Gomphonema,Gomphonema lagenula,species,0,0,0,0,52.81,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...
3566,OX258986,Navicula criophiliforma Witkowski Riaux-Gobin ...,Naviculaceae,Navicula,Navicula criophiliforma,species,0,0,0,0,50.86,2.01
3567,OX258987,Chamaepinnularia gerlachei B.Van de Vijver M....,Naviculaceae,Chamaepinnularia,Chamaepinnularia gerlachei,species,1,0,0,0,52.81,1.58
3568,OX258988,Nitzschia annewillemsiana Hamsher et al. 2016,Bacillariaceae,Nitzschia,Nitzschia annewillemsiana,species,0,0,0,0,50.86,2.01
3569,OX258989,Planothidium F.E.Round L.Bukhtiyarova 1996,Achnanthidiaceae,Planothidium,nan,genus,0,0,0,0,52.81,0.06
3570,OX258990,Psammothidium L.Bukhtiyarova F.E.Round 1996,Achnanthidiaceae,Psammothidium,nan,genus,0,0,0,0,52.81,0.06

In [38]:
primerex.to_csv("primerex.csv")

In [1]:
from src.marker_scoring.metrics_system import *

bind = Binding(otl=cls.otl)
result_full_len = bind.process_analysis_per_taxon(primerex, 'sum', 'full_len_mismatch_sum')

NameError: name 'cls' is not defined

In [8]:
result_three_end = bind.process_analysis_per_taxon(primerex, 'max', 'three_end_mismatch_sum')

In [10]:
# GC Match Analysis
bind.get_total_gc_matches(primerex)
tax_lev_gc = bind.process_analysis_per_taxon(primerex, operation="min", analysis_name="gc_matches_score")
# Temperature Melting (Tm) Analysis
tax_lev_min_tm = bind.process_analysis_per_taxon(primerex, operation="min", analysis_name="min_tm")

In [2]:
ref_qual = cls.comprehensive_primer_analysis(output_folder, save_otl_level_results=True)

In [3]:
ref_qual

,barcoded_taxa_one_plus,ratio_barcoded_taxa,mismatch_score,priming_ratio_sum,gc_matches_across_taxon,min_tm_cv,tm_score,amplification_success_percent
primer,,,,,,,,
rbcL_708F1_R3_1,10.61,0.27,355,14.57,0.0,0.67,17.10,81.21
rbcL_708F2_R3_2,10.61,0.24,396,140.95,0.0,0.67,17.13,84.78
rbcL_708F_DEG_R3_DEG,10.61,0.25,145,10.23,0.0,0.66,16.95,87.40
rbcL_708F1_R3_2,10.61,0.27,548,91.35,0.0,0.67,17.07,80.95
rbcL_646F_998R,10.61,0.23,104,41.92,0.0,2.20,45.05,90.81
rbcL_708F2_R3_1,10.61,0.24,202,22.33,0.0,0.67,17.16,85.04
rbcL_708F3_R3_2,10.61,0.25,683,69.22,0.0,0.62,16.26,75.93
rbcL_708F3_R3_1,10.61,0.25,496,11.25,0.0,0.62,16.30,76.00

In [2]:
cls.get_traits_and_resolution()

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/multibarcode

                      divergence_score
primer
rbcL_708F_DEG_R3_DEG              5.83
rbcL_646F_998R                    5.98
rbcL_708F1_R3_2                   5.83
rbcL_708F2_R3_2                   5.83
rbcL_708F3_R3_2                   5.68
rbcL_708F2_R3_1                   5.83
rbcL_708F1_R3_1                   5.83
rbcL_708F3_R3_1                   5.68

In [6]:
metrics_df = cls.join_analysis_results()
metrics_df

mozaiko INFO: Retrieving primer-PBS statistics.
mozaiko INFO: Retriving information on the Reference Database Quality.
mozaiko INFO: Calculating the number of barcodes per FASTA.
mozaiko INFO: Calculating the number of barcodes per FASTA.
0.16426756985605417
0.12295081967213115
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/insert/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/insert/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/insert/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  912 species
2: rbcL_646F_998R, resolve additional 37 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-dereped/insert/multibarcode

,barcoded_taxa_one_plus,ratio_barcoded_taxa,mismatch_score,priming_ratio_sum,gc_matches_across_taxon,min_tm_cv,tm_score,amplification_success_percent,taxonomic_resolution
primer,,,,,,,,,
rbcL_708F_DEG_R3_DEG,11.81,0.16,145,10.23,0.0,0.66,17.73,87.38,5.83
rbcL_646F_998R,7.32,0.12,104,41.92,0.0,2.20,45.59,90.79,5.83

In [10]:
ranked_df = cls.rank_primers(metrics_df, save_intermediate_ranks=False)
ranked_df

TypeError: MetricsSystemExecutor.rank_primers() got multiple values for argument 'save_intermediate_ranks'

##### ----------------------------------- END OF BINDING ---------------------------------------------

In [1]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_12SMiFish-U.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_12SMiFish-U.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_12SMiFish-U.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_12SMiFish-U.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_MarVer1.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_MarVer1.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-b.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-b.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-c.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-c.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Am12s.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Am12s.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_12S-V5-c.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_12S-V5-c.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Chon01.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Chon01.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Fuller1998.fasta']' returned non-zero exit status 1.

analysis_step,original_database,amplicon,amplicon-filtered,insert,insert-filtered,all_complete_pbs,all_complete_pbs-filtered,all_inserts
primer_name,,,,,,,,
12S_12S-V5-a,NA,824,823,824,823,1036,6,823
12S_12S-V5-b,NA,1016,1015,1016,1015,1041,NA,1015
12S_12S-V5-c,NA,718,715,718,715,745,NA,715
12S_12SMiFish-U,NA,NA,NA,150,150,348,171,150
12S_Ac12s,NA,93,93,785,780,1563,5,780
12S_AcMDB07,NA,763,755,761,753,782,5,753
12S_Am12s,NA,69,69,736,729,752,9,729
12S_Chon01,NA,728,725,728,725,745,6,725
12S_Elas02,NA,16,16,603,603,648,14,603
12S_Fuller1998,NA,NA,NA,NA,NA,NA,NA,NA
12S_Hauck2019a,NA,NA,NA,NA,NA,NA,NA,NA
12S_MarVer1,NA,743,742,743,742,769,NA,742
12S_MiFish-E,NA,97,97,590,590,644,24,590
12S_Tele01,NA,762,759,762,759,781,2,759
12S_Tele02,NA,653,652,692,691,751,31,691
12S_V12S-U,NA,741,741,741,741,763,1,741
12S_Vert01,NA,1016,1015,1016,1015,1599,3,1015
original_database,2722,NA,NA,NA,NA,NA,NA,NA

## Mismatches

In [3]:
from src.marker_scoring.metrics_system import *
from src.marker_scoring.scoring_utils import *

amp_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/amplicon/filtered"
insert_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/insert/filtered"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"


cls_instance = Binding()
analysis_results, gc = cls_instance.primer_pbs_analysis(amp_folder, insert_folder, primer_table)

In [4]:
gc

                      forward_primer_gc_fraction  reverse_primer_gc_fraction
primer_name
rbcL_646F_998R                          0.500000                    0.370370
rbcL_708F1_R3-1                         0.296296                    0.363636
rbcL_708F1_R3-2                         0.296296                    0.363636
rbcL_708F2_R3-1                         0.269231                    0.363636
rbcL_708F2_R3-2                         0.269231                    0.363636
rbcL_708F3_R3-1                         0.296296                    0.363636
rbcL_708F3_R3-2                         0.296296                    0.363636
rbcL_708F-DEG_R3-DEG                    0.280000                    0.363636

In [ ]:
otl = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl)
otl_handler.import_otl()
total_otl_taxa_count = otl_handler.total_taxa
otl_unique_taxa_set = otl_handler.otl_taxa_set

{'Achnanthes brevipes var. brevipes': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes brevipes'}, 'Achnanthes brevipes var. intermedia Kutzing Cleve 1895': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes brevipes'}, 'Achnanthes coarctata Brebisson ex W.Smith Grunow 1880': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes coarctata'}, 'Achnanthes curtissima J.R.Carter 1963': {'family': 'Achnanthidiaceae', 'genus': 'Psammothidium', 'species': 'Achnanthes curtissima'}, 'Achnanthes exigua Grunow 1880': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes exigua'}, 'Achnanthes hintzii Lange-Bertalot  Krammer 1989': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes hintzii'}, 'Achnanthes inflata Kutzing Grunow 1867': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes inflata'}, 'Achnanthes lemmermannii Hustedt 1933': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes lemmermannii'}, 'Achnanthes lutheri Hustedt 1933': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes lutheri'}, 'Achnanthes minuscula Hustedt 1945': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes minuscula'}, 'Achnanthes nodosa Cleve 1900': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes nodosa'}, 'Achnanthes oblongella strup 1902': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes oblongella'}, 'Achnanthes petersenii Hustedt 1937': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes petersenii'}, 'Achnanthes pusilla Woodhead  Tweed 1960': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes pusilla'}, 'Achnanthes semiaperta Hustedt 1945': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes semiaperta'}, 'Achnanthes Bory 1822': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': nan}, 'Achnanthes subexigua Hustedt 1934': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes subexigua'}, 'Achnanthes subsalsa J.B.Petersen 1928': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes subsalsa'}, 'Achnanthes thermalis Rabenhorst Schoenfeld 1907': {'family': 'Achnanthidiaceae', 'genus': 'Crenotia', 'species': 'Achnanthes thermalis'}, 'Achnanthes trinodis Ehrenberg 1870': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthes trinodis'}, 'Achnanthidium affine Grunow Czarnecki 1994': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium affine'}, 'Achnanthidium atomoides O.Monnier Lange-Bert.  L.Ector 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium atomoides'}, 'Achnanthidium atomus Hustedt Monnier Lange-Bertalot  Ector 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium atomus'}, 'Achnanthidium caledonicum Lange-Bertalot Lange-Bertalot 1999': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium caledonicum'}, 'Achnanthidium catenatum Bily  Marvan Lange-Bertalot 1999': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium catenatum'}, 'Achnanthidium delmontii F.Peres R.le Cohu  A.Barthes 2012': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium delmontii'}, 'Achnanthidium druartii Rimet  Coute 2010': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium druartii'}, 'Achnanthidium eutrophilum Lange-Bertalot Lange-Bertalot 1999': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium eutrophilum'}, 'Achnanthidium exile Kutzing Heiberg 1863': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium exile'}, 'Achnanthidium F.T.Kutzing 1844': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': nan}, 'Achnanthidium jackii Rabenhorst 1861': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium jackii'}, 'Achnanthidium kranzii Lange-Bertalot Round  Bukhtiyarova 1996': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium kranzii'}, 'Achnanthidium lineare W.Smith 1855': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium lineare'}, 'Achnanthidium linearioides Lange-Bert. Lange-Bert.': {'family': 'Achnanthidiaceae', 'genus': 'Rossithidium', 'species': 'Achnanthidium linearioides'}, 'Achnanthidium macrocephalum Hustedt Round  Bukhtiyarova 1996': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium macrocephalum'}, 'Achnanthidium minutissimum Kutzing Czarnecki 1994': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium minutissimum'}, 'Achnanthidium neomicrocephalum Lange-Bertalot  F.Staab 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium neomicrocephalum'}, 'Achnanthidium pfisteri H.Lange-Bertalot 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium pfisteri'}, 'Achnanthidium pyrenaicum Hustedt H.Kobayasi 1997': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium pyrenaicum'}, 'Achnanthidium rivulare Potapova  Ponader 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium rivulare'}, 'Achnanthidium rosenstockii Lange-Bertalot Lange-Bertalot 2004': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium rosenstockii'}, 'Achnanthidium saprophilum H.Kobayasi  S.Mayama Round  L.Bukhtiyarova 1996': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium saprophilum'}, 'Achnanthidium straubianum Lange-Bertalot Lange-Bertalot 1999': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium straubianum'}, 'Achnanthidium strictum E.Reichardt 2004': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium strictum'}, 'Achnanthidium subatomus Hustedt Lange-Bertalot 1999': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium subatomus'}, 'Achnanthidium subhudsonis Hustedt H.Kobayasi 2006': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium subhudsonis'}, 'Achnanthidium temniskovae P.Ivanov  L.Ector 2006': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium temniskovae'}, 'Achnanthidium thienemannii Hustedt Lange-Bertalot': {'family': 'Achnanthaceae', 'genus': 'Achnanthes', 'species': 'Achnanthidium thienemannii'}, 'Achnanthidium zhakovschikovii M.Potapova 2006': {'family': 'Achnanthidiaceae', 'genus': 'Achnanthidium', 'species': 'Achnanthidium zhakovschikovii'}, 'Adlafia aquaeductae Krasske Gerd Moser Lange-Bertalot  D.Metzeltin 1998': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': 'Adlafia aquaeductae'}, 'Adlafia bryophila J.B.Petersen Gerd Moser Lange-Bertalot  D.Metzeltin 1998': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': 'Adlafia bryophila'}, 'Adlafia langebertalotii O.Monnier  Ector 2012': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': 'Adlafia langebertalotii'}, 'Adlafia minuscula var. minuscula': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Adlafia minuscula'}, 'Adlafia minuscula var. muralis Grunow Lange-Bertalot 1999': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Adlafia minuscula'}, 'Adlafia parabryophila Lange-Bertalot Gerd Moser Lange-Bertalot  D.Metzeltin 1998': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': 'Adlafia parabryophila'}, 'Adlafia G.Moser H.Lange-Bertalot  D.Metzeltin 1998': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': nan}, 'Adlafia suchlandtii Hustedt Lange-Bertalot 1998': {'family': 'Naviculaceae', 'genus': 'Adlafia', 'species': 'Adlafia suchlandtii'}, 'Amphipleura pellucida Kutzing Kutzing 1844': {'family': 'Amphipleuraceae', 'genus': 'Amphipleura', 'species': 'Amphipleura pellucida'}, 'Amphipleura F.T.Kutzing 1844': {'family': 'Amphipleuraceae', 'genus': 'Amphipleura', 'species': nan}, 'Amphora aequalis Krammer 1980': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora aequalis'}, 'Amphora affinis Kutzing 1844': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora affinis'}, 'Amphora calumetica Thomas ex Wolle M.Peragallo 1897': {'family': 'Amphipleuraceae', 'genus': 'Amphiprora', 'species': 'Amphora calumetica'}, 'Amphora copulata Kutzing Schoeman  R.E.M.Archibald 1986': {'family': 'Amphipleuraceae', 'genus': 'Frustulia', 'species': 'Amphora copulata'}, 'Amphora eximia J.R.Carter 1974': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora eximia'}, 'Amphora hemicycla Stoermer  J.J.Yang': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora hemicycla'}, 'Amphora inariensis Krammer 1980': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora inariensis'}, 'Amphora indistincta Levkov 2009': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora indistincta'}, 'Amphora lange-bertalotii Levkov  Metzeltin 2009': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora lange-bertalotii'}, 'Amphora minutissima W.Smith 1853': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora minutissima'}, 'Amphora ovalis Kutzing Kutzing 1844': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora ovalis'}, 'Amphora pediculus Kutzing Grunow ex A.Schmidt 1875': {'family': 'Catenulaceae', 'genus': 'Amphora', 'species': 'Amphora pediculus'}, 'Aneumastus balticus Lange-Bertalot 2001': {'family': 'Mastogloiaceae', 'genus': 'Aneumastus', 'species': 'Aneumastus balticus'}, 'Aneumastus minor Lange-Bertalot 1993': {'family': 'Mastogloiaceae', 'genus': 'Aneumastus', 'species': 'Aneumastus minor'}, 'Aneumastus D.G.Mann  A.J.Stickle 1990': {'family': 'Mastogloiaceae', 'genus': 'Aneumastus', 'species': nan}, 'Aneumastus stroesei strup D.G.Mann 1990': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Aneumastus stroesei'}, 'Aneumastus tusculus Ehrenberg D.G.Mann  Stickle 1990': {'family': 'Mastogloiaceae', 'genus': 'Aneumastus', 'species': 'Aneumastus tusculus'}, 'Anomoeoneis E.Pfitzer 1871': {'family': 'Anomoeoneidaceae', 'genus': 'Anomoeoneis', 'species': nan}, 'Anomoeoneis sphaerophora E.Pfitzer 1871': {'family': 'Anomoeoneidaceae', 'genus': 'Anomoeoneis', 'species': 'Anomoeoneis sphaerophora'}, 'Berkeleya rutilans Trentepohl ex Roth Grunow 1880': {'family': 'Berkeleyaceae', 'genus': 'Berkeleya', 'species': 'Berkeleya rutilans'}, 'Brachysira brebissonii H.Lange-Bertalot  G.Moser 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira brebissonii'}, 'Brachysira calcicola Lange-Bertalot 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira calcicola'}, 'Brachysira follis Ehrenberg R.Ross 1986': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Brachysira follis'}, 'Brachysira garrensis Lange-Bertalot  Krammer Lange-Bertalot 1994': {'family': 'Anomoeoneidaceae', 'genus': 'Anomoeoneis', 'species': 'Brachysira garrensis'}, 'Brachysira hofmanniae Lange-Bertalot 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira hofmanniae'}, 'Brachysira intermedia strup Lange-Bertalot 1994': {'family': 'Anomoeoneidaceae', 'genus': 'Anomoeoneis', 'species': 'Brachysira intermedia'}, 'Brachysira liliana Lange-Bertalot 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira liliana'}, 'Brachysira neglectissima Lange-Bertalot 2004': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira neglectissima'}, 'Brachysira neoexilis Lange-Bertalot 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira neoexilis'}, 'Brachysira procera Lange-Bertalot  Gerd Moser 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira procera'}, 'Brachysira serians Brebisson Round  D.G.Mann 1981': {'family': 'Amphipleuraceae', 'genus': 'Frustulia', 'species': 'Brachysira serians'}, 'Brachysira F.T.Kutzing 1836': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': nan}, 'Brachysira styriaca Grunow R.Ross 1986': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Brachysira styriaca'}, 'Brachysira vitrea Grunow R.Ross 1986': {'family': 'Gomphonemataceae', 'genus': 'Gomphonema', 'species': 'Brachysira vitrea'}, 'Brachysira wygaschii Lange-Bertalot 1994': {'family': 'Brachysiraceae', 'genus': 'Brachysira', 'species': 'Brachysira wygaschii'}, 'Brachysira zellensis Grunow Round  D.G.Mann 1981': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Brachysira zellensis'}, 'Caloneis aerophila W.Bock 1963': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis aerophila'}, 'Caloneis alpestris Grunow Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis alpestris'}, 'Caloneis amphisbaena f. amphisbaena': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis amphisbaena'}, 'Caloneis bacillum Grunow Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis bacillum'}, 'Caloneis budensis Grunow Krammer 1985': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis budensis'}, 'Caloneis constans Reichardt 1994': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis constans'}, 'Caloneis fontinalis Grunow Cleve-Euler 1932': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis fontinalis'}, 'Caloneis lancettula Schulz Lange-Bertalot  Witkowski 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis lancettula'}, 'Caloneis latiuscula Kutzing Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis latiuscula'}, 'Caloneis lauta Carter  Bailey-Watts 1981': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis lauta'}, 'Caloneis lepidula Grunow Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis lepidula'}, 'Caloneis leptosoma Grunow Krammer 1985': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis leptosoma'}, 'Caloneis macedonica Hustedt 1945': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis macedonica'}, 'Caloneis molaris Grunow Krammer 1985': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis molaris'}, 'Caloneis obtusa W.Smith Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Caloneis obtusa'}, 'Caloneis permagna Bailey Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis permagna'}, 'Caloneis pulchra Messikommer 1927': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis pulchra'}, 'Caloneis schumanniana Grunow Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis schumanniana'}, 'Caloneis silicula Ehrenberg Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis silicula'}, 'Caloneis P.T.Cleve 1894': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': nan}, 'Caloneis sublinearis McCall 1933': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis sublinearis'}, 'Caloneis tenuis W.Gregory Krammer 1985': {'family': 'Pinnulariaceae', 'genus': 'Pinnularia', 'species': 'Caloneis tenuis'}, 'Caloneis thermalis Grunow Krammer 1985': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis thermalis'}, 'Caloneis undulata Skvortzow  Meyer 1928': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis undulata'}, 'Caloneis vasileyevae Lange-Bert. et al.': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis vasileyevae'}, 'Caloneis westii W.Smith Hendey 1964': {'family': 'Naviculaceae', 'genus': 'Caloneis', 'species': 'Caloneis westii'}, 'Campylodiscus hibernicus Ehrenberg 1845': {'family': 'Surirellaceae', 'genus': 'Campylodiscus', 'species': 'Campylodiscus hibernicus'}, 'Campylodiscus noricus Ehrenberg ex Kutzing 1844': {'family': 'Surirellaceae', 'genus': 'Campylodiscus', 'species': 'Campylodiscus noricus'}, 'Campylodiscus C.G.Ehrenberg ex F.T.Kutzing 1844': {'family': 'Surirellaceae', 'genus': 'Campylodiscus', 'species': nan}, 'Cavinula cocconeiformis Gregory ex Greville D.G.Mann  A.J.Stickle 1990': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula cocconeiformis'}, 'Cavinula intractata Hustedt Lange-Bertalot 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula intractata'}, 'Cavinula jaernefeltii Hustedt D.G.Mann  A.J.Stickle 1990': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula jaernefeltii'}, 'Cavinula lapidosa Krasske Lange-Bertalot 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula lapidosa'}, 'Cavinula pseudoscutiformis Hustedt D.G.Mann  A.J.Stickle 1990': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula pseudoscutiformis'}, 'Cavinula pusio Cleve Lange-Bertalot 2004': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula pusio'}, 'Cavinula scutelloides W.Smith Lange-Bertalot 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula scutelloides'}, 'Cavinula D.G.Mann  A.J.Stickle 1990': {'family': 'Cavinulaceae', 'genus': 'Cavinula', 'species': nan}, 'Cavinula variostriata Krasske D.G.Mann  A.J.Stickle 1990': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Cavinula variostriata'}, 'Chamaepinnularia begeri Krasske Lange-Bertalot 1996': {'family': 'Naviculaceae', 'genus': 'Chamaepinnularia', 'species': 'Chamaepinnularia begeri'}, 'Chamaepinnularia evanida Hustedt Lange-Bertalot 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Chamaepinnularia evanida'}, 'Chamaepinnularia hassiaca Krasske Cantonati  Lange-Bertalot 2009': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Chamaepinnularia hassiaca'}, 'Chamaepinnularia mediocris Krasske Lange-Bertalot  Krammer 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Chamaepinnularia mediocris'}, 'Chamaepinnularia muscicola J.B.Petersen M.S.Kulikovskiy Lange-Bert.  Witkowski 2010': {'family': 'Naviculaceae', 'genus': 'Chamaepinnularia', 'species': 'Chamaepinnularia muscicola'}, 'Chamaepinnularia soehrensis Krasske Lange-Bertalot  Krammer 1996': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Chamaepinnularia soehrensis'}, 'Chamaepinnularia H.Lange-Bertalot  K.Krammer 1996': {'family': 'Naviculaceae', 'genus': 'Chamaepinnularia', 'species': nan}, 'Chamaepinnularia submuscicola Krasske H.Lange-Bertalot 1998': {'family': 'Naviculaceae', 'genus': 'Navicula', 'species': 'Chamaepinnularia submuscicola'}, 'Cocconeis disculus Schumann Cleve 1882': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis disculus'}, 'Cocconeis euglyptoides Geitler H.Lange-Bertalot 2004': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis euglyptoides'}, 'Cocconeis neodiminuta Krammer 1990': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis neodiminuta'}, 'Cocconeis neothumensis Krammer 1991': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis neothumensis'}, 'Cocconeis pediculus Ehrenberg 1838': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis pediculus'}, 'Cocconeis placentra 1941': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis placentra'}, 'Cocconeis placentula var. euglypta Ehrenb. Cleve': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis placentula'}, 'Cocconeis placentula var. intermedia Heribaud  M.Peragallo Cleve 1895': {'family': 'Cocconeidaceae', 'genus': 'Cocconeis', 'species': 'Cocconeis placentula'}, 'Cocconeis placentula var. klinoraphis Geitler 1927': {'family': 'Cocconeidaceae', 'genus': 'Cocconei

In [3]:
process = cls_instance.iterate_over_primer_pbs_df(analysis_results, add_otl_taxa=False, otl_taxa_set=otl_unique_taxa_set)

In [4]:
attempt = cls_instance.get_primer_df('rbcL_708F_DEG_R3_DEG')

In [5]:
primer_pbs_df, primer_gc_df = cls_instance.primer_pbs_analysis(
    "../data/test_data/amplicon-test",
    "../data/test_data/insert-test",
    "../data/test_data/test_primer_table.tsv",
    save_results=False,
)

In [8]:
primer_pbs_df

{}

In [ ]:
gcm = cls_instance.get_total_gc_matches(attempt)
gcm['gc_matches_score'].max()

np.int64(1)

In [11]:
gcm_tax = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='min', analysis_name='gc_matches_score')
gcm_tax

                             gc_matches_score
taxon
 Acanthoceras sp.                           0
 Achnanthes brevipes                        0
 Achnanthes coarctata                       0
 Achnanthes elongata                        0
 Achnanthes longboardia                     0
...                                       ...
Ulnaria ulna var. claviceps                 0
Ulnaria ulna var. danica                    0
Ulnaria ungeriana                           0
Ulnaria ungeriana terato                    0
terato                                      0

[4056 rows x 1 columns]

In [1]:
import os
import pandas as pd

def calculate_missing_scientific_names(folder_path):
    results = []

    for file_name in os.listdir(folder_path):
        if file_name.endswith(".tsv"):
            file_path = os.path.join(folder_path, file_name)

            try:
                df = pd.read_csv(file_path, sep='\t')

                if 'scientificName' in df.columns:
                    total_entries = len(df)
                    missing_entries = (df['scientificName'] == '-').sum()

                    percentage_missing = (missing_entries / total_entries) * 100 if total_entries > 0 else 0

                    results.append({
                        'File Name': file_name,
                        'Percentage Missing': round(percentage_missing, 2)
                    })
                else:
                    results.append({
                        'File Name': file_name,
                        'Percentage Missing': 'Column not found'
                    })
            except Exception as e:
                results.append({
                    'File Name': file_name,
                    'Percentage Missing': f'Error: {e}'
                })

    return pd.DataFrame(results)

In [9]:
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi"
summary_df = calculate_missing_scientific_names(folder_path)
# order ascending by 'Percentage Missing'
summary_df.sort_values(by='Percentage Missing', ascending=False)

                               File Name  Percentage Missing
7   France_taxonlists_bmi_harmonized.tsv                8.72
1   Austria_taxonlist_bmi_harmonized.tsv                8.63
2   Poland_taxonlists_bmi_harmonized.tsv                4.89
4   Germany_taxonlist_bmi_harmonized.tsv                3.83
0    Sweden_taxonlist_bmi_harmonized.tsv                3.78
5  Portugal_taxonlist_bmi_harmonized.tsv                2.94
6   Finland_taxonlist_bmi_harmonized.tsv                2.73
3     Czech_taxonlist_bmi_harmonized.tsv                1.74

In [3]:
summary_df['Percentage Missing'].mean()

np.float64(4.6575)

In [11]:
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia"
summary_df = calculate_missing_scientific_names(folder_path)
summary_df.sort_values(by='Percentage Missing', ascending=False)

                                   File Name  Percentage Missing
2     Czech_taxonlist_diatoms_harmonized.tsv                3.82
1   Ireland_taxonlist_diatoms_harmonized.tsv                2.56
3   Finland_taxonlist_diatoms_harmonized.tsv                2.50
7    Sweden_taxonlist_diatoms_harmonized.tsv                2.06
6   Austria_taxonlist_diatoms_harmonized.tsv                2.01
8  Portugal_taxonlist_diatoms_harmonized.tsv                1.30
0   Germany_taxonlist_diatoms_harmonized.tsv                1.18
4    france_taxonlist_diatoms_harmonized.tsv                0.61
5    poland_taxonlitst_diatom_harmonized.tsv                0.00

In [14]:
summary_df['Percentage Missing'].mean()

np.float64(1.7817928308521056)

### -------------------------- HERE ---------------------

In [1]:
from src.marker_scoring.metrics_system import *

otl = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Portugal_taxonlist_diatoms_harmonized.tsv'
tandres = TraitsAndResolution(otl, results_folder='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed')
tandres.multibarcode_output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/multibarcode"
nuc_mat = tandres.load_nucleotide_distance()

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/incomplete_pbs/filtered/filtered_intersection.
                                               Species          family  \
0                                 Achnanthes Bory 1822   Achnanthaceae
1          Achnanthes biasolettiana var. biasolettiana   Achnanthaceae
2                 Achnanthes biasolettiana Grunow 1880   Achnanthaceae
3                     Achnanthes bioretii Germain 1957   Achnanthaceae
4        Achnanthes chlidanos M.H.Hohn  Hellerman 1963   Achnanthaceae
..                                                 ...             ...
664               Tryblionella levidensis W.Smith 1856  Bacillariaceae
665              Ulnaria biceps Kutzing P.Compere 2001  Fragilariaceae
666  Ulnaria delicatissima W.Smith M.Aboal  P.C.Sil...  Fragilariaceae
667                Ulnaria ulna Nitzsch P.Compere 2001  Fragilariaceae
668           Ulnaria ulna var. acus Kutz. Lange-Bert.  Fragilariaceae

            genus                   species     rank
0      Achnanthes                       NaN    genus
1      Achnanthes  Achnanthes biasolettiana  species
2      Achnanthes  Achnanthes biasolettiana  species
3      Achnanthes       Achnanthes bioretii  species
4      Achnanthes      Achnanthes chlidanos  species
..            ...                       ...      ...
664  Tryblionella   Tryblionella levidensis  species
665       Synedra            Ulnaria biceps  species
666       Synedra     Ulnaria delicatissima  species
667       Synedra              Ulnaria ulna  species
668       Synedra              Ulnaria ulna  species

[669 rows x 5 columns]

In [2]:
nuc_mat

,input_taxa,family,genus,species,rank,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F2_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Achnanthes Bory 1822,Achnanthaceae,Achnanthes,NaN,genus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Achnanthes biasolettiana var. biasolettiana,Achnanthaceae,Achnanthes,Achnanthes biasolettiana,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Achnanthes biasolettiana Grunow 1880,Achnanthaceae,Achnanthes,Achnanthes biasolettiana,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Achnanthes bioretii Germain 1957,Achnanthaceae,Achnanthes,Achnanthes bioretii,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Achnanthes chlidanos M.H.Hohn Hellerman 1963,Achnanthaceae,Achnanthes,Achnanthes chlidanos,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,Tryblionella levidensis W.Smith 1856,Bacillariaceae,Tryblionella,Tryblionella levidensis,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,Ulnaria biceps Kutzing P.Compere 2001,Fragilariaceae,Synedra,Ulnaria biceps,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,Ulnaria delicatissima W.Smith M.Aboal P.C.Sil...,Fragilariaceae,Synedra,Ulnaria delicatissima,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,Ulnaria ulna Nitzsch P.Compere 2001,Fragilariaceae,Synedra,Ulnaria ulna,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,Ulnaria ulna var. acus Kutz. Lange-Bert.,Fragilariaceae,Synedra,Ulnaria ulna,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
tandres.insert_folder_path

'/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data//home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered'

In [3]:
tandres.get_length_stats_for_amplicon_and_insert('/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon/filtered')

,insert_avg_length,amplicon_min_length,amplicon_max_length,amplicon_avg_length
rbcL_708F1_R3-1,262.94,227,312,311.94
rbcL_708F2_R3-2,262.94,227,312,311.94
rbcL_708F-DEG_R3-DEG,262.95,227,312,311.95
rbcL_708F1_R3-2,262.94,227,312,311.94
rbcL_646F_998R,330.91,227,379,378.91
rbcL_708F2_R3-1,262.94,227,312,311.94
rbcL_708F3_R3-2,262.94,227,312,311.94
rbcL_708F3_R3-1,262.94,227,312,311.94

In [4]:
divergence2 = tandres.compute_genetic_divergence_per_taxon(save_results=True)

In [42]:
len(divergence2[divergence2['rbcL_708F3_R3_1'] > 2.0])

38

In [2]:
divergence = tandres.get_divergence_score()
divergence

                 primer  total_taxa  n_taxa_above_cutoff  divergence_score
0  rbcL_708F_DEG_R3_DEG         669                   39              5.83
1        rbcL_646F_998R         669                   39              5.83
2       rbcL_708F1_R3_2         669                   39              5.83
3       rbcL_708F2_R3_2         669                   39              5.83
4       rbcL_708F3_R3_2         669                   38              5.68
5       rbcL_708F2_R3_1         669                   39              5.83
6       rbcL_708F1_R3_1         669                   39              5.83
7       rbcL_708F3_R3_1         669                   38              5.68

In [77]:
abc = nuc_mat[(~nuc_mat['rbcL_646F_998R'].isnull()) & (nuc_mat['genus'] == 'Achnanthes')]
abc

,input_taxa,family,genus,species,rank,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F2_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Achnanthes Bory 1822,Achnanthaceae,Achnanthes,NaN,genus,0,1,0,0,23,0,0,23
55,Achnanthidium minutissimum Kutzing Czarnecki 1994,Achnanthaceae,Achnanthes,Achnanthidium minutissimum,species,0,0,0,0,0,0,0,0

In [78]:
# Transform columns that are not 'input_taxa', family', genus', 'species', 'rank' to numeric
str_columns = ['input_taxa', 'family', 'genus', 'species', 'rank']
numeric_columns = [col for col in nuc_mat.columns if col not in str_columns]
nuc_mat[numeric_columns] = nuc_mat[numeric_columns].apply(pd.to_numeric, errors='coerce')
nuc_mat.dtypes

input_taxa               object
family                   object
genus                    object
species                  object
rank                     object
rbcL_708F_DEG_R3_DEG    float64
rbcL_646F_998R          float64
rbcL_708F1_R3_2         float64
rbcL_708F2_R3_2         float64
rbcL_708F3_R3_2         float64
rbcL_708F2_R3_1         float64
rbcL_708F1_R3_1         float64
rbcL_708F3_R3_1         float64
dtype: object

In [79]:
abc2 = nuc_mat[(~nuc_mat['rbcL_646F_998R'].isnull()) & (nuc_mat['genus'] == 'Achnanthes')]
abc2

,input_taxa,family,genus,species,rank,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F2_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Achnanthes Bory 1822,Achnanthaceae,Achnanthes,NaN,genus,0.0,1.0,0.0,0.0,23.0,0.0,0.0,23.0
55,Achnanthidium minutissimum Kutzing Czarnecki 1994,Achnanthaceae,Achnanthes,Achnanthidium minutissimum,species,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
result = fill_hierarchical_values(abc2, 'min')
result

,input_taxa,family,genus,species,rank,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F2_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Achnanthes Bory 1822,Achnanthaceae,Achnanthes,NaN,genus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,Achnanthidium minutissimum Kutzing Czarnecki 1994,Achnanthaceae,Achnanthes,Achnanthidium minutissimum,species,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
tandres.compute_genetic_divergence_per_taxon()

,input_taxa,family,genus,species,rank,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F2_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Achnanthes Bory 1822,Achnanthaceae,Achnanthes,NaN,genus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Achnanthes biasolettiana var. biasolettiana,Achnanthaceae,Achnanthes,Achnanthes biasolettiana,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Achnanthes biasolettiana Grunow 1880,Achnanthaceae,Achnanthes,Achnanthes biasolettiana,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Achnanthes bioretii Germain 1957,Achnanthaceae,Achnanthes,Achnanthes bioretii,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Achnanthes chlidanos M.H.Hohn Hellerman 1963,Achnanthaceae,Achnanthes,Achnanthes chlidanos,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,Tryblionella levidensis W.Smith 1856,Bacillariaceae,Tryblionella,Tryblionella levidensis,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,Ulnaria biceps Kutzing P.Compere 2001,Fragilariaceae,Synedra,Ulnaria biceps,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,Ulnaria delicatissima W.Smith M.Aboal P.C.Sil...,Fragilariaceae,Synedra,Ulnaria delicatissima,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,Ulnaria ulna Nitzsch P.Compere 2001,Fragilariaceae,Synedra,Ulnaria ulna,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,Ulnaria ulna var. acus Kutz. Lange-Bert.,Fragilariaceae,Synedra,Ulnaria ulna,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
hyal = nuc_mat.loc[1]
hyal.items()

<zip object at 0x78be3ddd58c0>

In [8]:
nuc_mat_species = nuc_mat['Species']
nuc_mat_species.to_csv("nuc_mat_species.csv")

In [1]:
import pandas as pd
test_multibarcode_600k = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/bmi_600k_multibarcodetest.tsv", sep="\t", header=None)
new_column_names = ['seq_id', 'primer', 'scientific_name', 'kingdom', 'phylum', 'class', 'order', 'family','seq']
test_multibarcode_600k.columns = new_column_names[:len(test_multibarcode_600k.columns)]
test_multibarcode_600k

,seq_id,primer,scientific_name,kingdom,phylum,class,order,family,seq
0,AAGRE003-21,COI_mICOIintF_jgHCO2198,Atylotus agrestis Wiedemann 1828,Animalia,Arthropoda,Insecta,Diptera,Tabanidae,CCTATCTGCTGCAATTGCCCATGGAGGAGGTTCTGTTGATTTAGCA...
1,ABEE097-17,COI_mICOIintF_jgHCO2198,Andrena pilipes Fabricius 1781,Animalia,Arthropoda,Insecta,Hymenoptera,Andrenidae,ATTATCATCATATTCTTATCACCCATCTTCCTCAACAGACCTAACA...
2,ABEE104-17,COI_mICOIintF_jgHCO2198,Halictus quadricinctus Fabricius 1776,Animalia,Arthropoda,Insecta,Hymenoptera,Halictidae,TCTATCATCAATTATATTTCATGCATCTTTCTCTGTTGATTTTTCT...
3,ABEE111-17,COI_mICOIintF_jgHCO2198,Hylaeus sinuatus Schenck 1853,Animalia,Arthropoda,Insecta,Hymenoptera,Colletidae,CTTATCATCCATAATATATCATCCATCATTATCAGTTGATTTAACA...
4,ABEE126-17,COI_mICOIintF_jgHCO2198,Hylaeus cornutus Curtis 1831,Animalia,Arthropoda,Insecta,Hymenoptera,Colletidae,ATTATCATCAATAATATACCATCCATCATTATCAGTAGATTTTACA...
...,...,...,...,...,...,...,...,...,...
3703062,CNLMB365-14,COI_FwhF2_FwhR2n,Typhlodromus Scheuten,Animalia,Arthropoda,Arachnida,Mesostigmata,Phytoseiidae,TCTTTCTAATAGAATTTTCCATAATGGAATTTCAGTTGATCTGGCT...
3703063,SSFDC473-14,COI_FwhF2_FwhR2n,Arctoseius Thor 1930,Animalia,Arthropoda,Arachnida,Mesostigmata,Ascidae,TTTAGCAAGAAATATTGCGCATAGAGGCAGCTCTGTTGATCTAGCA...
3703064,GMARC348-14,COI_FwhF2_FwhR2n,Cecidomyiidae,Animalia,Arthropoda,Insecta,Diptera,Cecidomyiidae,GCTATCATCAGTTATTGCACATACAGGATCAGCTGTAGATTTTTCA...
3703065,GMMDC239-15,COI_FwhF2_FwhR2n,Sciaridae,Animalia,Arthropoda,Insecta,Diptera,Sciaridae,ATTATCTTCTACTTTATCTCACTCAGGAGCCTCTGTTGATTTATCT...
3703066,GMAAC1239-16,COI_FwhF2_FwhR2n,Cecidomyiidae,Animalia,Arthropoda,Insecta,Diptera,Cecidomyiidae,TTTATCATCAATTATATTTCATTCAAGAACTTCAGTCGATTTATCT...

In [12]:
unique_families = test_multibarcode_600k.groupby('family').size()
unique_families.sort_values(ascending=False)

family
Cecidomyiidae         388069
Chironomidae          322583
Ceratopogonidae       154400
Sciaridae             134253
Staphylinidae         100794
                       ...
Plateremaeidae             1
Metopidiotrichidae         1
Oceaniidae                 1
Paramunnidae               1
Ostreidae                  1
Length: 2173, dtype: int64

In [13]:
unique_primers = test_multibarcode_600k.groupby('primer').size()
unique_primers.sort_values(ascending=False)

primer
COI_FwhF2_FwhR2n             608953
COI_BF3_BR2                  499717
COI_BF2_BR2                  499685
COI_fwhF2_Fol-degen-rev      493378
COI_mICOIintF_jgHCO2198      493018
COI_MICOIntF_HCO2198         492193
COI_FwhF2_EPTDr2n            382116
COI_MG2-LCO1490_MG2-univR    234007
dtype: int64

### Checking largest primer

In [14]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
largest_primer = largest_primer[['seq_id', 'primer', 'scientific_name', 'seq']]
largest_primer
# largest_primer.to_csv("fwh.tsv", sep="\t", index=False)

,seq_id,primer,scientific_name,seq
406832,AASFB602-10,COI_FwhF2_FwhR2n,Ctenidae,TTTAGCTTCTAGAGTAGGTCATATAGGAAGATCAATGGATTTTGCT...
406833,AASFB633-10,COI_FwhF2_FwhR2n,Clubionidae,TTTAGCTTCTGGCGTGGGACATTCTGGTAGTGCTATGGATTTTGCT...
406834,AASFB645-10,COI_FwhF2_FwhR2n,Anyphaenidae,TTTATCTTCAAGAGTTGGTCATATAGGAAGAGCTATAGATTTTGCT...
406835,AASFB649-10,COI_FwhF2_FwhR2n,Corinnidae,TTTAGCATCAACTATAGGGCACACAGGAAGAGCTGTTGATTTTGCG...
406836,AASFB654-10,COI_FwhF2_FwhR2n,Salticidae,TTTAGCTTCAATTGTTGGGCATAATGGAAGTTCTGTTGATTTTGCA...
...,...,...,...,...
3703062,CNLMB365-14,COI_FwhF2_FwhR2n,Typhlodromus Scheuten,TCTTTCTAATAGAATTTTCCATAATGGAATTTCAGTTGATCTGGCT...
3703063,SSFDC473-14,COI_FwhF2_FwhR2n,Arctoseius Thor 1930,TTTAGCAAGAAATATTGCGCATAGAGGCAGCTCTGTTGATCTAGCA...
3703064,GMARC348-14,COI_FwhF2_FwhR2n,Cecidomyiidae,GCTATCATCAGTTATTGCACATACAGGATCAGCTGTAGATTTTTCA...
3703065,GMMDC239-15,COI_FwhF2_FwhR2n,Sciaridae,ATTATCTTCTACTTTATCTCACTCAGGAGCCTCTGTTGATTTATCT...
3703066,GMAAC1239-16,COI_FwhF2_FwhR2n,Cecidomyiidae,TTTATCATCAATTATATTTCATTCAAGAACTTCAGTCGATTTATCT...

#### By family

In [16]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
unique_fam_prim = largest_primer.groupby('family').size()
unique_fam_prim.sort_values(ascending=False)

family
Cecidomyiidae      66356
Chironomidae       46389
Ceratopogonidae    23311
Sciaridae          21998
Staphylinidae      16090
                   ...
Viridasiidae           1
Virgulariidae          1
Aegidae                1
Adelphacaridae         1
Acteonidae             1
Length: 2137, dtype: int64

In [72]:
primer_subset = test_multibarcode_600k[test_multibarcode_600k[1] == 'COI_FwhF2_FwhR2n']
test_subset = primer_subset[test_multibarcode_600k[7] == 'Cecidomyiidae']
test_subset = test_subset[[0, 1, 2, 8]]
test_subset
test_subset.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/filtered/multibarcode/cecidomyiidae_fwh.tsv", sep='\t', index=False)

/tmp/ipykernel_107298/2624939451.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_subset = primer_subset[test_multibarcode_600k[7] == 'Cecidomyiidae']

#### By order

In [15]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
unique_fam_prim = largest_primer.groupby('order').size()
unique_fam_prim.sort_values(ascending=False)

order
Diptera           260984
Hymenoptera        82758
Coleoptera         81625
Lepidoptera        62315
Hemiptera          32882
                   ...
Solemyida              1
Tethyida               1
Sphacelariales         1
Verongiida             1
Zoraptera              1
Length: 209, dtype: int64

In [ ]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
largest_prim_order =  largest_primer[largest_primer['order'] == 'Diptera']
largest_prim_order = largest_prim_order[['seq_id', 'primer', 'scientific_name', 'seq', ]]
largest_prim_order

,seq_id,primer,scientific_name,seq
406989,AAASF032-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406990,AAASF015-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406991,AAASF019-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406992,AAASF029-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406993,AAASF007-17,COI_FwhF2_FwhR2n,Lutzomyia longipalpis Lutz Neiva 1912,TTTATCTAGAAATATTGCCCATAGAGGAGCTTCAGTTGATTTAGCA...
...,...,...,...,...
3703057,CNTIG1958-15,COI_FwhF2_FwhR2n,Paramyia rectiloba Levesque-Beaudin Mlynarek ...,TTTATCTTCTATTATTGCTCATGGAAATGCTTCTGTAGATTTAGCA...
3703058,JICCD1347-16,COI_FwhF2_FwhR2n,Simulium tarsatum Macquart 1846,TCTTTCTTCGGGTATTGCTCATGCTGGAGCCTCAGTTGATTTAGCA...
3703064,GMARC348-14,COI_FwhF2_FwhR2n,Cecidomyiidae,GCTATCATCAGTTATTGCACATACAGGATCAGCTGTAGATTTTTCA...
3703065,GMMDC239-15,COI_FwhF2_FwhR2n,Sciaridae,ATTATCTTCTACTTTATCTCACTCAGGAGCCTCTGTTGATTTATCT...
3703066,GMAAC1239-16,COI_FwhF2_FwhR2n,Cecidomyiidae,TTTATCATCAATTATATTTCATTCAAGAACTTCAGTCGATTTATCT...

In [22]:
largest_prim_order.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/mb-order-diptera/diptera-fwh.tsv", sep='\t', index=False, header=None)

In [26]:
with open("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/filtered/multibarcode/fwh_diptera.fasta", "w") as fasta_file:
    for _, row in largest_prim_order.iterrows():
        fasta_file.write(f">{row['seq_id']}|{row['scientific_name']}\n{row['seq']}\n")

##### Order, clustered

In [25]:
diptera_clustered = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/mb-order-diptera/diptera_clustered.csv", sep=",")
diptera_clustered

,processid,bin_uri,scientificName,rank,kingdom,phylum,class,order,family,genus,species,identification_method,category,marker_code,nuc,nuc_basecount
0,ABWYT30619-24,NaN,Chloropidae,family,Animalia,Arthropoda,Insecta,Diptera,Chloropidae,-,NaN,Image based identification,Morphotaxonomy,COI-5P,TACTTTATATTTTATTTTTGGAGCTTGATCTGGAATAGTAGGAACA...,658.0
1,ABWYT30952-24,BOLD:AFZ5207,Cecidomyiidae,family,Animalia,Arthropoda,Insecta,Diptera,Cecidomyiidae,-,NaN,Image based identification,Morphotaxonomy,COI-5P,TACTCTTTACTTTATTTTCGGTATTTGATCCGGAATAGTAGGAACT...,658.0
2,AGIMP024-13,NaN,"Bactrocera zonata (Saunders, 1842)",species,Animalia,Arthropoda,Insecta,Diptera,Tephritidae,Bactrocera,Bactrocera zonata,Adult,Morphotaxonomy,COI-5P,GGAACCTTATATTTTATTTTCGGGGCCTGAGCAGGAATAGTTGGGA...,640.0
3,AMCAS887-21,NaN,Sciaridae,family,Animalia,Arthropoda,Insecta,Diptera,Sciaridae,-,NaN,Image based identification,Morphotaxonomy,COI-5P,TTTATATTTTATTTTAGGAGCTTGAGCTGGAATAATTGGTACTTCA...,655.0
4,ANDIV1946-23,BOLD:AAA7374,Syrphidae,family,Animalia,Arthropoda,Insecta,Diptera,Syrphidae,-,NaN,Morphology,Morphotaxonomy,COI-5P,CATTATATTTTCTATTTGGAGCTTGAGCTGGAATAGTAGGAACTTC...,654.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16055,ZURQU025-13,BOLD:ACN7884,"Culicoides metagonatus Wirth & Blanton, 1956",species,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,Culicoides,Culicoides metagonatus,Morphology,Morphotaxonomy,COI-5P,AACCTTATATTTTATTTTTGGTATTTGATCAGGGATAATCGGAACT...,602.0
16056,ZURQU034-13,BOLD:ACN8093,"Culicoides elutus Macfie, 1948",species,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,Culicoides,Culicoides elutus,Morphology,Morphotaxonomy,COI-5P,AACATTATACTTTATTTTTGGGGCATGAGCTGGAATAGTAGGAACT...,658.0
16057,ZURQU038-13,BOLD:ACN8308,"Culicoides scopus Root & Hoffman, 1937",species,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,Culicoides,Culicoides scopus,Morphology,Morphotaxonomy,COI-5P,AACCCTTTATTTTATTTTTGGTGCTTGAGCTGGAATAGTGGGGACA...,658.0
16058,ZURQU081-13,BOLD:ACN8093,"Culicoides elutus Macfie, 1948",species,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,Culicoides,Culicoides elutus,Morphology,Morphotaxonomy,COI-5P,AACACTATACTTTATTTTTGGGGCATGAGCTGGAATAGTAGGAACT...,658.0
16059,ZURQU082-13,BOLD:ACN8308,"Culicoides scopus Root & Hoffman, 1937",species,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,Culicoides,Culicoides scopus,Morphology,Morphotaxonomy,COI-5P,AACCCTTTATTTTATTTTTGGTGCTTGAGCTGGAATAGTGGGCACA...,658.0

#### Checking one-seq distribution per family

In [ ]:
def check_unique_families(test_multibarcode_600k, primer_list):
    for primer in primer_list:
        primer_df = test_multibarcode_600k[test_multibarcode_600k['primer'] == primer]

        unique_fam_prim = primer_df.groupby('family').size()
        fams_one_seq = unique_fam_prim[unique_fam_prim < 2].index.tolist()

        filtered_check_single_orders = test_multibarcode_600k[
            (test_multibarcode_600k['primer'] == primer) &
            (test_multibarcode_600k['family'].isin(fams_one_seq))
        ]

        print(f"Number of orders with families of one sequence for primer '{primer}':", filtered_check_single_orders['order'].nunique())

        # Step 6: Iterate over unique 'order' values to check for families not in the selected list
        for order_of_uniq_families in filtered_check_single_orders['order'].unique():
            order_rows = primer_df[primer_df['order'] == order_of_uniq_families]
            families_not_in_list = order_rows[~order_rows['family'].isin(fams_one_seq)]

            if not families_not_in_list.empty:
                print(f"    Order '{order_of_uniq_families}' has entries in 'family' that have more than one sequence.")

primer_list = [
    'COI_BF2_BR2',
    'COI_BF3_BR2',
    'COI_FwhF2_EPTDr2n',
    'COI_FwhF2_FwhR2n',
    'COI_MG2-LCO1490_MG2-univR',
    'COI_MICOIntF_HCO2198',
    'COI_fwhF2_Fol-degen-rev',
    'COI_mICOIintF_jgHCO2198'
]

check_unique_families(test_multibarcode_600k, primer_list)

Number of orders with families of one sequence for primer 'COI_BF2_BR2': 103
    Order 'Littorinimorpha' has entries in 'family' that have more than one sequence.
    Order 'Arhynchobdellida' has entries in 'family' that have more than one sequence.
    Order 'Scleractinia' has entries in 'family' that have more than one sequence.
    Order 'Zoantharia' has entries in 'family' that have more than one sequence.
    Order 'Cheilostomatida' has entries in 'family' that have more than one sequence.
    Order 'Stylommatophora' has entries in 'family' that have more than one sequence.
    Order 'Harpacticoida' has entries in 'family' that have more than one sequence.
    Order 'Octopoda' has entries in 'family' that have more than one sequence.
    Order 'Anostraca' has entries in 'family' that have more than one sequence.
    Order 'Poecilosclerida' has entries in 'family' that have more than one sequence.
    Order 'Lepidoptera' has entries in 'family' that have more than one sequence.
    Order 'Scleralcyonacea' has entries in 'family' that have more than one sequence.
    Order 'Antipatharia' has entries in 'family' that have more than one sequence.
    Order 'Nudibranchia' has entries in 'family' that have more than one sequence.
    Order 'Sarcoptiformes' has entries in 'family' that have more than one sequence.
    Order 'Diptera' has entries in 'family' that have more than one sequence.
    Order 'Cephalaspidea' has entries in 'family' that have more than one sequence.
    Order 'Thysanoptera' has entries in 'family' that have more than one sequence.
    Order 'Isopoda' has entries in 'family' that have more than one sequence.
    Order 'Hymenoptera' has entries in 'family' that have more than one sequence.
    Order 'Decapoda' has entries in 'family' that have more than one sequence.
    Order 'Trochida' has entries in 'family' that have more than one sequence.
    Order 'Heteronemertea' has entries in 'family' that have more than one sequence.
    Order 'Calanoida' has entries in 'family' that have more than one sequence.
    Order 'Malacalcyonacea' has entries in 'family' that have more than one sequence.
    Order 'Rhabditida' has entries in 'family' that have more than one sequence.
    Order 'Poduromorpha' has entries in 'family' that have more than one sequence.
    Order 'Siphonaptera' has entries in 'family' that have more than one sequence.
    Order 'Pleurobranchida' has entries in 'family' that have more than one sequence.
    Order 'Coleoptera' has entries in 'family' that have more than one sequence.
    Order 'Cyclopoida' has entries in 'family' that have more than one sequence.
    Order 'Solifugae' has entries in 'family' that have more than one sequence.
    Order 'Chitonida' has entries in 'family' that have more than one sequence.
    Order 'Ectocarpales' has entries in 'family' that have more than one sequence.
    Order 'Ephemeroptera' has entries in 'family' that have more than one sequence.
    Order 'Cyclostomatida' has entries in 'family' that have more than one sequence.
    Order 'Trombidiformes' has entries in 'family' that have more than one sequence.
    Order 'Amphipoda' has entries in 'family' that have more than one sequence.
    Order 'Araneae' has entries in 'family' that have more than one sequence.
    Order 'Diplostraca' has entries in 'family' that have more than one sequence.
    Order 'Clionaida' has entries in 'family' that have more than one sequence.
    Order 'Pteropoda' has entries in 'family' that have more than one sequence.
    Order 'Hemiptera' has entries in 'family' that have more than one sequence.
    Order 'Pantopoda' has entries in 'family' that have more than one sequence.
    Order 'Pseudoscorpiones' has entries in 'family' that have more than one sequence.
    Order 'Mesostigmata' has entries in 'family' that have more than one sequence.
    Order 'Laminariales' has entries in 'family' that have more than one sequence.
    Order 'Branchiobdellida' has entries in 'family' that have more than one sequence.
    Order 'Odonata' has entries in 'family' that have more than one sequence.
    Order 'Rhodymeniales' has entries in 'family' that have more than one sequence.
    Order 'Neogastropoda' has entries in 'family' that have more than one sequence.
    Order 'Sabellida' has entries in 'family' that have more than one sequence.
    Order 'Cycloneritida' has entries in 'family' that have more than one sequence.
    Order 'Embioptera' has entries in 'family' that have more than one sequence.
    Order 'Anthoathecata' has entries in 'family' that have more than one sequence.
    Order 'Opiliones' has entries in 'family' that have more than one sequence.
    Order 'Mantodea' has entries in 'family' that have more than one sequence.
    Order 'Ceramiales' has entries in 'family' that have more than one sequence.
    Order 'Haplosclerida' has entries in 'family' that have more than one sequence.
    Order 'Spirobolida' has entries in 'family' that have more than one sequence.
    Order 'Blattodea' has entries in 'family' that have more than one sequence.
    Order 'Oegopsida' has entries in 'family' that have more than one sequence.
    Order 'Siphonophorae' has entries in 'family' that have more than one sequence.
    Order 'Leptothecata' has entries in 'family' that have more than one sequence.
    Order 'Mecoptera' has entries in 'family' that have more than one sequence.
    Order 'Nemaliales' has entries in 'family' that have more than one sequence.
    Order 'Neuroptera' has entries in 'family' that have more than one sequence.
    Order 'Bubarida' has entries in 'family' that have more than one sequence.
    Order 'Phyllodocida' has entries in 'family' that have more than one sequence.
    Order 'Suberitida' has entries in 'family' that have more than one sequence.
    Order 'Trichoptera' has entries in 'family' that have more than one sequence.
    Order 'Plumatellida' has entries in 'family' that have more than one sequence.
    Order 'Gelidiales' has entries in 'family' that have more than one sequence.
    Order 'Podocopida' has entries in 'family' that have more than one sequence.
    Order 'Psocodea' has entries in 'family' that have more than one sequence.
    Order 'Solitaria' has entries in 'family' that have more than one sequence.
    Order 'Parachela' has entries in 'family' that have more than one sequence.
    Order 'Gigartinales' has entries in 'family' that have more than one sequence.
    Order 'Spongillida' has entries in 'family' that have more than one sequence.
Number of orders with families of one sequence for primer 'COI_BF3_BR2': 104
    Order 'Littorinimorpha' has entries in 'family' that have more than one sequence.
    Order 'Arhynchobdellida' has entries in 'family' that have more than one sequence.
    Order 'Scleractinia' has entries in 'family' that have more than one sequence.
    Order 'Zoantharia' has entries in 'family' that have more than one sequence.
    Order 'Cheilostomatida' has entries in 'family' that have more than one sequence.
    Order 'Stylommatophora' has entries in 'family' that have more than one sequence.
    Order 'Harpacticoida' has entries in 'family' that have more than one sequence.
    Order 'Octopoda' has entries in 'family' that have more than one sequence.
    Order 'Decapoda' has entries in 'family' that have more than one sequence.
    Order 'Cumacea' has entries in 'family' that have more than one sequence.
    Order 'Araneae' has entries in 'family' that have more than one sequence.
    Order 'Trombidiformes' has entries in 'family' that have more than one sequence.
    Order 'Anostraca' has entries in 'family' that have more than one sequence.
    Order 'Calanoida' has entries in 'family' that have more than one sequence.
    Order 'Trichoptera' has entries in 'family' that have more than one sequence.
    Order 'Lepidoptera' has entries in 'family' that have more than one sequence.
    Order 'Nudibranchia' has entries in 'family' that have more than one sequence.
    Order 'Coleoptera' has entries in 'family' that have more than one sequence.
    Order 'Pleurobranchida' has entries in 'family' that have more than one sequence.
    Order 'Hymenoptera' has entries in 'family' that have more than one sequence.
    Order 'Mesostigmata' has entries in 'family' that have more than one sequence.
    Order 'Haplosclerida' has entries in 'family' that have more than one sequence.
    Order 'Oegopsida' has entries in 'family' that have more than one sequence.
    Order 'Pseudoscorpiones' has entries in 'family' that have more than one sequence.
    Order 'Diptera' has entries in 'family' that have more than one sequence.
    Order 'Neogastropoda' has entries in 'family' that have more than one sequence.
    Order 'Siphonophorae' has entries in 'family' that have more than one sequence.
    Order 'Amphipoda' has entries in 'family' that have more than one sequence.
    Order 'Siphonaptera' has entries in 'family' that have more than one sequence.
    Order 'Mecoptera' has entries in 'family' that have more than one sequence.
    Order 'Scleralcyonacea' has entries in 'family' that have more than one sequence.
    Order 'Ectocarpales' has entries in 'family' that have more than one sequence.
    Order 'Rhabditida' has entries in 'family' that have more than one sequence.
    Order 'Laminariales' has entries in 'family' that have more than one sequence.
    Order 'Diplostraca' has entries in 'family' that have more than one sequence.
    Order 'Solitaria' has entries in 'family' that have more than one sequence.
    Order 'Sarcoptiformes' has entries in 'family' that have more than one sequence.
    Order 'Clionaida' has entries in 'family' that have more than one sequence.
    Order 'Gelidiales' has entries in 'family' that have more than one sequence.
    Order 'Parachela' has entries in 'family' that have more than one sequence.
    Order 'Sabellida' has entries in 'family' that have more than one sequence.
    Order 'Ephemeroptera' has entries in 'family' that have more than one sequence.
    Order 'Poecilosclerida' has entries in 'family' that have more than one sequence.
    Order 'Heteronemertea' has entries in 'family' that have more than one sequence.
    Order 'Hemiptera' has entries in 'family' that have more than one sequence.
    Order 'Pantopoda' has entries in 'family' that have more than one sequence.
    Order 'Phyllodocida' has entries in 'family' that have more than one sequence.
    Order 'Malacalcyonacea' has entries in 'family' that have more than one sequence.
    Order 'Cephalaspidea' has entries in 'family' that have more than one sequence.
    Order 'Neuroptera' has entries in 'family' that have more than one sequence.
    Order 'Opiliones' has entries in 'family' that have more than one sequence.
    Order 'Bubarida' has entries in 'family' that have more than one sequence.
    Order 'Antipatharia' has entries in 'family' that have more than one sequence.
    Order 'Rhodymeniales' has entries in 'family' that have more than one sequence.
    Order 'Embioptera' has entries in 'family' that have more than one sequence.
    Order 'Suberitida' has entries in 'family' that have more than one sequence.
    Order 'Gigartinales' has entries in 'family' that have more than one sequence.
    Order 'Pteropoda' has entries in 'family' that have more than one sequence.
    Order 'Cyclostomatida' has entries in 'family' that have more than one sequence.
    Order 'Solifugae' has entries in 'family' that have more than one sequence.
    Order 'Mantodea' has entries in 'family' that have more than one sequence.
    Order 'Cycloneritida' has entries in 'family' that have more than one sequence.
    Order 'Nemaliales' has entries in 'family' that have more than one sequence.
    Order 'Leptothecata' has entries in 'family' that have more than one sequence.
    Order 'Branchiobdellida' has entries in 'family' that have more than one sequence.
    Order 'Psocodea' has entries in 'family' that have more than one sequence.
    Order 'Blattodea' has entries in 'family' that have more than one sequence.
    Order 'Plumatellida' has entries in 'family' that have more than one sequence.
    Order 'Trochida' has entries in 'family' that have more than one sequence.
    Order 'Isopoda' has entries in 'family' that have more than one sequence.
    Order 'Ceramiales' has entries in 'family' that have more than one sequence.
    Order 'Thysanoptera' has entries in 'family' that have more than one sequence.
    Order 'Odonata' has entries in 'family' that have more than one sequence.
    Order 'Anthoathecata' has entries in 'family' that have more than one sequence.
    Order 'Podocopida' has entries in 'family' that have more than one sequence.
    Order 'Poduromorpha' has entries in 'family' that have more than one sequence.
    Order 'Cyclopoida' has entries in 'family' that have more than one sequence.
    Order 'Spongillida' has entries in 'family' that have more than one sequence.
    Order 'Chitonida' has entries in 'family' that have more than one sequence.
    Order 'Spirobolida' has entries in 'family' that have more than one sequence.
Number of orders with families of one sequence for primer 'COI_FwhF2_EPTDr2n': 77
    Order 'Sarcoptiformes' has entries in 'family' that have more than one sequence.
    Order 'Siphonaptera' has entries in 'family' that have more than one sequence.
    Order 'Solitaria' has entries in 'family' that have more than one sequence.
    Order 'Trombidiformes' has entries in 'family' that have more than one sequence.
    Order 'Amphipoda' has entries in 'family' that have more than one sequence.
    Order 'Dictyosiphonales' has entries in 'family' that have more than one sequence.
    Order 'Gigartinales' has entries in 'family' that have more than one sequence.
    Order 'Ceramiales' has entries in 'family' that have more than one sequence.
    Order 'Neogastropoda' has entries in 'family' that have more than one sequence.
    Order 'Littorinimorpha' has entries in 'family' that have more than one sequence.
    Order 'Araneae' has entries in 'family' that have more than one sequence.
    Order 'Nudibranchia' has entries in 'family' that have more than one sequence.
    Order 'Neuroptera' has entries in 'family' that have more than one sequence.
    Order 'Odonata' has entries in 'family' that have more than one sequence.
    Order 'Pseudoscorpiones' has entries in 'family' that have more than one sequence.
    Order 'Gelidiales' has entries in 'family' that have more than one sequence.
    Order 'Fucales' has entries in 'family' that have more than one sequence.
    Order 'Poecilosclerida' has entries in 'family' that have more than one sequence.
    Order 'Coleoptera' has entries in 'family' that have more than one sequence.
    Order 'Symphypleona' has entries in 'family' that have more than one sequence.
    Order 'Ixodida' has entries in 'family' that have more than one sequence.
    Order 'Decapoda' has entries in 'family' that have more than one sequence.
    Order 'Isopoda' has entries in 'family' that have more than one sequence.
    Order 'Actiniaria' has entries in 'family' that have more than one sequence.
    Order 'Octopoda' has entries in 'family' that have more than one sequence.
    Order 'Clionaida' has entries in 'family' that have more than one sequence.
    Order 'Harpacticoida' has entries in 'family' that have more than one sequence.
    Order 'Cheilostomatida' has entries in 'family' that have more than one sequence.
    Order 'Oegopsida' has entries in 'family' that have more than one sequence.
    Order 'Phyllodocida' has entries in 'family' that have more than one sequence.
    Order 'Hemiptera' has entries in 'family' that have more than one sequence.
    Order 'Diplostraca' has entries in 'family' that have more than one sequence.
    Order 'Orthoptera' has entries in 'family' that have more than one sequence.
    Order 'Diptera' has entries in 'family' that have more than one sequence.
    Order 'Leptothecata' has entries in 'family' that have more than one sequence.
    Order 'Anostraca' has entries in 'family' that have more than one sequence.
    Order 'Polydesmida' has entries in 'family' that have more than one sequence.
    Order 'Arhynchobdellida' has entries in 'family' that have more than one sequence.
    Order 'Hymenoptera' has entries in 'family' that have more than one sequence.
    Order 'Mesostigmata' has entries in 'family' that have more than one sequence.
    Order 'Mantodea' has entries in 'family' that have more than one sequence.
    Order 'Solifugae' has entries in 'family' that have more than one sequence.
    Order 'Siphonophorae' has entries in 'family' that have more than one sequence.
    Order 'Anthoathecata' has entries in 'family' that have more than one sequence.
    Order 'Lepidoptera' has entries in 'family' that have more than one sequence.
    Order 'Trichoptera' has entries in 'family' that have more than one sequence.
    Order 'Stylommatophora' has entries in 'family' that have more than one sequence.
    Order 'Rhodymeniales' has entries in 'family' that have more than one sequence.
    Order 'Ephemeroptera' has entries in 'family' that have more than one sequence.
    Order 'Spongillida' has entries in 'family' that have more than one sequence.
    Order 'Pantopoda' has entries in 'family' that have more than one sequence.
    Order 'Opiliones' has entries in 'family' that have more than one sequence.
    Order 'Haplosclerida' has entries in 'family' that have more than one sequence.
    Order 'Thysanoptera' has entries in 'family' that have more than one sequence.
    Order 'Psocodea' has entries in 'family' that have more than one sequence.
    Order 'Scleractinia' has entries in 'family' that have more than one sequence.
    Order 'Sessilia' has entries in 'family' that have more than one sequence.
    Order 'Tubificida' has entries in 'family' that have more than one sequence.
    Order 'Cyclopoida' has entries in 'family' that have more than one sequence.
Number of orders with families of one sequence for primer 'COI_FwhF2_FwhR2n': 96
    Order 'Siphonaptera' has entries in 'family' that have more than one sequence.
    Order 'Solitaria' has entries in 'family' that have more than one sequence.
    Order 'Trombidiformes' has entries in 'family' that have more than one sequence.
    Order 'Amphipoda' has entries in 'family' that have more than one sequence.
    Order 'Dictyosiphonales' has entries in 'family' that have more than one sequence.
    Order 'Laminariales' has entries in 'family' that have more than one sequence.
    Order 'Ostreida' has entries in 'family' that have more than one sequence.
    Order 'Neogastropoda' has entries in 'family' that have more than one sequence.
    Order 'Actiniaria' has entries in 'family' that have more than one sequence.
    Order 'Monostilifera' has entries in 'family' that have more than one sequence.
    Order 'Plumatellida' has entries in 'family' that have more than one sequence.
    Order 'Araneae' has entries in 'family' that have more than one sequence.
    Order 'Trochida' has entries in 'family' that have more than one sequence.
    Order 'Neuroptera' has entries in 'family' that have more than one sequence.
    Order 'Odonata' has entries in 'family' that have more than one sequence.
    Order 'Pseudoscorpiones' has entries in 'family' that have more than one sequence.
    Order 'Gelidiales' has entries in 'family' that have more than one sequence.
    Order 'Poecilosclerida' has entries in 'family' that have more than one sequence.
    Order 'Coleoptera' has entries in 'family' that have more than one sequence.
    Order 'Cyclostomatida' has entries in 'family' that have more than one sequence.
    Order 'Scleralcyonacea' has entries in 'family' that have more than one sequence.

In [139]:
fams_one_seq = unique_fam_prim[unique_fam_prim < 2].index.tolist()
print(fams_one_seq)

['Aberrantidae', 'Acartophthalmidae', 'Achatinidae', 'Acroporidae', 'Acropsopilionidae', 'Acteonidae', 'Adelphacaridae', 'Aegidae', 'Ahnfeltiaceae', 'Aididae', 'Alariaceae', 'Alcyoniidae', 'Alvinocarididae', 'Ammoplanidae', 'Anaplectidae', 'Anomiidae', 'Apolemiidae', 'Aporrhaidae', 'Archaeidae', 'Arcticidae', 'Arietellidae', 'Ariolimacidae', 'Arkyidae', 'Artheneidae', 'Atollidae', 'Atriplectididae', 'Atypidae', 'Australimyzidae', 'Austrochilidae', 'Barbarochthonidae', 'Barentsiidae', 'Bathyphelliidae', 'Belidae', 'Biantidae', 'Boettgerillidae', 'Bothriembryontidae', 'Branchipodidae', 'Bryocryptellidae', 'Bullidae', 'Burnupiidae', 'Busyconidae', 'Caddidae', 'Cadlinellidae', 'Caeculidae', 'Callistoplacidae', 'Callithamniaceae', 'Calocidae', 'Calophyidae', 'Camerobiidae', 'Canthyloscelidae', 'Cephidae', 'Cercomegistidae', 'Cerianthidae', 'Cerithiopsidae', 'Cheiridiidae', 'Chlorocyphidae', 'Chronidae', 'Chrysolampidae', 'Cladorhizidae', 'Clausophyidae', 'Clinostomidae', 'Conicostomatidae', 'Coptopterygidae', 'Corambidae', 'Crellidae', 'Crossotonotidae', 'Cryptosulidae', 'Cuthonidae', 'Cyclocaridae', 'Cyrtaucheniidae', 'Dampfiellidae', 'Dermationidae', 'Desmacellidae', 'Desmarestiaceae', 'Diaperoeciidae', 'Diaphanocephalidae', 'Dictyosiphonaceae', 'Dinidoridae', 'Diploastraeidae', 'Dogielinotidae', 'Donacidae', 'Drilidae', 'Ectocarpaceae', 'Eledonidae', 'Entypesidae', 'Epicopeiidae', 'Epicriidae', 'Eremobelbidae', 'Eriopisidae', 'Ethusidae', 'Euagridae', 'Euctenizidae', 'Euphaeidae', 'Eutrombidiidae', 'Fenestrulinidae', 'Fionidae', 'Flustrellidridae', 'Galaxauraceae', 'Garypinidae', 'Geryoniidae', 'Glaphyridae', 'Glyphocrangonidae', 'Gonyleptidae', 'Gorgonorhynchidae', 'Granulinidae', 'Grylloblattidae', 'Heroidae', 'Heterocheilidae', 'Heterogastridae', 'Heterogynidae', 'Hexapodidae', 'Homalocnemidae', 'Huttoninidae', 'Hyblaeidae', 'Hydrachnidae', 'Hymenolepididae', 'Hyperiopsidae', 'Ianthellidae', 'Ibaliidae', 'Ischnopsyllidae', 'Isostictidae', 'Ithonidae', 'Karschiidae', 'Lacernidae', 'Lanceolidae', 'Larcidae', 'Latrunculiidae', 'Lauriidae', 'Laversiidae', 'Lepidepecreellidae', 'Lessoniaceae', 'Leucosoleniidae', 'Licneremaeidae', 'Limnadiidae', 'Linnaeoxanthidae', 'Lithoglyphidae', 'Lithophyllaceae', 'Lomanotidae', 'Lopadorrhynchidae', 'Lophocateridae', 'Lutrochidae', 'Lychnocolacidae', 'Lyctocoridae', 'Macrophthalmidae', 'Malacobdellidae', 'Margaritidae', 'Marginellidae', 'Marginidae', 'Megaluropidae', 'Melanopsidae', 'Mellinidae', 'Melphidippidae', 'Mesoplophoridae', 'Mesosignidae', 'Metaniidae', 'Micromalthidae', 'Microthoraciidae', 'Mitridae', 'Mummuciidae', 'Murmidiidae', 'Myraboliidae', 'Myriaporidae', 'Mysmenidae', 'Najnidae', 'Nebaliidae', 'Nemesiidae', 'Neolepetopsidae', 'Nephtheidae', 'Neritopsidae', 'Niphocepheidae', 'Nodocepheidae', 'Nudomideopsidae', 'Nymphomyiidae', 'Oceaniidae', 'Olindiidae', 'Oniscidae', 'Opetiidae', 'Oreogetonidae', 'Oreoleptidae', 'Orussidae', 'Ostreidae', 'Pachastrellidae', 'Pachybolidae', 'Pachychilidae', 'Pachyneuridae', 'Pantophthalmidae', 'Paramphithoidae', 'Paramunnidae', 'Paramuriceidae', 'Parthenopidae', 'Parvidrilidae', 'Peachiidae', 'Pectinatellidae', 'Pectinidae', 'Pediculariidae', 'Petrosiidae', 'Pezidae', 'Phenacolepadidae', 'Pheroliodidae', 'Phoxichilidiidae', 'Phreodrilidae', 'Phylliroidae', 'Physophoridae', 'Plateremaeidae', 'Plectreuridae', 'Pleurobranchaeidae', 'Plocamiaceae', 'Polythoridae', 'Pontoporeiidae', 'Potamididae', 'Potamonautidae', 'Praobdellidae', 'Primnoidae', 'Prostomatidae', 'Prostomidae', 'Psechridae', 'Pterocladiaceae', 'Ptilocerembiidae', 'Ramazzottiidae', 'Relicanthidae', 'Rhopalopsyllidae', 'Ricinidae', 'Rivetinidae', 'Roeslerstammiidae', 'Rossellidae', 'Samlidae', 'Scaphandridae', 'Schizogyniidae', 'Scolopendrellidae', 'Scyllaeidae', 'Segestriidae', 'Solariellidae', 'Solemyidae', 'Sphaeronectidae', 'Sphaerulariidae', 'Spinocalanidae', 'Spiralizoridae', 'Spyridiaceae', 'Stivaliidae', 'Strongylidae', 'Stypocaulaceae', 'Symplectoscyphidae', 'Telegeusidae', 'Tellinidae', 'Teloganellidae', 'Teratomyzidae', 'Tethyidae', 'Tobrilidae', 'Tomopteridae', 'Tonnidae', 'Tonzidae', 'Tornatinidae', 'Trachypachidae', 'Tricorythidae', 'Tripylidae', 'Triviidae', 'Tubuliporidae', 'Turritellidae', 'Ulmaridae', 'Umbonulidae', 'Urostylididae', 'Ustyurtiidae', 'Virgulariidae', 'Viridasiidae', 'Watersiporidae', 'Winterschmidtiidae', 'Xironodrilidae', 'Xystodesmidae', 'Zancleidae']

In [140]:
filtered_check_single_orders = test_multibarcode_600k[(test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n') & (test_multibarcode_600k['family'].isin(fams_one_seq))]
filtered_check_single_orders
#filtered_check_single_orders['order'].nunique()

,seq_id,primer,scientific_name,kingdom,phylum,class,order,family,seq
408452,ABPVM095-10,COI_FwhF2_FwhR2n,Stivaliidae,Animalia,Arthropoda,Insecta,Siphonaptera,Stivaliidae,TTTATCATCTTCTATTAGACATAGAGGAGCTTCTGTAGATTTGAGA...
409733,ADMAB183-23,COI_FwhF2_FwhR2n,Barentsia matsushimana Toriumi 1951,Animalia,Entoprocta,NaN,Solitaria,Barentsiidae,ATTGTCTTCTAATTTAGCTCATTCTGGAGGTTCTGTAGATCTTGCT...
410065,AFWM062-21,COI_FwhF2_FwhR2n,Peza Harvey 1990,Animalia,Arthropoda,Arachnida,Trombidiformes,Pezidae,TCTTTCAAATAACATTGCCCACGCCGGTAGAGCAGTTGATTTAACA...
411494,AJAKK782-17,COI_FwhF2_FwhR2n,Conicostomatidae,Animalia,Arthropoda,Malacostraca,Amphipoda,Conicostomatidae,TTTATCTGCTACTCTAGCACACAGGGGCGGTAGAGTAGACCTAGCT...
411551,AJAKK1066-17,COI_FwhF2_FwhR2n,Hyperiopsis G.O.Sars 1885,Animalia,Arthropoda,Malacostraca,Amphipoda,Hyperiopsidae,ATTAGCTGCCTCAGTAGCACATAGAGGAAGTTCCGTTGATTTAGCT...
...,...,...,...,...,...,...,...,...,...
3695347,WILLI207-17,COI_FwhF2_FwhR2n,Oreoleptis torrenticola Zloty Sinclair Pritch...,Animalia,Arthropoda,Insecta,Diptera,Oreoleptidae,CTTATCATCTAGAATTGCTCATGCAGGAGGATCTGTTGACTTAGCT...
3695497,DBMB008-20,COI_FwhF2_FwhR2n,Macrophthalmus depressus Ruppell 1830,Animalia,Arthropoda,Malacostraca,Decapoda,Macrophthalmidae,TTTAGCAGCAGCTATTGCCCATGCAGGTGCTTCAGTAGATCTAGGT...
3698434,MAODO230-11,COI_FwhF2_FwhR2n,Paracypha unimaculata Selys 1853,Animalia,Arthropoda,Insecta,Odonata,Chlorocyphidae,ATTAGCAGGAGCCATTGCCCACGCGGGGGGGTCTGTAGATTTAACA...
3699622,SCL030-22,COI_FwhF2_FwhR2n,Isopora togianensis Wallace 1997,Animalia,Cnidaria,Anthozoa,Scleractinia,Acroporidae,TCTATCGAGCATCCAGGCCCACTCTGGGGGGGCGGTAGACATGGCT...
3702461,GMMDN2883-15,COI_FwhF2_FwhR2n,Viridasiidae,Animalia,Arthropoda,Arachnida,Araneae,Viridasiidae,TTTAGCTTCTATTGTGGGGCATGGAGGGAGAGCAGTTGATTTTGCA...

In [ ]:
for order_of_uniq_families in filtered_check_single_orders['order'].unique():
    order_rows = filtered_check_single_orders[filtered_check_single_orders['order'] == order_of_uniq_families]
    families_not_in_list = order_rows[~order_rows['family'].isin(fams_one_seq)]

    if not families_not_in_list.empty:
        print(f"Order '{order_of_uniq_families}' has entries in 'family' that only have on sequence:")
        print(families_not_in_list)

In [45]:
# group by primer, family
family_primer_counts = test_multibarcode_600k.groupby([1, 7]).size().reset_index(name='count')
min_max_per_primer = family_primer_counts.groupby(1)['count'].agg(['min', 'max'])

print(min_max_per_primer)

                           min    max
1
COI_BF2_BR2                  1  59918
COI_BF3_BR2                  1  59903
COI_FwhF2_EPTDr2n            1  46000
COI_FwhF2_FwhR2n             1  66356
COI_MG2-LCO1490_MG2-univR    1  14306
COI_MICOIntF_HCO2198         1  59527
COI_fwhF2_Fol-degen-rev      1  59525
COI_mICOIintF_jgHCO2198      1  59525

In [ ]:
# Total: 3703067
import pandas as pd
file_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/external_scripts/test_order.tsv"
df = pd.read_csv(file_path, sep='\t')

def get_analysis_order_of_magnitude(df):
    levels = {
        "phylum": 4,
        "class": 5,
        "order": 6,
        "family": 7
    }

    for level, col in levels.items():
        grouped_counts = df.groupby(df.columns[col]).size()

        min_count = grouped_counts.min()
        max_count = grouped_counts.max()
        mean_count = grouped_counts.mean()

        print(f"\nStatistics for {level} level:")
        print(f"  Unique groups: {len(grouped_counts)}")
        print(f"  Min entries per file: {min_count}")
        print(f"  Max entries per file: {max_count}")

get_analysis_order_of_magnitude(df)

Statistics for phylum level:
  Unique groups: 14
  Min entries per file: 24
  Max entries per file: 3654885

Statistics for class level:
  Unique groups: 47
  Min entries per file: 2
  Max entries per file: 3408770

Statistics for order level:
  Unique groups: 214
  Min entries per file: 1
  Max entries per file: 1674953

Statistics for family level:
  Unique groups: 2173
  Min entries per file: 1
  Max entries per file: 388068

In [ ]:
import os
import pandas as pd

def filter_tsv_files(folder_path):
    # List all TSV files in the folder
    for file_name in os.listdir(folder_path):
        if file_name.endswith(".tsv"):
            file_path = os.path.join(folder_path, file_name)

            # Read the TSV file
            df = pd.read_csv(file_path, sep='\t')

            # Check if 'phylum' column exists
            if 'phylum' in df.columns:
                # Filter out unwanted phyla
                df = df[~df['phylum'].isin(['Rhodophyta', 'Chordata', 'Tracheophyta'])]

                # Save the cleaned file (overwrite or create new file)
                output_path = os.path.join(folder_path, f"filtered_{file_name}")
                df.to_csv(output_path, sep='\t', index=False)
                print(f"Processed: {file_name} -> Saved as {output_path}")
            else:
                print(f"Skipping {file_name}: No 'phylum' column found.")

# Example usage
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi"
filter_tsv_files(folder_path)

Processed: Sweden_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Sweden_taxonlist_bmi_harmonized.tsv
Processed: Austria_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Austria_taxonlist_bmi_harmonized.tsv
Processed: Poland_taxonlists_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Poland_taxonlists_bmi_harmonized.tsv
Processed: Czech_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Czech_taxonlist_bmi_harmonized.tsv
Processed: Germany_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Germany_taxonlist_bmi_harmonized.tsv
Processed: Portugal_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Portugal_taxonlist_bmi_harmonized.tsv
Processed: Finland_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Finland_taxonlist_bmi_harmonized.tsv
Processed: France_taxonlists_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_France_taxonlists_bmi_harmonized.tsv

In [2]:
from src.marker_scoring.metrics_system import ReferenceDatabaseQuality

refb = ReferenceDatabaseQuality(all_inserts_path='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat.barcode_earlier_results/insert/filtered', otl='/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv')
barcodes_per_entry = refb.calculate_number_of_barcodes_per_fasta_entry()
barcodes_per_entry
# refb.taxa_hierarchy
#refb.calculate_number_of_barcodes_per_otl_taxonomy(barcodes_per_entry, refb.taxa_hierarchy)

mozaiko INFO: Calculating the number of barcodes per FASTA.

{'rbcL_708F1_R3-1': {'Achnanthes brevipes|Achnanthes brevipes Kutzing 1833|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthes brevipes': 1,
  'Achnanthes coarctata|Achnanthes coarctata Brebisson ex W.Smith Grunow 1880|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthes coarctata': 1,
  'Achnanthes elongata|Achnanthes Bory 1822|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|nan': 7,
  'Achnanthes longboardia|Achnanthes longboardia A.R.Sherwood  R.L.Lowe 2009|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthes longboardia': 2,
  'Achnanthes longipes|Achnanthes longipes C.Agardh 1824|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthes longipes': 1,
  'Achnanthes sp. A|Achnanthes Bory 1822|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|nan': 1,
  'Achnanthes sp. B|Achnanthes Bory 1822|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|nan': 1,
  'Achnanthes sp.|Achnanthes Bory 1822|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|nan': 4,
  'Achnanthidium catenatum|Achnanthidium catenatum Bily  Marvan Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium catenatum': 2,
  'Achnanthidium chlidanos|Achnanthidium chlidanos Hohn  Hellerman E.Novelo R.Tavera  C.Ibarra 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium chlidanos': 1,
  'Achnanthidium delmontii|Achnanthidium delmontii F.Peres R.le Cohu  A.Barthes 2012|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|Achnanthidium delmontii': 6,
  'Achnanthidium digitatum|Achnanthidium digitatum Pinseel Vanormelingen Hamilton  Van de Vijver 2017|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|Achnanthidium digitatum': 4,
  'Achnanthidium eutrophilum|Achnanthidium eutrophilum Lange-Bertalot Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium eutrophilum': 9,
  'Achnanthidium jackii|Achnanthidium jackii Rabenhorst 1861|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|Achnanthidium jackii': 2,
  'Achnanthidium kranzii|Achnanthidium kranzii Lange-Bertalot Round  Bukhtiyarova 1996|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium kranzii': 1,
  'Achnanthidium lineare|Achnanthidium lineare W.Smith 1855|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|Achnanthidium lineare': 3,
  'Achnanthidium minutissimum|Achnanthidium minutissimum Kutzing Czarnecki 1994|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium minutissimum': 115,
  'Achnanthidium pyrenaicum|Achnanthidium pyrenaicum Hustedt H.Kobayasi 1997|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium pyrenaicum': 8,
  'Achnanthidium reimeri|Achnanthidium reimeri Camburn Ponader  Potapova 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium reimeri': 1,
  'Achnanthidium rivulare|Achnanthidium rivulare Potapova  Ponader 2004|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|Achnanthidium rivulare': 1,
  'Achnanthidium saprophilum|Achnanthidium saprophilum H.Kobayasi  S.Mayama Round  L.Bukhtiyarova 1996|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium saprophilum': 2,
  'Achnanthidium sp.|Achnanthidium F.T.Kutzing 1844|genus|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthidiaceae|Achnanthidium|nan': 1,
  'Achnanthidium straubianum|Achnanthidium straubianum Lange-Bertalot Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium straubianum': 1,
  'Achnanthidium subatomus|Achnanthidium subatomus Hustedt Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Achnanthales|Achnanthaceae|Achnanthes|Achnanthidium subatomus': 4,
  'Actinocyclus actinochilus|Actinocyclus actinochilus Ehrenberg Simonsen 1982|species|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Coscinodiscaceae|Coscinodiscus|Actinocyclus actinochilus': 1,
  'Actinoptychus octonarius|Actinoptychus octonarius Ehrenberg Kutzing 1844|species|Animalia|Mollusca|Gastropoda|Nudibranchia|Actinocyclidae|Actinocyclus|Actinoptychus octonarius': 2,
  'Actinoptychus sp.|Actinoptychus C.G.Ehrenberg 1843|genus|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Heliopeltaceae|Actinoptychus|nan': 6,
  'Actinoptychus splendens|Actinoptychus splendens Shadbolt Ralfs ex Pritchard 1861|species|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Heliopeltaceae|Actinoptychus|Actinoptychus splendens': 2,
  'Adlafia bryophila|Adlafia bryophila J.B.Petersen Gerd Moser Lange-Bertalot  D.Metzeltin 1998|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Adlafia|Adlafia bryophila': 1,
  'Adlafia minuscula|Adlafia minuscula Grunow Lange-Bertalot 1999|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula|Adlafia minuscula': 2,
  'Amicula sp.|Amicula J.E.Gray 1847|genus|Animalia|Mollusca|Polyplacophora|Chitonida|Mopaliidae|Amicula|nan': 2,
  'Amphitetras antediluviana|Amphitetras antediluviana Ehrenberg 1840|species|Chromista|Ochrophyta|Bacillariophyceae|Triceratiales|Triceratiaceae|Amphitetras|Amphitetras antediluviana': 1,
  'Amphora abludens|Amphora abludens Simonsen 1960|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora abludens': 2,
  'Amphora aff. atomoides|Amphora atomoides Levkov 2009|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora atomoides': 1,
  'Amphora aliformis|Amphora aliformis J.G.Stepanek S.Mayama  J.P.Kociolek 2015|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora aliformis': 2,
  'Amphora beaufortiana|Amphora beaufortiana Hustedt 1955|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora beaufortiana': 1,
  'Amphora berolinensis|Amphora berolinensis N.Abarca  R.Jahn 2014|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora berolinensis': 1,
  'Amphora calumetica|Amphora calumetica Thomas ex Wolle M.Peragallo 1897|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Amphipleuraceae|Amphiprora|Amphora calumetica': 1,
  'Amphora cf. immarginata|Amphora immarginata T.Nagumo 2003|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora immarginata': 1,
  'Amphora commutata|Amphora commutata Grunow 1880|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora commutata': 2,
  'Amphora copulata|Amphora copulata Kutzing Schoeman  R.E.M.Archibald 1986|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Amphipleuraceae|Frustulia|Amphora copulata': 3,
  'Amphora fusca|Amphora fusca A.Schmidt 1875|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora fusca': 1,
  'Amphora graeffeana|Amphora graeffeana Hendey 1973|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora graeffeana': 3,
  'Amphora helenensis|Amphora helenensis Giffen 1973|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora helenensis': 2,
  'Amphora indistincta|Amphora indistincta Levkov 2009|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora indistincta': 1,
  'Amphora laevissima|Amphora laevissima W.Gregory 1857|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora laevissima': 1,
  'Amphora lativentralis|Amphora lativentralis Stepanek  Kociolek 2018|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora lativentralis': 3,
  'Amphora lineolata|Amphora lineolata Ehrenberg 1838|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora lineolata': 1,
  'Amphora margalefii var. lacustris|Amphora margalefii var. lacustris P.Sanchez 1993|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora margalefii': 1,
  'Amphora obtusa var. crassa|Amphora obtusa var. crassa Tempere  Peragallo 1908|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora obtusa': 1,
  'Amphora obtusa|Amphora obtusa Leuduger-Fortmorel 1879|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora obtusa': 1,
  'Amphora ovalis|Amphora ovalis Kutzing Kutzing 1844|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora ovalis': 8,
  'Amphora pediculus|Amphora pediculus Kutzing Grunow ex A.Schmidt 1875|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora pediculus': 66,
  'Amphora proteoides|Amphora proteoides Hustedt|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora proteoides': 1,
  'Amphora proteus|Amphora proteus Gregory 1857|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora proteus': 1,
  'Amphora securicula|Amphora securicula H.Peragallo  M.Peragallo 1899|species|Chromista|Ochrophyta|Bacillariophyceae|nan|nan|Tetramphora|Amphora securicula': 1,
  'Amphora semperpalorum|Amphora semperpalorum A.H.Wachnicka  E.E.Gaiser 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora semperpalorum': 1,
  'Amphora sublaevis|Amphora sublaevis F.Hustedt 1955|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora sublaevis': 2,
  'Amphora sulcata|Amphora sulcata Gregory 1854|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora sulcata': 1,
  'Amphora thumensis|Amphora thumensis Mayer A.Cleve 1932|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora thumensis': 1,
  'Amphora vixvisibilis|Amphora vixvisibilis Ch.Li  Witkowski 2016|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora vixvisibilis': 1,
  'Amphora waldeniana|Amphora waldeniana J.G.Stepanek  J.P.Kociolek 2013|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiophysales|Catenulaceae|Amphora|Amphora waldeniana': 1,
  'Anaulus australis|Anaulus australis Drebes  Schulz 1989|species|Chromista|Ochrophyta|Bacillariophyceae|Anaulales|Anaulaceae|Anaulus|Anaulus australis': 5,
  'Aneumastus albanicus|Aneumastus albanicus Lange-Bertalot  Miho 2001|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus albanicus': 3,
  'Aneumastus macedonicus|Aneumastus macedonicus Z.Levkov 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus macedonicus': 2,
  'Aneumastus mongolotusculus|Aneumastus mongolotusculus Maltsev Andreeva  Kulikovskiy 2019|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus mongolotusculus': 1,
  'Aneumastus ohridanus|Aneumastus ohridanus Z.Levkov  D.Metzeltin 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus ohridanus': 2,
  'Aneumastus pseudoapiculatus|Aneumastus pseudoapiculatus Z.Levkov  D.Metzeltin 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus pseudoapiculatus': 4,
  'Aneumastus rhombicus|Aneumastus rhombicus Z.Levkov  D.Metzeltin 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus rhombicus': 2,
  'Aneumastus rostratus|Aneumastus rostratus Hustedt Lange-Bertalot 2001|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula|Aneumastus rostratus': 1,
  'Aneumastus stroesei|Aneumastus stroesei strup D.G.Mann 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Naviculaceae|Navicula|Aneumastus stroesei': 2,
  'Aneumastus subapiculatus|Aneumastus subapiculatus Z.Levkov  T.Nakov 2007|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus subapiculatus': 2,
  'Aneumastus tusculus|Aneumastus tusculus Ehrenberg D.G.Mann  Stickle 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Mastogloiales|Mastogloiaceae|Aneumastus|Aneumastus tusculus': 1,
  'Anomoeoneis fogedii|Anomoeoneis fogedii Reimer 1982|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Anomoeoneidaceae|Anomoeoneis|Anomoeoneis fogedii': 1,
  'Anomoeoneis sculpta|Anomoeoneis sculpta Ehrenberg Cleve 1896|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Anomoeoneidaceae|Anomoeoneis|Anomoeoneis sculpta': 1,
  'Anomoeoneis sphaerophora|Anomoeoneis sphaerophora E.Pfitzer 1871|species|Chromista|Ochrophyta|Bacillariophyceae|Cymbellales|Anomoeoneidaceae|Anomoeoneis|Anomoeoneis sphaerophora': 1,
  'Ardissonea baculus|Ardissonea baculus Gregory|species|Chromista|Ochrophyta|Bacillariophyceae|Ardissoneales|Ardissoneaceae|Ardissonea|Ardissonea baculus': 1,
  'Ardissonea crystallina|Ardissonea crystallina C.Agardh Grunow 1880|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Synedra|Ardissonea crystallina': 1,
  'Ardissonea formosa|Ardissonea formosa Hantzsch Grunow|species|Chromista|Ochrophyta|Bacillariophyceae|Ardissoneales|Ardissoneaceae|Ardissonea|Ardissonea formosa': 1,
  'Ardissonea fulgens|Ardissonea fulgens Grev. Kanjer Kusber  Van de Vijver|species|Chromista|Ochrophyta|Bacillariophyceae|Ardissoneales|Ardissoneaceae|Ardissonea|Ardissonea fulgens': 1,
  'Asterionella formosa|Asterionella formosa Hassall 1850|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Asterionella|Asterionella formosa': 20,
  'Asterionellopsis glacialis|Asterionellopsis glacialis Castracane Round 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Asterionella|Asterionellopsis glacialis': 3,
  'Asterionellopsis guyunusae|Asterionellopsis F.E.Round 1990|genus|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Asterionellopsis|nan': 1,
  'Asterionellopsis lenisilicea|Asterionellopsis F.E.Round 1990|genus|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Asterionellopsis|nan': 1,
  'Asterionellopsis tropicalis|Asterionellopsis tropicalis Franco 2016|species|Chromista|Ochrophyta|Bacillariophyceae|Fragilariales|Fragilariaceae|Asterionellopsis|Asterionellopsis tropicalis': 1,
  'Asteromphalus sp.|Asteromphalus C.G.Ehrenberg 1844|genus|Chromista|Ochrophyta|Bacillariophyceae|Asterolamprales|Asterolampraceae|Asteromphalus|nan': 1,
  'Attheya armata|Attheya armata T.West R.M.Crawford 1994|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Chaetocerotaceae|Chaetoceros|Attheya armata': 1,
  'Attheya decora|Attheya decora T.West 1860|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Attheyaceae|Attheya|Attheya decora': 1,
  'Attheya longicornis|Attheya longicornis R.M.Crawford  C.Gardner 1994|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Attheyaceae|Attheya|Attheya longicornis': 1,
  'Attheya septentrionalis|Attheya septentrionalis strup R.M.Crawford 1994|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Chaetocerotaceae|Chaetoceros|Attheya septentrionalis': 3,
  'Aulacodiscus oreganus|Aulacodiscus oreganus|species|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Aulacodiscaceae|Aulacodiscus|Aulacodiscus oreganus': 1,
  'Aulacodiscus orientalis|Aulacodiscus orientalis Greville 1864|species|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Aulacodiscaceae|Aulacodiscus|Aulacodiscus orientalis': 1,
  'Aulacoseira ambigua|Aulacoseira ambigua Grunow Simonsen 1979|species|Chromista|Ochrophyta|Bacillariophyceae|Aulacoseirales|Aulacoseiraceae|Aulacoseira|Aulacoseira ambigua': 10,
  'Aulacoseira granulata|Aulacoseira granulata Ehrenberg Simonsen 1979|species|Chromista|Ochrophyta|Bacillariophyceae|Aulacoseirales|Aulacoseiraceae|Aulacoseira|Aulacoseira granulata': 15,
  'Aulacoseira pusilla|Aulacoseira pusilla F.Meister Tuji  Houk 2004|species|Chromista|Ochrophyta|Bacillariophyceae|Melosirales|Melosiraceae|Melosira|Aulacoseira pusilla': 16,
  'Aulacoseira sp.|Aulacoseira G.H.K.Thwaites 1848|genus|Chromista|Ochrophyta|Bacillariophyceae|Aulacoseirales|Aulacoseiraceae|Aulacoseira|nan': 1,
  'Aulacoseira subarctica|Aulacoseira subarctica Otto Muller E.Y.Haworth 1990|species|Chromista|Ochrophyta|Bacillariophyceae|Aulacoseirales|Aulacoseiraceae|Aulacoseira|Aulacoseira subarctica': 4,
  'Aulacoseira tenella|Aulacoseira tenella Nygaard Simonsen 1979|species|Chromista|Ochrophyta|Bacillariophyceae|Melosirales|Melosiraceae|Melosira|Aulacoseira tenella': 4,
  'Aulacoseira valida|Aulacoseira valida Grunow Krammer 1991|species|Chromista|Ochrophyta|Bacillariophyceae|Aulacoseirales|Aulacoseiraceae|Aulacoseira|Aulacoseira valida': 1,
  'Auricula cf. complexa|Auricula complexa Gregory Cleve 1894|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Amphipleuraceae|Amphiprora|Auricula complexa': 1,
  'Auricula cf. flabelliformis|Auricula flabelliformis M.Voigt 1960|species|Chromista|Ochrophyta|Bacillariophyceae|Surirellales|Auriculaceae|Auricula|Auricula flabelliformis': 1,
  'Auricula cf. minuta|Auricula minuta Cleve 1894|species|Chromista|Ochrophyta|Bacillariophyceae|Surirellales|Auriculaceae|Auricula|Auricula minuta': 1,
  'Auricula complexa|Auricula complexa Gregory Cleve 1894|species|Chromista|Ochrophyta|Bacillariophyceae|Naviculales|Amphipleuraceae|Amphiprora|Auricula complexa': 1,
  'Auricula mirabilis|Auricula mirabilis F.Meister Paddock  Sims 1980|species|Chromista|Ochrophyta|Bacillariophyceae|nan|nan|Hustedtia|Auricula mirabilis': 1,
  'Bacillaria paxillifer|Bacillaria paxillifer O.F.Mull. Hendey|species|Chromista|Ochrophyta|Bacillariophyceae|nan|nan|Vibrio|Bacillaria paxillifer': 11,
  'Bacteriastrum jadranum|Bacteriastrum jadranum Godrijan Maric  Pfannkuchen 2012|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Chaetocerotaceae|Bacteriastrum|Bacteriastrum jadranum': 1,
  'Bacteriastrum mediterraneum|Bacteriastrum mediterraneum Pavillard|species|Chromista|Ochrophyta|Bacillariophyceae|Chaetocerotales|Chaetocerotaceae|Bacteriastrum|Bacteriastrum mediterraneum': 1,
  'Bacterosira bathyomphala|Bacterosira bathyomphala Cleve Syvertsen  Hasle 1993|species|Chromista|Ochrophyta|Bacillariophyceae|Coscinodiscales|Coscinodiscaceae|Coscinodiscus|Bacterosira bathyomphala': 1,
  'Bacterosira constricta|Bacterosira constricta Gaarder 1938 J.S.Park  J.H.Lee 2016|species|Chromista|Ochrophyta|Bacillariophyceae|Thalassiosirales|Thallassiosiraceae|Bacterosira|Bacterosira constricta': 1,
  'Bellerochea horologicalis|Bellerochea horologicalis Stosch 1980|species|Chromista|Ochrophyta|Bacillariophyceae|Hemiaulales|Bellerocheaceae|Bellerochea|Bellerochea horologicalis': 1,
  'Bellerochea malleus|Bellerochea malleus Brightwell Van Heurck 1885|species|Chromista|Ochrophyta|Bacillariophyceae|Hemiaulales|Bellerocheaceae|Bellerochea|Bellerochea malleus': 3,
  'Bellerochea yucatanensis|Bellerochea yucatanensis Stosch 1977|species|Chromista|Ochrophyta|Bacillariophyceae|Hemiaulales|Bellerocheaceae|Bellerochea|Bellerochea yucatanensis': 1,