In [1]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.data

Retrieving taxonomy in header, from column 1 to column 10, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.

,seq_id,sequence,length,taxa_info
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...
...,...,...,...,...
9228,OX258991,GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...,998,Navicula concordia|Navicula concordia Witkowsk...
9229,PP073739,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-
9230,PP073741,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,729,Sellaphora pupula|Sellaphora pupula Kutzing Me...
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,626,Amphora copulata|Amphora copulata Kutzing Scho...

In [2]:
pre_processed = dt_class.pre_process_harmonized_fasta()
pre_processed

mozaiko INFO: This method assumes that the FASTA header has been harmonized and contains the following pipe-separated 'columns':
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9226,OX258989,AGTGACCGTGACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTT...,1005,Planothidium wetzelii|Planothidium F.E.Round ...,Planothidium wetzelii,Planothidium F.E.Round L.Bukhtiyarova 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Planothidium,NaN
9227,OX258990,GTAATCCCTTACGCTAAAATGGGTTACTGGGATGCTTCATACGCAG...,986,Psammothidium papilio|Psammothidium L.Bukhtiya...,Psammothidium papilio,Psammothidium L.Bukhtiyarova F.E.Round 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Psammothidium,NaN
9228,OX258991,GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...,998,Navicula concordia|Navicula concordia Witkowsk...,Navicula concordia,Navicula concordia Witkowski Riaux-Gobin Dani...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Naviculaceae,Navicula,Navicula concordia
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,729,Sellaphora pupula|Sellaphora pupula Kutzing Me...,Sellaphora pupula,Sellaphora pupula Kutzing Mereschkovsky 1902,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Sellaphoraceae,Sellaphora,Sellaphora pupula
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,626,Amphora copulata|Amphora copulata Kutzing Scho...,Amphora copulata,Amphora copulata Kutzing Schoeman R.E.M.Archi...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Amphipleuraceae,Frustulia,Amphora copulata

In [16]:
import pandas as pd
dt_class.data = pd.concat(
            [dt_class.data, dt_class.data["taxa_info"].str.split("|", expand=True)], axis=1
        )

In [17]:
dt_class.data.columns = [
            "seq_id",
            "sequence",
            "length",
            "all_taxa_info",
            "original_taxa_info",
            "scientificName",
            "rank",
            "kingdom",
            "phylum",
            "class",
            "order",
            "family",
            "genus"
        ]

In [4]:
dt_class.data[dt_class.data['rank'] == 'CLASS']

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus
1263,AY485503,ACTGCGAATGGCTCATTATATCAGTTATAGTTTATTTGATAATTCC...,1632,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
1840,X85389,AACCTGGTTGATCCTGCCAGTAGTCATACGCTCGTCTCAAAGATTA...,1798,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
1852,AM502026,TAGTCATACGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTAC...,1721,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
2585,FJ002126,ATAATGGGTTATTGGGATGCTTCATACTCAGTAAAAGCTACTGATG...,1054,Eucampia antarctica|Bacillariophyceae|CLASS|Ch...,Eucampia antarctica,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
2811,AM710493,ATACAACAGACCACTTCTTTGCTTTTATCGCATACGAATGTGATTT...,683,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4271,KJ011623,AGTAGTCATACGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGT...,1597,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4454,KM197150,GCTCGTAGTTGGATTTGTGGCAGTCGCGTGCGGCCCGGCATTCGTG...,330,Bacillariophyceae sp.|Bacillariophyceae|CLASS|...,Bacillariophyceae sp.,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-
4493,KJ011806,AGTGACCGTTACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTT...,1401,Cymbella lanceolata|Bacillariophyceae|CLASS|Ch...,Cymbella lanceolata,Bacillariophyceae,CLASS,Chromista,Ochrophyta,Bacillariophyceae,-,-,-

In [18]:
dt_class.data['rank'] = dt_class.data['rank'].str.lower()

In [19]:
non_interest_ranks = ['kingdom', 'phylum', 'class', 'order']
dt_class.data = dt_class.data = dt_class.data[~dt_class.data['rank'].isin(non_interest_ranks)]

In [7]:
dt_class.data[dt_class.data['rank'] == 'class']

Empty DataFrame
Columns: [seq_id, sequence, length, all_taxa_info, original_taxa_info, scientificName, rank, kingdom, phylum, class, order, family, genus]
Index: []

In [20]:
import numpy as np
dt_class.data = dt_class.data.replace("-", np.nan)

In [9]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus
55,TCC162-18S-1,TGCATGTCTAAGTATAAACTGCTTTATACTGTGAAACTGCGAATGG...,1676,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,TCC208-18S-1,GAGTTTTCTCTGAATCTGCGAATGGCTCATTATATCAGTTATAGTT...,1663,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,TCC212-18S-1,TATAAGCAAATTTATACGTGAAACTGCGAATGGCTCATTATATCAG...,1627,Chlorella sp.|-|-|-|-|-|-|-|-,Chlorella sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099,TCC715-Rbcl-1,ATTAAAGTGACCGTTACGAATCTGGTGTAATTCCTTACGCTAAAAT...,1445,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1213,TCC812-28S-1,CCCGCTGGAATTTAAGCATATAATTAAGCGGAGGAAAAGAAACTAA...,577,Nitzschia sp.|-|-|-|-|-|-|-|-,Nitzschia sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8927,OP297455,GACCGTTACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACT...,1121,Nitzschia sp.|-|-|-|-|-|-|-|-,Nitzschia sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9080,OR066516,ATCTGGYGTAATTCCTTACGCTAAAATGGGTTACTGGGATGCTTCA...,985,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9081,OR066517,ATCTGGYGTAATTCCTTACGCTAAAATGGGTTACTGGGATGCTTCA...,985,Gomphadelpha kociolekii|-|-|-|-|-|-|-|-,Gomphadelpha kociolekii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9229,PP073739,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-,Nitzschia nandorii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9230,PP073741,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,1155,Nitzschia nandorii|-|-|-|-|-|-|-|-,Nitzschia nandorii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
dt_class.data = dt_class.data.dropna(subset=["scientificName"], how="all")

In [11]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

Empty DataFrame
Columns: [seq_id, sequence, length, all_taxa_info, original_taxa_info, scientificName, rank, kingdom, phylum, class, order, family, genus]
Index: []

In [22]:
species_variants = ['species', 'form', 'variety', 'subspecies']
dt_class.data['species'] = np.where(
    dt_class.data['rank'].str.lower().isin(species_variants),
    dt_class.data['scientificName'],  # Assign scientificName if condition is met
    np.nan  # Assign NaN otherwise
)
dt_class.data['species'] = dt_class.data['species'].str.split(' ').str[0] + ' ' + dt_class.data['species'].str.split(' ').str[1]

In [23]:
dt_class.data

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9226,OX258989,AGTGACCGTGACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTT...,1005,Planothidium wetzelii|Planothidium F.E.Round ...,Planothidium wetzelii,Planothidium F.E.Round L.Bukhtiyarova 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Planothidium,NaN
9227,OX258990,GTAATCCCTTACGCTAAAATGGGTTACTGGGATGCTTCATACGCAG...,986,Psammothidium papilio|Psammothidium L.Bukhtiya...,Psammothidium papilio,Psammothidium L.Bukhtiyarova F.E.Round 1996,genus,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Psammothidium,NaN
9228,OX258991,GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...,998,Navicula concordia|Navicula concordia Witkowsk...,Navicula concordia,Navicula concordia Witkowski Riaux-Gobin Dani...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Naviculaceae,Navicula,Navicula concordia
9231,PP196581,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,729,Sellaphora pupula|Sellaphora pupula Kutzing Me...,Sellaphora pupula,Sellaphora pupula Kutzing Mereschkovsky 1902,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Sellaphoraceae,Sellaphora,Sellaphora pupula
9232,PP196582,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,626,Amphora copulata|Amphora copulata Kutzing Scho...,Amphora copulata,Amphora copulata Kutzing Schoeman R.E.M.Archi...,species,Chromista,Ochrophyta,Bacillariophyceae,Naviculales,Amphipleuraceae,Frustulia,Amphora copulata

In [3]:
tax = all_comp['taxa_info']
unq_taxa = tax.unique()
len(unq_taxa)

NameError: name 'all_comp' is not defined

In [5]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "../data/test_data/fasta_example_file.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.get_sequences()
dt_class.data

No TaxIDs found in the fasta file. Starting lineage file upload process.

        --------------------------------- help message ---------------------------------------
        Taxonomic information is needed to continue the in-silico analysis.
        The inputed FASTA file does not contain Taxonomic IDs.
        Please upload a TSV file containing the sequence IDs and taxonomic lineage.

        The TSV file must contain the columns:
        [seq_id, species, genus, family, order, class, phylum, subkingdom, kingdom, empire].
        Please make sure columns follow the same order before uploading.

        For the taxonomic levels where no assignment is available, please leave the cells blank.

        If your FASTA file does contain Taxonomic IDs for all sequences, please make sure these
        are present in each sequence header.
        For correct reading, these must be identified with 'taxid=' beforehand.
        For example: 'CM074756.1;taxid=8481'.
        ---------------------------------------------------------------------------------------

Operation canceled. Data currently in memory:

        seq_id             sequence  length
0   CM074756.1     GTTATTGTAGCTTATC      16
1  NC_088426.1  GCATAAAGCATGGCACTGA      19
2   PP475397.1             GTTATTGA       8

In [3]:
dt_class.get_mapping_between_seq_id_taxonomy()

{'CM074756.1': '', 'NC_088426.1': '', 'PP475397.1': ''}

In [9]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
diat_data_df = dt_class.data
diat_data_df.to_csv("try.csv")

In [13]:
dt_class.get_sequence_ids()

['CM074756.1', 'NC_088426.1', 'PP475397.1']

In [14]:
dt_class.get_sequence_lengths()

[16, 19, 8]

-----------

In [ ]:
from src.reference_database.sequence_import import *

In [8]:
fasta= '../data/input_data/diat-barcode.fasta'
cls = CustomFastaImport(fasta)
cls.read_fasta(fasta)

No TaxIDs found in the fasta file. Starting lineage file upload process.

        --------------------------------- help message ---------------------------------------
        Taxonomic information is needed to continue the in-silico analysis.
        The inputed FASTA file does not contain Taxonomic IDs.
        Please upload a TSV file containing the sequence IDs and taxonomic lineage.

        The TSV file must contain the columns:
        [seq_id, species, genus, family, order, class, phylum, subkingdom, kingdom, empire].
        Please make sure columns follow the same order before uploading.

        For the taxonomic levels where no assignment is available, please leave the cells blank.

        If your FASTA file does contain Taxonomic IDs for all sequences, please make sure these
        are present in each sequence header.
        For correct reading, these must be identified with 'taxid=' beforehand.
        For example: 'CM074756.1;taxid=8481'.
        ---------------------------------------------------------------------------------------

File uploaded successfully.

           seq_id                                           sequence  length
0      TCC6-18S-1  TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...    1688
1     TCC7a-18S-1  TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...    1680
2      TCC9-18S-1  GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...    1659
3     TCC26-18S-1  CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...    1636
4     TCC27-18S-1  TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...    1638
...           ...                                                ...     ...
9228     OX258991  GACGAATCTGGTGTAATCCCTTACGCTAAAATGGGTTACTGGGATG...     998
9229     PP073739  GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...    1155
9230     PP073741  TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...    1155
9231     PP196581  TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...     729
9232     PP196582  GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...     626

[9233 rows x 3 columns]

In [9]:
dt_class.lineage_file

In [18]:
dt_class.lineage_file.columns.to_list()

AttributeError: 'NoneType' object has no attribute 'columns'

In [ ]:
from src.reference_database.db_curation import *
crabs = CrabsScriptGenerator()
json_file = "../src/reference_database/assign_tax_parameters.json"
crabs.run_assign_tax_command(json_file)

## Test with Trial example
Issue: Fasta is not formatted as it should. Should not have tax id separated by ID -> affecting how PGA reads sequences

In [ ]:
def clean_fasta_headers(input_file, output_file):
    unique_tax = set()
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        for line in infile:
            if line.startswith('>'):
                header = line.split(";", 2)
                seq_id = header[0].strip()
                tax_id = header[1].strip()
                unique_tax.add(tax_id)
                formatted_header = seq_id + " | " + tax_id + "\n"
                # print(formatted_header)
                outfile.write(formatted_header)
            else:
                outfile.write(line)

        print(len(unique_tax))

clean_fasta_headers("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference.fasta", "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta")

402

In [1]:
from src.in_silico_analysis.amplification import InSilicoAmplification
data = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"
run_name = "diat-barcode-testimport"
cutadapt = InSilicoAmplification(data, run_name=run_name)
cutadapt.run_in_silico_analysis(primer_table=primer_table)

ModuleNotFoundError: No module named 'src.in_silico_analysis'

### MultiBarcodeTools

In [2]:
from src.marker_scoring.scoring_utils import create_MultiBarcodeTools_input

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/insert/filtered"
output_dir = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/diat-multibarcode-insert.tsv"
create_MultiBarcodeTools_input(insert_path, output_dir)

Conversion complete. Output written to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/diat-multibarcode-insert.tsv

#### With joined incomplete pbs

In [1]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered/filtered_intersection and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  1060 species
2: rbcL_646F_998R, resolve additional 40 species
3: rbcL_708F1_R3_2, resolve additional 3 species
4: rbcL_708F3_R3_2, resolve additional 2 species
5: rbcL_708F2_R3_2, resolve additional 2 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode

,primer,additional_resolved_species,cumulative_resolved_species
0,rbcL_708F_DEG_R3_DEG,1060,1060
1,rbcL_646F_998R,40,1100
2,rbcL_708F1_R3_2,3,1103
3,rbcL_708F3_R3_2,2,1105
4,rbcL_708F2_R3_2,2,1107

In [2]:
from src.marker_scoring.metrics_system import *

trait.get_taxonomic_resolution(otl_total_taxa_count=1500)

,primer,additional_resolved_species,cumulative_resolved_species,taxonomic_resolution_percentage
0,rbcL_708F_DEG_R3_DEG,1060,1060,70.67
1,rbcL_646F_998R,40,1100,73.33
2,rbcL_708F1_R3_2,3,1103,73.53
3,rbcL_708F3_R3_2,2,1105,73.67
4,rbcL_708F2_R3_2,2,1107,73.80

In [3]:
trait.load_nucleotide_distance()

,Species,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Chilomonas_paramecium,-,85,-,-,-,-,-,-
1,Hannaea_arcus,2,2,2,2,2,2,2,2
2,Stauroneis_gracilior,11,17,11,11,11,11,11,11
3,Hyalosira_tropicalis,14,15,14,14,14,14,14,14
4,Adlafia_bryophila,33,39,37,37,38,38,38,38
...,...,...,...,...,...,...,...,...,...
1405,Amphora_beaufortiana,6,6,6,6,6,6,6,6
1406,Pseudo_nitzschia_multistriata,24,26,24,14,24,24,24,14
1407,Planktoniella_sol,19,36,-,-,19,19,-,-
1408,Tetramphora_chilensis,26,32,26,-,26,26,26,-
1409,Pinnularia_subgibba_var_sublinearis,1,1,1,1,1,1,1,1

#### without joined incomplete PBS

In [1]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/insert/filtered and amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/amplicon/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  1020 species
2: rbcL_646F_998R, resolve additional 31 species
3: rbcL_708F3_R3_2, resolve additional 2 species
4: rbcL_708F1_R3_2, resolve additional 1 species
5: rbcL_708F2_R3_2, resolve additional 1 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/multibarcode

,primer,additional_resolved_species,cumulative_resolved_species
0,rbcL_708F_DEG_R3_DEG,1020,1020
1,rbcL_646F_998R,31,1051
2,rbcL_708F3_R3_2,2,1053
3,rbcL_708F1_R3_2,1,1054
4,rbcL_708F2_R3_2,1,1055

In [ ]:
from src.reference_database.sequence_import import CustomFastaImport

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/all_inserts/rbcL_646F_998R.fasta"
cls = CustomFastaImport()
cls.read_fasta(insert_path)

,seq_id,taxa_info,sequence,length
0,TCC7a-Rbcl-1,Fragilaria sp.,TTATACTGTATGGAAGGTATCAATCGTGCTGCAGCTGCAACAGGTG...,331
1,TCC134-Rbcl-1,Ulnaria acus,TTAAACTGTATGGAAGGTATTAACCGTGCGTCAGCTGCAACAGGTG...,331
2,TCC425-Rbcl-1,Nitzschia palea,TTAAACTGTATGGAAGGTATTAACCGTGCTTCAGCTGCAACAGGTG...,331
3,TCC426-Rbcl-1,Gomphonema parvulum,TTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
4,TCC429-Rbcl-1,Gomphonema lagenula,TTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
...,...,...,...,...
4599,OX258989,Planothidium wetzelii,TTATACTGTATGGAAGGTATTAACCGTGCTTCTTCAGCTACAGGTG...,331
4600,OX258990,Psammothidium papilio,TTAAACTGTATGGAAGGTATCAACCGTGCTTCTTCAGCTACAGGTG...,331
4601,OX258991,Navicula concordia,TTATACTGTATGGAAGGTATTAACCGTGCATCAGCAGCTACAGGTG...,331
4602,PP073739,Nitzschia nandorii,CTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331
4603,PP073741,Nitzschia nandorii,CTAAACTGTATGGAAGGTATTAACCGTGCTTCTGCTGCTACAGGTG...,331

In [ ]:
from src.marker_scoring.metrics_system import *

otl = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"
insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-amplicon/all_inserts"


otl_h = OtlHandler(otl=otl)
_, taxa_set = otl_h.import_otl()

otl_h.apply_fasta_filtering_for_all_fasta_files_in_folder(insert_path, otl_taxa_set=taxa_set, overwrite=False)

# otl_filtered_path = insert_path + "/all_inserts_otl_filtered"
# cls = ReferenceDatabaseQuality(otl_filtered_path, otl)
# dict_prev = cls.calculate_number_of_barcodes_per_taxon()

In [ ]:
upt_dict = otl_h.add_sequences_not_in_silico_amplified_but_in_otl_with_value_as_zero(dict_prev, taxa_set)

In [ ]:
cls.calculate_percentage_of_taxa_w_x_barcodes()

{'rbcL_708F1_R3-1': 12.31,
 'rbcL_708F-DEG_R3-DEG': 13.12,
 'rbcL_708F1_R3-2': 12.27,
 'rbcL_646F_998R': 12.61,
 'rbcL_708F2_R3-1': 12.86,
 'rbcL_708F3_R3-1': 11.43}

In [ ]:
cls.barcoded_taxa_ratio()

{'rbcL_708F1_R3-1': {'barcoded_taxa_five_plus': 1.69,
  'ratio_barcoded_taxa': 7.28},
 'rbcL_708F-DEG_R3-DEG': {'barcoded_taxa_five_plus': 1.73,
  'ratio_barcoded_taxa': 7.58},
 'rbcL_708F1_R3-2': {'barcoded_taxa_five_plus': 1.65,
  'ratio_barcoded_taxa': 7.44},
 'rbcL_646F_998R': {'barcoded_taxa_five_plus': 1.65,
  'ratio_barcoded_taxa': 7.64},
 'rbcL_708F2_R3-1': {'barcoded_taxa_five_plus': 1.65,
  'ratio_barcoded_taxa': 7.79},
 'rbcL_708F3_R3-1': {'barcoded_taxa_five_plus': 1.47,
  'ratio_barcoded_taxa': 7.78}}

In [ ]:
from src.marker_scoring.metrics_system import ReferenceDatabaseQuality
import os

output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/all_inserts"

otl1 = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"

for filename in os.listdir(output_folder):
    if filename.endswith(".fasta"):
        fasta_file = os.path.join(output_folder, filename)
        cls = ReferenceDatabaseQuality(fasta_file, otl1)
        score = cls.barcode_coverage_score()
        filename = filename.split(".")[0]
        print(f"Score for {filename}: {score}")

Score for rbcL_708F1_R3-1: 4.35
Score for rbcL_708F-DEG_R3-DEG: 4.58
Score for rbcL_708F1_R3-2: 4.32
Score for rbcL_646F_998R: 4.4
Score for rbcL_708F2_R3-1: 4.47
Score for rbcL_708F3_R3-1: 3.96

In [ ]:
otl2 = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/Germany_phylib_taxonlist.tsv"

for filename in os.listdir(output_folder):
    if filename.endswith(".fasta"):
        fasta_file = os.path.join(output_folder, filename)
        cls = ReferenceDatabaseQuality(fasta_file, otl2)
        score = cls.barcode_coverage_score()
        print(f"Score for {filename}: {score}")

Score for rbcL_708F1_R3-1.fasta: 4.35
Score for rbcL_708F-DEG_R3-DEG.fasta: 4.58
Score for rbcL_708F1_R3-2.fasta: 4.3
Score for rbcL_646F_998R.fasta: 4.39
Score for rbcL_708F2_R3-1.fasta: 4.45
Score for rbcL_708F3_R3-1.fasta: 3.96

In [ ]:
from src.marker_scoring.metrics_system import MetricsSystemExecutor

output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/all_inserts"
otl1 = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"

cls = MetricsSystemExecutor(output_folder, otl1)
abc = cls.calculate_reference_database_quality()
abc

                                     taxa
0                     Amphora acutiuscula
1                        Amphora aequalis
2                      Achnanthes affinis
3                     Amphora aff. vetula
4     Achnanthes austriaca var. helvetica
...                                   ...
2779             Ulnaria ulna var. danica
2780                         Ulnaria ulna
2781                  Ulnaria ulna terato
2782                    Ulnaria ungeriana
2783             Ulnaria ungeriana terato

[2784 rows x 1 columns]
Processing file: rbcL_708F1_R3-1.fasta
Processing file: rbcL_708F2_R3-2.fasta
Processing file: rbcL_708F-DEG_R3-DEG.fasta
Processing file: rbcL_708F1_R3-2.fasta
Processing file: rbcL_646F_998R.fasta
Processing file: rbcL_708F2_R3-1.fasta
Processing file: rbcL_708F3_R3-2.fasta
Processing file: rbcL_708F3_R3-1.fasta

{'rbcL_708F1_R3-1': {'barcoded_taxa_five_plus': 0.74,
  'ratio_barcoded_taxa': 0.16},
 'rbcL_708F2_R3-2': {'barcoded_taxa_five_plus': 0.74,
  'ratio_barcoded_taxa': 0.16},
 'rbcL_708F-DEG_R3-DEG': {'barcoded_taxa_five_plus': 0.74,
  'ratio_barcoded_taxa': 0.16},
 'rbcL_708F1_R3-2': {'barcoded_taxa_five_plus': 0.74,
  'ratio_barcoded_taxa': 0.17},
 'rbcL_646F_998R': {'barcoded_taxa_five_plus': 0.66,
  'ratio_barcoded_taxa': 0.15},
 'rbcL_708F2_R3-1': {'barcoded_taxa_five_plus': 0.74,
  'ratio_barcoded_taxa': 0.16},
 'rbcL_708F3_R3-2': {'barcoded_taxa_five_plus': 0.7,
  'ratio_barcoded_taxa': 0.17},
 'rbcL_708F3_R3-1': {'barcoded_taxa_five_plus': 0.7,
  'ratio_barcoded_taxa': 0.17}}

### Binding

In [4]:
from src.marker_scoring.metrics_system import *

output_folder =  "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode"
otl = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"

cls = MetricsSystemExecutor(results_folder=output_folder, otl=otl, primer_table=primer_table)
ref_qual = cls.get_reference_database_quality()
ref_qual

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.

                      barcoded_taxa_one_plus  ratio_barcoded_taxa
rbcL_708F1_R3-1                        12.30                 0.14
rbcL_708F2_R3-2                        12.85                 0.13
rbcL_708F-DEG_R3-DEG                   13.11                 0.13
rbcL_708F1_R3-2                        12.27                 0.14
rbcL_646F_998R                         12.63                 0.13
rbcL_708F2_R3-1                        12.89                 0.13
rbcL_708F3_R3-2                        11.45                 0.13
rbcL_708F3_R3-1                        11.49                 0.13

In [5]:
primer_pbs, gc_df = cls.get_primer_pbs_analysis()

In [6]:
binding = Binding()
tax_lev_max_ms = binding.process_analysis_per_taxon(primer_pbs['rbcL_646F_998R'], operation='max', analysis_name='full_len_mismatch_sum')

In [7]:
binding.process_analysis_across_taxon(tax_lev_max_ms, operation='sum')

794.0

In [6]:
full_len_mismatch_sum = pd.DataFrame(primer_pbs['rbcL_646F_998R']['full_len_mismatch_sum'])
max_mismatch_three_end = pd.DataFrame(primer_pbs['rbcL_646F_998R']['three_end_mismatch_sum'])

In [9]:
binding.get_priming_ratio(full_len_mismatch_sum, max_mismatch_three_end)

NameError: name 'full_len_mismatch_sum' is not defined

In [12]:
abc = binding.get_total_gc_matches(primer_pbs['rbcL_646F_998R'])
abc.to_csv('abc.csv', sep='\t')

In [10]:
tax_lev_gc = binding.process_analysis_per_taxon(primer_pbs['rbcL_646F_998R'], operation='min', analysis_name='gc_matches_score')

In [11]:
binding.process_analysis_across_taxon(tax_lev_gc, operation='sum')

0.0

In [17]:
tax_lev_min_tm = binding.process_analysis_per_taxon(primer_pbs['rbcL_646F_998R'], operation='min', analysis_name='min_tm')

In [18]:
binding.process_analysis_across_taxon(tax_lev_min_tm, operation='coef_var')

2.19

In [13]:
binding.tm_score(primer_pbs['rbcL_646F_998R'])

45.01

In [3]:
amp_succ = binding.calculate_amplification_success_score(output_folder)
amp_succ_df = pd.DataFrame(amp_succ['amplification_sucess_percent'])
amp_succ_df

NameError: name 'binding' is not defined

In [ ]:
ref_qual.join(amp_succ_df)

#### Executor

In [1]:
from src.marker_scoring.metrics_system import *

output_folder =  "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode"
otl = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"

cls = MetricsSystemExecutor(results_folder=output_folder, otl=otl, primer_table=primer_table)
ref_qual = cls.comprehensive_primer_analysis(output_folder)

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.

In [2]:
ref_qual

,barcoded_taxa_one_plus,ratio_barcoded_taxa,max_mismatch_across_taxon,priming_ratio,gc_matches_across_taxon,tm_coefficient_var,tm_score,amplification_success_percent
primer,,,,,,,,
rbcL_708F1_R3_1,12.30,0.14,2273,30.17,2.0,1.19,17.16,82.11
rbcL_708F2_R3_2,12.85,0.13,2748,35.22,2.0,1.19,17.18,85.30
rbcL_708F_DEG_R3_DEG,13.11,0.13,1161,63.95,2.0,1.20,17.02,87.99
rbcL_708F1_R3_2,12.27,0.14,3450,20.95,2.0,1.18,17.14,81.87
rbcL_646F_998R,12.63,0.13,794,172.57,0.0,2.19,45.01,91.15
rbcL_708F2_R3_1,12.89,0.13,1521,55.87,2.0,1.20,17.21,85.55
rbcL_708F3_R3_2,11.45,0.13,4035,20.80,2.0,1.13,16.11,76.84
rbcL_708F3_R3_1,11.49,0.13,2903,30.55,2.0,1.14,16.15,76.91

In [3]:
ts_df = cls.get_traits_and_resolution(output_folder)
ts_df

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode/multibarcode_input.tsv
1: rbcL_708F_DEG_R3_DEG, resolve  1060 species
2: rbcL_646F_998R, resolve additional 40 species
3: rbcL_708F1_R3_2, resolve additional 3 species
4: rbcL_708F3_R3_2, resolve additional 2 species
5: rbcL_708F2_R3_2, resolve additional 2 species

mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/multibarcode

                      taxonomic_resolution_percentage  divergence_score
primer
rbcL_646F_998R                                  40.52             25.16
rbcL_708F1_R3_1                                   NaN             23.98
rbcL_708F1_R3_2                                 40.63             23.90
rbcL_708F2_R3_1                                   NaN             25.16
rbcL_708F2_R3_2                                 40.77             25.08
rbcL_708F3_R3_1                                   NaN             22.87
rbcL_708F3_R3_2                                 40.70             22.84
rbcL_708F_DEG_R3_DEG                            39.04             25.49

In [4]:
metrics_df = cls.join_analysis_results()
metrics_df

,barcoded_taxa_one_plus,ratio_barcoded_taxa,max_mismatch_across_taxon,priming_ratio,gc_matches_across_taxon,tm_coefficient_var,tm_score,amplification_success_percent,taxonomic_resolution_percentage,divergence_score
primer,,,,,,,,,,
rbcL_708F1_R3_1,12.30,0.14,2273,30.17,2.0,1.19,17.16,82.11,NaN,23.98
rbcL_708F2_R3_2,12.85,0.13,2748,35.22,2.0,1.19,17.18,85.30,40.77,25.08
rbcL_708F_DEG_R3_DEG,13.11,0.13,1161,63.95,2.0,1.20,17.02,87.99,39.04,25.49
rbcL_708F1_R3_2,12.27,0.14,3450,20.95,2.0,1.18,17.14,81.87,40.63,23.90
rbcL_646F_998R,12.63,0.13,794,172.57,0.0,2.19,45.01,91.15,40.52,25.16
rbcL_708F2_R3_1,12.89,0.13,1521,55.87,2.0,1.20,17.21,85.55,NaN,25.16
rbcL_708F3_R3_2,11.45,0.13,4035,20.80,2.0,1.13,16.11,76.84,40.70,22.84
rbcL_708F3_R3_1,11.49,0.13,2903,30.55,2.0,1.14,16.15,76.91,NaN,22.87

In [5]:
ranked_df = cls.rank_primers(metrics_df)
ranked_df

mozaico INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/ranked_primers.tsv

,primer,barcoded_taxa_one_plus,ratio_barcoded_taxa,max_mismatch_across_taxon,priming_ratio,gc_matches_across_taxon,tm_coefficient_var,tm_score,amplification_success_percent,taxonomic_resolution_percentage,...,rank_ratio_barcoded_taxa,rank_max_mismatch_across_taxon,rank_priming_ratio,rank_gc_matches_across_taxon,rank_tm_coefficient_var,rank_tm_score,rank_amplification_success_percent,rank_taxonomic_resolution_percentage,rank_divergence_score,final_rank
0,rbcL_708F1_R3_1,12.30,0.14,2273,30.17,2.0,1.19,17.16,82.11,NaN,...,1.5,4.0,3.0,4.0,4.5,4.0,5.0,NaN,4.0,35.0
1,rbcL_708F2_R3_1,12.89,0.13,1521,55.87,2.0,1.20,17.21,85.55,NaN,...,5.5,3.0,6.0,4.0,6.5,2.0,3.0,NaN,6.5,38.5
2,rbcL_708F1_R3_2,12.27,0.14,3450,20.95,2.0,1.18,17.14,81.87,40.63,...,1.5,7.0,2.0,4.0,3.0,5.0,6.0,3.0,3.0,40.5
3,rbcL_708F_DEG_R3_DEG,13.11,0.13,1161,63.95,2.0,1.20,17.02,87.99,39.04,...,5.5,2.0,7.0,4.0,6.5,6.0,2.0,1.0,8.0,43.0
4,rbcL_708F2_R3_2,12.85,0.13,2748,35.22,2.0,1.19,17.18,85.30,40.77,...,5.5,5.0,5.0,4.0,4.5,3.0,4.0,5.0,5.0,44.0
5,rbcL_708F3_R3_1,11.49,0.13,2903,30.55,2.0,1.14,16.15,76.91,NaN,...,5.5,6.0,4.0,4.0,2.0,7.0,7.0,NaN,2.0,44.5
6,rbcL_646F_998R,12.63,0.13,794,172.57,0.0,2.19,45.01,91.15,40.52,...,5.5,1.0,8.0,8.0,8.0,1.0,1.0,2.0,6.5,45.0
7,rbcL_708F3_R3_2,11.45,0.13,4035,20.80,2.0,1.13,16.11,76.84,40.70,...,5.5,8.0,1.0,4.0,1.0,8.0,8.0,4.0,1.0,48.5

##### ----------------------------------- END OF BINDING ---------------------------------------------

In [1]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/insert/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_12SMiFish-U.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/12S_12SMiFish-U.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_12SMiFish-U.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/amplicon/filtered/12S_12SMiFish-U.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_MarVer1.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_MarVer1.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-b.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-b.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-c.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_complete_pbs/filtered/12S_12S-V5-c.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Fuller1998.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Am12s.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Am12s.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_12S-V5-c.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_12S-V5-c.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Chon01.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/incomplete_pbs/filtered/12S_Chon01.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Hauck2019a.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Hauck2019a.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Fuller1998.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S/all_inserts/12S_Fuller1998.fasta']' returned non-zero exit status 1.

analysis_step,original_database,amplicon,amplicon-filtered,insert,insert-filtered,all_complete_pbs,all_complete_pbs-filtered,all_inserts
primer_name,,,,,,,,
12S_12S-V5-a,NA,824,823,824,823,1036,6,823
12S_12S-V5-b,NA,1016,1015,1016,1015,1041,NA,1015
12S_12S-V5-c,NA,718,715,718,715,745,NA,715
12S_12SMiFish-U,NA,NA,NA,150,150,348,171,150
12S_Ac12s,NA,93,93,785,780,1563,5,780
12S_AcMDB07,NA,763,755,761,753,782,5,753
12S_Am12s,NA,69,69,736,729,752,9,729
12S_Chon01,NA,728,725,728,725,745,6,725
12S_Elas02,NA,16,16,603,603,648,14,603
12S_Fuller1998,NA,NA,NA,NA,NA,NA,NA,NA
12S_Hauck2019a,NA,NA,NA,NA,NA,NA,NA,NA
12S_MarVer1,NA,743,742,743,742,769,NA,742
12S_MiFish-E,NA,97,97,590,590,644,24,590
12S_Tele01,NA,762,759,762,759,781,2,759
12S_Tele02,NA,653,652,692,691,751,31,691
12S_V12S-U,NA,741,741,741,741,763,1,741
12S_Vert01,NA,1016,1015,1016,1015,1599,3,1015
original_database,2722,NA,NA,NA,NA,NA,NA,NA

In [ ]:
three_end_fwd_gc_matches = calculate_iupac_mismatches(three_end_fwd_primers,three_end_fwd_seq,search_gc_clamp=True,)[1]

## Mismatches

In [3]:
from src.marker_scoring.metrics_system import *
from src.marker_scoring.scoring_utils import *

amp_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/amplicon/filtered"
insert_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/insert/filtered"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"


cls_instance = Binding()
analysis_results, gc = cls_instance.primer_pbs_analysis(amp_folder, insert_folder, primer_table)

In [4]:
gc

                      forward_primer_gc_fraction  reverse_primer_gc_fraction
primer_name
rbcL_646F_998R                          0.500000                    0.370370
rbcL_708F1_R3-1                         0.296296                    0.363636
rbcL_708F1_R3-2                         0.296296                    0.363636
rbcL_708F2_R3-1                         0.269231                    0.363636
rbcL_708F2_R3-2                         0.269231                    0.363636
rbcL_708F3_R3-1                         0.296296                    0.363636
rbcL_708F3_R3-2                         0.296296                    0.363636
rbcL_708F-DEG_R3-DEG                    0.280000                    0.363636

In [2]:
otl = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/france_taxonlist.tsv"
otl_handler = OtlHandler(otl)
otl_handler.import_otl()
total_otl_taxa_count = otl_handler.total_taxa
otl_unique_taxa_set = otl_handler.otl_taxa_set

                                     taxa
0                     Amphora acutiuscula
1                        Amphora aequalis
2                      Achnanthes affinis
3                     Amphora aff. vetula
4     Achnanthes austriaca var. helvetica
...                                   ...
2779             Ulnaria ulna var. danica
2780                         Ulnaria ulna
2781                  Ulnaria ulna terato
2782                    Ulnaria ungeriana
2783             Ulnaria ungeriana terato

[2784 rows x 1 columns]

In [3]:
process = cls_instance.iterate_over_primer_pbs_df(analysis_results, add_otl_taxa=False, otl_taxa_set=otl_unique_taxa_set)

In [4]:
attempt = cls_instance.get_primer_df('rbcL_708F_DEG_R3_DEG')

In [5]:
primer_pbs_df, primer_gc_df = cls_instance.primer_pbs_analysis(
    "../data/test_data/amplicon-test",
    "../data/test_data/insert-test",
    "../data/test_data/test_primer_table.tsv",
    save_results=False,
)

In [8]:
primer_pbs_df

{}

In [ ]:
gcm = cls_instance.get_total_gc_matches(attempt)
gcm['gc_matches_score'].max()

np.int64(1)

In [11]:
gcm_tax = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='min', analysis_name='gc_matches_score')
gcm_tax

                             gc_matches_score
taxon
 Acanthoceras sp.                           0
 Achnanthes brevipes                        0
 Achnanthes coarctata                       0
 Achnanthes elongata                        0
 Achnanthes longboardia                     0
...                                       ...
Ulnaria ulna var. claviceps                 0
Ulnaria ulna var. danica                    0
Ulnaria ungeriana                           0
Ulnaria ungeriana terato                    0
terato                                      0

[4056 rows x 1 columns]

In [19]:
cls_instance.process_analysis_across_taxon(gcm_tax, operation='sum')

2

In [20]:
cls_instance.tm_score(attempt)

46.1

In [26]:
line = ">ABC.7 |"
header_parts = line.strip("|").split("|")
len(header_parts)

1

In [8]:
cls_instance.processed_primers.keys()

dict_keys(['rbcL_646F_998R', 'rbcL_708F1_R3_1', 'rbcL_708F1_R3_2', 'rbcL_708F2_R3_1', 'rbcL_708F2_R3_2', 'rbcL_708F3_R3_1', 'rbcL_708F3_R3_2', 'rbcL_708F_DEG_R3_DEG'])

In [47]:
gc = pd.DataFrame(attempt.loc[:, 'gc_matches_sum'])
gc.max()

gc_matches_sum    1
dtype: int64

In [14]:
min_tm_ptaxon = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='min', analysis_name='min_tm')

In [15]:
cls_instance.process_analysis_across_taxon(min_tm_ptaxon, operation='coef_var')

142

In [4]:
mm_sum_three = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='max', analysis_name='three_end_mismatch_sum')
mm_sum_three_all = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='max', analysis_name='full_len_mismatch_sum')

In [5]:
# Mismatching Score
mm_sum_three_sum = cls_instance.process_analysis_across_taxon(mm_sum_three, operation='sum')
mm_sum_three_all_sum = cls_instance.process_analysis_across_taxon(mm_sum_three_all, operation='sum')

In [6]:
cls_instance.get_priming_ratio(mm_sum_three, mm_sum_three_all)

20.0

In [1]:
from src.marker_scoring.metrics_system import *
otl = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/test_data/abc-otl.tsv"
otl_handler = OtlHandler(otl)
otl_handler.import_otl()
total_otl_taxa_count = otl_handler.total_taxa
otl_unique_taxa_set = otl_handler.otl_taxa_set
otl_handler.filter_fasta_for_species_not_in_otl(fasta_file="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/test_data/abc.fasta", otl_taxa_set=otl_unique_taxa_set, overwrite=False)

    taxa
0  taxa1
['> seqa |']
mozaico WARNING: Taxonomy seems to not be present for - > seqa |
mozaico WARNING: Header parsing error - > seqa |
Error details: list index out of range

(1,
 0,
 '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/test_data/test_data_otl_filtered/abc.fasta')

In [ ]:
# Basic usage
folders = ['/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/all_complete_pbs/filtered', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/incomplete_pbs/filtered', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/all_inserts/all_inserts_otl_filtered']
filt
# Basic usage - saves to default location in first folder
output_files = count_sequences_by_taxonomy(folders)

No FASTA files found or no sequences with taxonomy in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/all_complete_pbs/filtered
No FASTA files found or no sequences with taxonomy in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/incomplete_pbs/filtered
Taxonomy sequence counts saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test-minoverlap/all_inserts/all_inserts_otl_filtered/all_inserts_otl_filtered_taxonomy_sequence_counts.tsv

In [2]:
from src.marker_scoring.metrics_system import *

cls_instance = Binding()
cls_instance.get_outputs_taxa_counts("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test")
df = cls_instance.calculate_amplification_success_score("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test")
df

,taxa_in_silico_amplified,taxa_with_pbs,taxa_with_incomplete_pbs,amplification_sucess_percent
rbcL_708F1_R3-1,1262,1537,0,82.11
rbcL_708F2_R3-2,1306,1531,0,85.30
rbcL_708F-DEG_R3-DEG,1341,1524,0,87.99
rbcL_708F1_R3-2,1260,1539,0,81.87
rbcL_646F_998R,1298,1424,0,91.15
rbcL_708F2_R3-1,1308,1529,0,85.55
rbcL_708F3_R3-2,1198,1559,0,76.84
rbcL_708F3_R3-1,1199,1559,0,76.91

In [1]:
from src.marker_scoring.metrics_system import *

tr_instance = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode")
df = tr_instance.get_length_stats_for_amplicon_and_insert()
df

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.

,insert_avg_length,amplicon_min_length,amplicon_max_length,amplicon_avg_length
rbcL_708F1_R3-1,262.95,227,312,311.95
rbcL_708F2_R3-2,262.95,227,312,311.95
rbcL_708F-DEG_R3-DEG,262.95,227,312,311.95
rbcL_708F1_R3-2,262.95,227,312,311.95
rbcL_646F_998R,330.91,227,379,378.91
rbcL_708F2_R3-1,262.95,227,312,311.95
rbcL_708F3_R3-2,262.94,227,312,311.94
rbcL_708F3_R3-1,262.94,227,312,311.94

In [1]:
from src.marker_scoring.metrics_system import *

tr_instance = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode")

tr_instance.multibarcode_output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/multibarcode"
df_div = tr_instance.compute_genetic_divergence_per_taxon()
df_div

results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/incomplete_pbs/filtered/filtered_intersection.

,Species,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Amphora_margalefii_var_lacustris,1.9,2.1,1.9,1.9,1.9,1.9,1.9,1.9
1,Thalassionema_frauenfeldii,6.5,2.7,NaN,6.5,NaN,NaN,NaN,6.5
2,Amphora_berolinensis,2.7,2.7,2.7,4.2,2.7,2.7,2.7,4.2
3,Ditylum_brightwellii,5.3,6.0,5.3,5.3,5.3,5.3,5.3,5.3
4,Halamphora_aponina,0.4,0.3,0.4,0.4,0.4,0.4,0.4,0.4
...,...,...,...,...,...,...,...,...,...
1405,Plagiotropis_sp_,8.4,9.1,9.9,10.3,8.4,14.5,9.9,14.1
1406,Planothidium_cf_subantarcticum,2.3,2.1,2.3,2.3,2.3,2.3,2.3,2.3
1407,Diploneis_kilhamiana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1408,Nitzschia_schefterae,1.1,0.9,1.1,1.1,1.1,1.1,1.1,1.1
1409,Planothidium_frequentissimum,3.0,3.3,3.0,3.0,3.0,3.0,3.0,3.0

In [3]:
tr_instance.get_divergence_score(otl_total_taxa_count=3342)

                 Primer  total_taxa  n_taxa_above_cutoff  divergence_score
0  rbcL_708F_DEG_R3_DEG        3342                  693             20.74
1        rbcL_646F_998R        3342                  686             20.53
2       rbcL_708F1_R3_2        3342                  650             19.45
3       rbcL_708F3_R3_2        3342                  621             18.58
4       rbcL_708F2_R3_2        3342                  682             20.41
5       rbcL_708F2_R3_1        3342                  684             20.47
6       rbcL_708F1_R3_1        3342                  652             19.51
7       rbcL_708F3_R3_1        3342                  622             18.61

In [3]:
tr_instance.nuc_dist_matrix

,Species,rbcL_708F_DEG_R3_DEG,rbcL_646F_998R,rbcL_708F1_R3_2,rbcL_708F3_R3_2,rbcL_708F2_R3_2,rbcL_708F2_R3_1,rbcL_708F1_R3_1,rbcL_708F3_R3_1
0,Amphora_margalefii_var_lacustris,5,7,5,5,5,5,5,5
1,Thalassionema_frauenfeldii,17,9,-,17,-,-,-,17
2,Amphora_berolinensis,7,9,7,11,7,7,7,11
3,Ditylum_brightwellii,14,20,14,14,14,14,14,14
4,Halamphora_aponina,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
1405,Plagiotropis_sp_,22,30,26,27,22,38,26,37
1406,Planothidium_cf_subantarcticum,6,7,6,6,6,6,6,6
1407,Diploneis_kilhamiana,0,0,0,0,0,0,0,0
1408,Nitzschia_schefterae,3,3,3,3,3,3,3,3
1409,Planothidium_frequentissimum,8,11,8,8,8,8,8,8

In [ ]:
import os
import pandas as pd

def calculate_missing_scientific_names(folder_path):
    results = []

    for file_name in os.listdir(folder_path):
        if file_name.endswith(".tsv"):
            file_path = os.path.join(folder_path, file_name)

            try:
                df = pd.read_csv(file_path, sep='\t')

                if 'scientificName' in df.columns:
                    total_entries = len(df)
                    missing_entries = (df['scientificName'] == '-').sum()

                    percentage_missing = (missing_entries / total_entries) * 100 if total_entries > 0 else 0

                    results.append({
                        'File Name': file_name,
                        'Percentage Missing': percentage_missing
                    })
                else:
                    results.append({
                        'File Name': file_name,
                        'Percentage Missing': 'Column not found'
                    })
            except Exception as e:
                results.append({
                    'File Name': file_name,
                    'Percentage Missing': f'Error: {e}'
                })

    return pd.DataFrame(results)

In [11]:
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi"
summary_df = calculate_missing_scientific_names(folder_path)
print(summary_df)

                               File Name  Percentage Missing
0    Sweden_taxonlist_bmi_harmonized.tsv            3.783469
1   Austria_taxonlist_bmi_harmonized.tsv            8.630195
2   Poland_taxonlists_bmi_harmonized.tsv            4.891304
3     Czech_taxonlist_bmi_harmonized.tsv            1.738281
4   Germany_taxonlist_bmi_harmonized.tsv            3.828829
5  Portugal_taxonlist_bmi_harmonized.tsv            2.941176
6   Finland_taxonlist_bmi_harmonized.tsv            2.727273
7   France_taxonlists_bmi_harmonized.tsv            8.720930

In [12]:
summary_df['Percentage Missing'].mean()

np.float64(4.657682260978175)

In [13]:
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia"
summary_df = calculate_missing_scientific_names(folder_path)
print(summary_df)

                                   File Name  Percentage Missing
0   Germany_taxonlist_diatoms_harmonized.tsv            1.175174
1   Ireland_taxonlist_diatoms_harmonized.tsv            2.561118
2     Czech_taxonlist_diatoms_harmonized.tsv            3.819604
3   Finland_taxonlist_diatoms_harmonized.tsv            2.500000
4    france_taxonlist_diatoms_harmonized.tsv            0.610632
5    poland_taxonlitst_diatom_harmonized.tsv            0.000000
6   Austria_taxonlist_diatoms_harmonized.tsv            2.014099
7    Sweden_taxonlist_diatoms_harmonized.tsv            2.056807
8  Portugal_taxonlist_diatoms_harmonized.tsv            1.298701

In [14]:
summary_df['Percentage Missing'].mean()

np.float64(1.7817928308521056)