In [2]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.data

FileNotFoundError: Input file does not exist in the directory.

In [ ]:
pre_processed = dt_class.pre_process_harmonized_fasta()
pre_processed

In [ ]:
import pandas as pd
dt_class.data = pd.concat(
            [dt_class.data, dt_class.data["taxa_info"].str.split("|", expand=True)], axis=1
        )

In [ ]:
dt_class.data.columns = [
            "seq_id",
            "sequence",
            "length",
            "all_taxa_info",
            "original_taxa_info",
            "scientificName",
            "rank",
            "kingdom",
            "phylum",
            "class",
            "order",
            "family",
            "genus"
        ]

In [ ]:
dt_class.data[dt_class.data['rank'] == 'CLASS']

In [ ]:
dt_class.data['rank'] = dt_class.data['rank'].str.lower()

In [ ]:
non_interest_ranks = ['kingdom', 'phylum', 'class', 'order']
dt_class.data = dt_class.data = dt_class.data[~dt_class.data['rank'].isin(non_interest_ranks)]

In [ ]:
dt_class.data[dt_class.data['rank'] == 'class']

In [ ]:
import numpy as np
dt_class.data = dt_class.data.replace("-", np.nan)

In [ ]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

In [ ]:
dt_class.data = dt_class.data.dropna(subset=["scientificName"], how="all")

In [ ]:
# Check entries with missing values for 'scientificName'
dt_class.data[dt_class.data['scientificName'].isnull()]

In [ ]:
species_variants = ['species', 'form', 'variety', 'subspecies']
dt_class.data['species'] = np.where(
    dt_class.data['rank'].str.lower().isin(species_variants),
    dt_class.data['scientificName'],  # Assign scientificName if condition is met
    np.nan  # Assign NaN otherwise
)
dt_class.data['species'] = dt_class.data['species'].str.split(' ').str[0] + ' ' + dt_class.data['species'].str.split(' ').str[1]

In [ ]:
dt_class.data

In [ ]:
otl_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

In [ ]:
from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl_path)

otl = otl_handler.import_otl()
otl

In [ ]:
tax = all_comp['taxa_info']
unq_taxa = tax.unique()
len(unq_taxa)

In [ ]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "../data/test_data/fasta_example_file.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
dt_class.get_sequences()
dt_class.data

In [ ]:
dt_class.get_mapping_between_seq_id_taxonomy()

In [ ]:
from src.reference_database.sequence_import import CustomFastaImport

fasta = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
dt_class = CustomFastaImport(fasta)
dt_class.read_fasta(fasta)
diat_data_df = dt_class.data
diat_data_df.to_csv("try.csv")

In [ ]:
dt_class.get_sequence_ids()

In [ ]:
dt_class.get_sequence_lengths()

-----------

In [ ]:
from src.reference_database.sequence_import import *

In [ ]:
fasta= '../data/input_data/diat-barcode.fasta'
cls = CustomFastaImport(fasta)
cls.read_fasta(fasta)

In [ ]:
dt_class.lineage_file

In [ ]:
dt_class.lineage_file.columns.to_list()

In [ ]:
from src.reference_database.db_curation import *
crabs = CrabsScriptGenerator()
json_file = "../src/reference_database/assign_tax_parameters.json"
crabs.run_assign_tax_command(json_file)

## Test with Trial example
Issue: Fasta is not formatted as it should. Should not have tax id separated by ID -> affecting how PGA reads sequences

In [ ]:
def clean_fasta_headers(input_file, output_file):
    unique_tax = set()
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        for line in infile:
            if line.startswith('>'):
                header = line.split(";", 2)
                seq_id = header[0].strip()
                tax_id = header[1].strip()
                unique_tax.add(tax_id)
                formatted_header = seq_id + " | " + tax_id + "\n"
                # print(formatted_header)
                outfile.write(formatted_header)
            else:
                outfile.write(line)

        print(len(unique_tax))

clean_fasta_headers("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference.fasta", "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta")

In [ ]:
from src.in_silico_analysis.amplification import InSilicoAmplification
data = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-taxa.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"
run_name = "diat-barcode-testimport"
cutadapt = InSilicoAmplification(data, run_name=run_name)
cutadapt.run_in_silico_analysis(primer_table=primer_table)

### MultiBarcodeTools

In [ ]:
from src.marker_scoring.scoring_utils import create_MultiBarcodeTools_input

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/insert/filtered"
output_dir = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test/diat-multibarcode-insert.tsv"
create_MultiBarcodeTools_input(insert_path, output_dir)

#### With joined incomplete pbs

In [ ]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

In [ ]:
from src.marker_scoring.metrics_system import *

trait.get_taxonomic_resolution(otl_total_taxa_count=1500)

In [ ]:
trait.load_nucleotide_distance()

#### without joined incomplete PBS

In [ ]:
from src.marker_scoring.metrics_system import *

trait = TraitsAndResolution(results_folder="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-test")
output_str = trait.run_multibarcode_pipeline()
trait.parse_multibarcode_output(output_str)

In [ ]:
from src.reference_database.sequence_import import CustomFastaImport

insert_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode/all_inserts/rbcL_646F_998R.fasta"
cls = CustomFastaImport()
cls.read_fasta(insert_path)

### Binding

In [1]:
from src.marker_scoring.metrics_system import MetricsSystemExecutor

output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/old-diatoms-dereped"
otl1 = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Portugal_taxonlist_diatoms_harmonized.tsv"

cls = MetricsSystemExecutor(results_folder=output_folder, otl=otl1, primer_table='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat-barcode-primers.tsv')

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/old-diatoms-dereped/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/old-diatoms-dereped/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/old-diatoms-dereped/incomplete_pbs/filtered.

In [ ]:
cls.sort_otl_level_results()

In [ ]:
abc = cls.get_reference_database_quality()
abc

In [ ]:
primer_pbs, gc = cls.get_primer_pbs_analysis()

In [ ]:
primerex = primer_pbs['rbcL_646F_998R']

In [ ]:
primerex

In [ ]:
primerex.to_csv("primerex.csv")

In [ ]:
from src.marker_scoring.metrics_system import *

bind = Binding(otl=cls.otl)
result_full_len = bind.process_analysis_per_taxon(primerex, 'sum', 'full_len_mismatch_sum')

In [ ]:
result_three_end = bind.process_analysis_per_taxon(primerex, 'max', 'three_end_mismatch_sum')

In [ ]:
# GC Match Analysis
bind.get_total_gc_matches(primerex)
tax_lev_gc = bind.process_analysis_per_taxon(primerex, operation="min", analysis_name="gc_matches_score")
# Temperature Melting (Tm) Analysis
tax_lev_min_tm = bind.process_analysis_per_taxon(primerex, operation="min", analysis_name="min_tm")

In [2]:
ref_qual = cls.comprehensive_primer_analysis(output_folder, save_otl_level_results=True)

mozaiko INFO: Retrieving primer-PBS statistics.
mozaiko INFO: Retriving information on the Reference Database Quality.
mozaiko INFO: Calculating the number of barcodes per FASTA.
mozaiko INFO: Calculating the number of barcodes per FASTA.

In [12]:
ref_qual

,barcoded_taxa_one_plus,ratio_barcoded_taxa,mismatch_score,priming_ratio,gc_matches_across_taxon,min_tm_cv,tm_score
primer,,,,,,,
rbcL_708F_DEG_R3_DEG,32.74,0.36,0.68,0.10,0.0,0.66,17.73
rbcL_646F_998R,30.34,0.35,0.52,0.58,0.0,2.20,45.59

In [3]:
ref_qual

,barcoded_taxa_one_plus,ratio_barcoded_taxa,mismatch_score,priming_ratio_sum,gc_matches_across_taxon,min_tm_cv,tm_score
primer,,,,,,,
rbcL_708F_DEG_R3_DEG,32.74,0.36,0.68,10.23,0.0,0.66,17.73
rbcL_646F_998R,30.34,0.35,0.52,41.92,0.0,2.20,45.59

In [7]:
len(ref_qual[~ref_qual['full_len_mismatch_sum'].isnull()])

200

In [5]:
tax_lev_max_ms_full_len = cls.process_analysis_per_taxon(
    primer_pbs['rbcL_646F_998R'],
    operation="max",
    analysis_name="full_len_mismatch_sum",
)

AttributeError: 'MetricsSystemExecutor' object has no attribute 'process_analysis_per_taxon'

In [ ]:
cls.get_traits_and_resolution()

In [ ]:
metrics_df = cls.join_analysis_results()
metrics_df

In [ ]:
ranked_df = cls.rank_primers(metrics_df, save_intermediate_ranks=False)
ranked_df

##### ----------------------------------- END OF BINDING ---------------------------------------------

In [ ]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/previous_software/reference-taxa.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/12S"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

## Mismatches

In [ ]:
from src.marker_scoring.metrics_system import *
from src.marker_scoring.scoring_utils import *

amp_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/amplicon/filtered"
insert_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/output_data/diat-barcode-harmonized-consensus/insert/filtered"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/data/input_data/diat-barcode-primers.tsv"


cls_instance = Binding()
analysis_results, gc = cls_instance.primer_pbs_analysis(amp_folder, insert_folder, primer_table)

In [ ]:
gc

In [ ]:
otl = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl)
otl_handler.import_otl()
total_otl_taxa_count = otl_handler.total_taxa
otl_unique_taxa_set = otl_handler.otl_taxa_set

In [ ]:
process = cls_instance.iterate_over_primer_pbs_df(analysis_results, add_otl_taxa=False, otl_taxa_set=otl_unique_taxa_set)

In [ ]:
attempt = cls_instance.get_primer_df('rbcL_708F_DEG_R3_DEG')

In [ ]:
primer_pbs_df, primer_gc_df = cls_instance.primer_pbs_analysis(
    "../data/test_data/amplicon-test",
    "../data/test_data/insert-test",
    "../data/test_data/test_primer_table.tsv",
    save_results=False,
)

In [ ]:
primer_pbs_df

In [ ]:
gcm = cls_instance.get_total_gc_matches(attempt)
gcm['gc_matches_score'].max()

In [ ]:
gcm_tax = cls_instance.process_analysis_per_taxon(primer_df=attempt, operation='min', analysis_name='gc_matches_score')
gcm_tax

### -------------------------- HERE ---------------------

In [ ]:
from src.marker_scoring.metrics_system import *

otl = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Portugal_taxonlist_diatoms_harmonized.tsv'
tandres = TraitsAndResolution(otl, results_folder='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed')
tandres.multibarcode_output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/multibarcode"
nuc_mat = tandres.load_nucleotide_distance()

In [ ]:
nuc_mat

In [ ]:
tandres.insert_folder_path

In [ ]:
tandres.get_length_stats_for_amplicon_and_insert('/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/insert/filtered', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-fixed/amplicon/filtered')

In [ ]:
divergence2 = tandres.compute_genetic_divergence_per_taxon(save_results=True)

In [ ]:
len(divergence2[divergence2['rbcL_708F3_R3_1'] > 2.0])

In [ ]:
divergence = tandres.get_divergence_score()
divergence

In [ ]:
abc = nuc_mat[(~nuc_mat['rbcL_646F_998R'].isnull()) & (nuc_mat['genus'] == 'Achnanthes')]
abc

In [ ]:
# Transform columns that are not 'input_taxa', family', genus', 'species', 'rank' to numeric
str_columns = ['input_taxa', 'family', 'genus', 'species', 'rank']
numeric_columns = [col for col in nuc_mat.columns if col not in str_columns]
nuc_mat[numeric_columns] = nuc_mat[numeric_columns].apply(pd.to_numeric, errors='coerce')
nuc_mat.dtypes

In [ ]:
abc2 = nuc_mat[(~nuc_mat['rbcL_646F_998R'].isnull()) & (nuc_mat['genus'] == 'Achnanthes')]
abc2

In [ ]:
result = fill_hierarchical_values(abc2, 'min')
result

In [ ]:
tandres.compute_genetic_divergence_per_taxon()

In [ ]:
hyal = nuc_mat.loc[1]
hyal.items()

In [ ]:
nuc_mat_species = nuc_mat['Species']
nuc_mat_species.to_csv("nuc_mat_species.csv")

In [ ]:
import pandas as pd
test_multibarcode_600k = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/bmi_600k_multibarcodetest.tsv", sep="\t", header=None)
new_column_names = ['seq_id', 'primer', 'scientific_name', 'kingdom', 'phylum', 'class', 'order', 'family','seq']
test_multibarcode_600k.columns = new_column_names[:len(test_multibarcode_600k.columns)]
test_multibarcode_600k

In [ ]:
unique_families = test_multibarcode_600k.groupby('family').size()
unique_families.sort_values(ascending=False)

In [ ]:
unique_primers = test_multibarcode_600k.groupby('primer').size()
unique_primers.sort_values(ascending=False)

### Checking largest primer

In [ ]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
largest_primer = largest_primer[['seq_id', 'primer', 'scientific_name', 'seq']]
largest_primer
# largest_primer.to_csv("fwh.tsv", sep="\t", index=False)

#### By family

In [ ]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
unique_fam_prim = largest_primer.groupby('family').size()
unique_fam_prim.sort_values(ascending=False)

In [ ]:
primer_subset = test_multibarcode_600k[test_multibarcode_600k[1] == 'COI_FwhF2_FwhR2n']
test_subset = primer_subset[test_multibarcode_600k[7] == 'Cecidomyiidae']
test_subset = test_subset[[0, 1, 2, 8]]
test_subset
test_subset.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/filtered/multibarcode/cecidomyiidae_fwh.tsv", sep='\t', index=False)

#### By order

In [ ]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
unique_fam_prim = largest_primer.groupby('order').size()
unique_fam_prim.sort_values(ascending=False)

In [ ]:
largest_primer = test_multibarcode_600k[test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n']
largest_prim_order =  largest_primer[largest_primer['order'] == 'Diptera']
largest_prim_order = largest_prim_order[['seq_id', 'primer', 'scientific_name', 'seq', ]]
largest_prim_order

In [ ]:
largest_prim_order.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/mb-order-diptera/diptera-fwh.tsv", sep='\t', index=False, header=None)

In [ ]:
with open("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/filtered/multibarcode/fwh_diptera.fasta", "w") as fasta_file:
    for _, row in largest_prim_order.iterrows():
        fasta_file.write(f">{row['seq_id']}|{row['scientific_name']}\n{row['seq']}\n")

##### Order, clustered

In [ ]:
diptera_clustered = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/multibarcode/mb-order-diptera/diptera_clustered.csv", sep=",")
diptera_clustered

#### Checking one-seq distribution per family

In [ ]:
def check_unique_families(test_multibarcode_600k, primer_list):
    for primer in primer_list:
        primer_df = test_multibarcode_600k[test_multibarcode_600k['primer'] == primer]

        unique_fam_prim = primer_df.groupby('family').size()
        fams_one_seq = unique_fam_prim[unique_fam_prim < 2].index.tolist()

        filtered_check_single_orders = test_multibarcode_600k[
            (test_multibarcode_600k['primer'] == primer) &
            (test_multibarcode_600k['family'].isin(fams_one_seq))
        ]

        print(f"Number of orders with families of one sequence for primer '{primer}':", filtered_check_single_orders['order'].nunique())

        # Step 6: Iterate over unique 'order' values to check for families not in the selected list
        for order_of_uniq_families in filtered_check_single_orders['order'].unique():
            order_rows = primer_df[primer_df['order'] == order_of_uniq_families]
            families_not_in_list = order_rows[~order_rows['family'].isin(fams_one_seq)]

            if not families_not_in_list.empty:
                print(f"    Order '{order_of_uniq_families}' has entries in 'family' that have more than one sequence.")

primer_list = [
    'COI_BF2_BR2',
    'COI_BF3_BR2',
    'COI_FwhF2_EPTDr2n',
    'COI_FwhF2_FwhR2n',
    'COI_MG2-LCO1490_MG2-univR',
    'COI_MICOIntF_HCO2198',
    'COI_fwhF2_Fol-degen-rev',
    'COI_mICOIintF_jgHCO2198'
]

check_unique_families(test_multibarcode_600k, primer_list)

In [ ]:
fams_one_seq = unique_fam_prim[unique_fam_prim < 2].index.tolist()
print(fams_one_seq)

In [ ]:
filtered_check_single_orders = test_multibarcode_600k[(test_multibarcode_600k['primer'] == 'COI_FwhF2_FwhR2n') & (test_multibarcode_600k['family'].isin(fams_one_seq))]
filtered_check_single_orders
#filtered_check_single_orders['order'].nunique()

In [ ]:
for order_of_uniq_families in filtered_check_single_orders['order'].unique():
    order_rows = filtered_check_single_orders[filtered_check_single_orders['order'] == order_of_uniq_families]
    families_not_in_list = order_rows[~order_rows['family'].isin(fams_one_seq)]

    if not families_not_in_list.empty:
        print(f"Order '{order_of_uniq_families}' has entries in 'family' that only have on sequence:")
        print(families_not_in_list)

In [ ]:
# group by primer, family
family_primer_counts = test_multibarcode_600k.groupby([1, 7]).size().reset_index(name='count')
min_max_per_primer = family_primer_counts.groupby(1)['count'].agg(['min', 'max'])

print(min_max_per_primer)

In [ ]:
# Total: 3703067
import pandas as pd
file_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/external_scripts/test_order.tsv"
df = pd.read_csv(file_path, sep='\t')

def get_analysis_order_of_magnitude(df):
    levels = {
        "phylum": 4,
        "class": 5,
        "order": 6,
        "family": 7
    }

    for level, col in levels.items():
        grouped_counts = df.groupby(df.columns[col]).size()

        min_count = grouped_counts.min()
        max_count = grouped_counts.max()
        mean_count = grouped_counts.mean()

        print(f"\nStatistics for {level} level:")
        print(f"  Unique groups: {len(grouped_counts)}")
        print(f"  Min entries per file: {min_count}")
        print(f"  Max entries per file: {max_count}")

get_analysis_order_of_magnitude(df)

In [29]:
import os
import pandas as pd

def filter_tsv_files(folder_path):
    # List all TSV files in the folder
    for file_name in os.listdir(folder_path):
        if file_name.endswith(".tsv"):
            file_path = os.path.join(folder_path, file_name)

            # Read the TSV file
            df = pd.read_csv(file_path, sep='\t')

            # Check if 'phylum' column exists
            if 'phylum' in df.columns:
                # Filter out unwanted phyla
                df = df[~df['phylum'].isin(['Rhodophyta', 'Chordata', 'Tracheophyta'])]

                # Save the cleaned file (overwrite or create new file)
                output_path = os.path.join(folder_path, f"filtered_{file_name}")
                df.to_csv(output_path, sep='\t', index=False)
                print(f"Processed: {file_name} -> Saved as {output_path}")
            else:
                print(f"Skipping {file_name}: No 'phylum' column found.")

# Example usage
folder_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi"
filter_tsv_files(folder_path)

Processed: Poland_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Poland_taxonlist_bmi_harmonized.tsv
Processed: Sweden_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Sweden_taxonlist_bmi_harmonized.tsv
Processed: Austria_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Austria_taxonlist_bmi_harmonized.tsv
Processed: Czech_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Czech_taxonlist_bmi_harmonized.tsv
Processed: Germany_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Germany_taxonlist_bmi_harmonized.tsv
Processed: Portugal_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Portugal_taxonlist_bmi_harmonized.tsv
Processed: Finland_taxonlist_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_Finland_taxonlist_bmi_harmonized.tsv
Processed: France_taxonlists_bmi_harmonized.tsv -> Saved as /home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_France_taxonlists_bmi_harmonized.tsv

In [ ]:
from src.marker_scoring.metrics_system import ReferenceDatabaseQuality

refb = ReferenceDatabaseQuality(all_inserts_path='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat.barcode_earlier_results/insert/filtered', otl='/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv')
barcodes_per_entry = refb.calculate_number_of_barcodes_per_fasta_entry()
barcodes_per_entry
# refb.taxa_hierarchy
#refb.calculate_number_of_barcodes_per_otl_taxonomy(barcodes_per_entry, refb.taxa_hierarchy)

## Joining multibarcode results and checking missing entries

In [ ]:
import pandas as pd
merged = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/mulitbarcode/merged_matrices.csv", sep='\t')
merged

In [ ]:
merged_families = merged['SourceFolder'].unique()
len(merged_families)

In [ ]:
abc = unique_fam_prim
# Retrieve names of families
lista = abc.index.to_list()
# save the list in a file
with open('families.txt', 'w') as filehandle:
    for listitem in lista:
        filehandle.write('%s\n' % listitem)

In [ ]:
# CHheck which families are missing from 'SourceFolder' compared to a file
file = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/families.txt'
merged_families = merged['SourceFolder'].unique()

with open(file, 'r') as f:
    source_families = f.read().splitlines()

missing_families = [fam for fam in source_families if fam not in merged_families]
missing_families

In [ ]:
len(missing_families)

In [ ]:
# Count unqie values in 'SourceFolder' column
merged[['SourceFolder']].nunique()

## Check 'rc' removal

In [ ]:
test_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/mulitbarcode/COI_BF3_BR2"

from src.marker_scoring.scoring_utils import remove_rc_suffix_from_fasta_files

remove_rc_suffix_from_fasta_files(test_path)

In [ ]:
from src.marker_scoring.metrics_system import Binding

results_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-additional-primers"
bd = Binding(otl='/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_phyl/Austria_taxonlist_bmi_harmonized.tsv')
bd.get_outputs_taxa_counts(results_folder)

In [ ]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl-just-amplification"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

In [ ]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

In [ ]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

In [ ]:
from src.marker_scoring.metrics_system import *

insert_folder_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered"
incomplete_pbs_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/incomplete_pbs/filtered/filtered_intersection"
otl = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_phyl/Germany_taxonlist_bmi_harmonized.tsv"

otl_handler = OtlHandler(otl)
otl_handler.import_otl()
total_otl_taxa_count = otl_handler.total_taxa
otl_unique_taxa_set = otl_handler.otl_taxa_set


with tempfile.TemporaryDirectory() as temp_dir:
    all_inserts_path = os.path.join(temp_dir, "all_inserts")
    os.makedirs(all_inserts_path, exist_ok=True)

    for folder in [insert_folder_path, incomplete_pbs_path]:
        if os.path.exists(folder):
            for file in os.listdir(folder):
                src = os.path.join(folder, file)
                dest = os.path.join(all_inserts_path, file)

                if os.path.isfile(src):
                    shutil.copy(src, dest)

    red_bd_qual = ReferenceDatabaseQuality(
        otl=otl, all_inserts_path=all_inserts_path
    )
    # reference_db_quality = red_bd_qual.barcoded_taxa_ratio(
    #     total_taxa_count=total_otl_taxa_count
    # )

    barcoded_taxa_five_plus = red_bd_qual.calculate_percentage_of_taxa_w_x_barcodes(
    total_otl_taxa_count, barcode_threshold=5
)
    barcoded_taxa_one_plus = red_bd_qual.calculate_percentage_of_taxa_w_x_barcodes(
    total_otl_taxa_count, barcode_threshold=1
)

In [ ]:
barcoded_taxa_five_plus

In [ ]:
barcoded_taxa_one_plus

In [ ]:
# OG
reference_db_quality

In [ ]:
from pathlib import Path

def extract_third_element_from_fasta(fasta_path):
    third_elements = []
    with open(fasta_path, 'r') as file:
        for line in file:
            if line.startswith('>'):
                parts = line[1:].strip().split('|')
                if len(parts) >= 3:
                    third_elements.append(parts[2])
    return third_elements


fasta_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered/COI_FwhF2_FwhR2n.fasta"
third_elements_list = extract_third_element_from_fasta(fasta_file)
print(third_elements_list)

In [ ]:
COI_FwhF2_FwhR2n_taxa =  extract_third_element_from_fasta("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered/COI_FwhF2_FwhR2n.fasta")
COI_FwhF2_EPTDr2n_taxa =  extract_third_element_from_fasta("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered/COI_FwhF2_EPTDr2n.fasta")
COI_BF2_BR2_taxa =  extract_third_element_from_fasta("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered/COI_BF2_BR2.fasta")
COI_BF3_BR2_taxa = extract_third_element_from_fasta("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/insert/filtered/COI_BF3_BR2.fasta")

In [ ]:
type(COI_BF3_BR2_taxa)

In [ ]:
unique_german_scientific_names = otl_handler.otl['scientificName'].unique()

In [ ]:
len(unique_german_scientific_names)

In [ ]:
common_COI_FwhF2_FwhR2n_taxa= set(COI_FwhF2_FwhR2n_taxa) & set(unique_german_scientific_names)
common_COI_FwhF2_EPTDr2n_taxa = set(COI_FwhF2_EPTDr2n_taxa) & set(unique_german_scientific_names)
common_COI_BF2_BR2_taxa = set(COI_BF2_BR2_taxa) & set(unique_german_scientific_names)
common_COI_BF3_BR2_taxa = set(COI_BF3_BR2_taxa) & set(unique_german_scientific_names)

In [ ]:
print("COI_FwhF2_FwhR2n taxa in OTL:", len(common_COI_FwhF2_FwhR2n_taxa))
print("COI_FwhF2_EPTDr2n taxa in OTL:", len(common_COI_FwhF2_EPTDr2n_taxa))
print("COI_BF2_BR2 taxa in OTL:", len(common_COI_BF2_BR2_taxa))
print("COI_BF3_BR2 taxa in OTL:", len(common_COI_BF3_BR2_taxa))

In [ ]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification()

insil.remove_intersection_sequences(input_path="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/test_data/test_filter_intersection/test_input_path",
                                                    filter_path="/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/test_data/test_filter_intersection/test_filter_path")

In [ ]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat_barcode_hrm_dreped_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-NEWRUN"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

In [1]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/DIA/diat_barcode_hrm_dreped_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diatoms-NEWRUN"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

mozaiko INFO: Number of sequences in original database: 7297
mozaiko INFO: Percentage calculations completed successfully.

,all_complete_pbs,amplicon,incomplete_pbs,insert,input_B,all_complete_pbs-input_ABC,incomplete_pbs-input_AC,insert-input_A,percentage_of_sequences_with_PBS,percentage_of_amplified_sequences_with_PBS
primer_name,,,,,,,,,,
rbcL_646F_998R,3748,3572,3728,3572,17,3745,3728,3571,95.81,99.53
rbcL_708F-DEG_R3-DEG,4043,3768,4016,3768,23,4039,4016,3767,93.84,99.39
rbcL_rbcL_39F_404R,2617,1930,2568,1930,47,2615,2568,1930,75.60,97.62
rbcL_rbcL_404F_646R,3894,3716,3869,3716,19,3888,3869,3714,96.01,99.49
rbcL_rbcL_998F_1229R,3123,3064,3097,3064,22,3119,3097,3064,98.94,99.29

In [3]:
from src.marker_scoring.scoring_utils import sequence_count_tracking

og_db = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_processed.fasta"
analysis_fold = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy"
sequence_count_tracking(og_db, analysis_fold, save_results=False)

mozaiko INFO: Number of sequences in original database: 623311
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/insert/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/insert/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/insert/input_A/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/insert/input_A/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/input_B/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/input_B/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/all_complete_pbs/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/all_complete_pbs/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/all_complete_pbs/input_ABC/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/all_complete_pbs/input_ABC/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/incomplete_pbs/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/incomplete_pbs/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko ERROR: Error processing file /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/incomplete_pbs/input_AC/COI_JgLCO1490_jgHCO2198.fasta: Command '['grep', '-c', '^>', '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN copy/incomplete_pbs/input_AC/COI_JgLCO1490_jgHCO2198.fasta']' returned non-zero exit status 1.
mozaiko INFO: Percentage calculations completed successfully.

,all_complete_pbs,amplicon,incomplete_pbs,insert,input_B,all_complete_pbs-input_ABC,incomplete_pbs-input_AC,insert-input_A,percentage_of_sequences_with_PBS,percentage_of_amplified_sequences_with_PBS
primer_name,,,,,,,,,,
COI_BF2_BR2,500104.0,5646.0,499640.0,5642.0,458.0,500045.0,499587.0,5638.0,1.22,92.49
COI_BF3_BR2,500136.0,5692.0,499672.0,5688.0,458.0,500076.0,499618.0,5685.0,1.23,92.54
COI_FwhF2_EPTDr2n,587194.0,381907.0,382051.0,381907.0,205076.0,587127.0,382051.0,381882.0,99.97,65.06
COI_FwhF2_FwhR2n,617718.0,599206.0,608757.0,599206.0,8894.0,617639.0,608745.0,599163.0,98.45,98.54
COI_JgLCO1490_jgHCO2198,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
COI_MG2-LCO1490_MG2-univR,234296.0,6148.0,234061.0,6148.0,233.0,234129.0,233896.0,6147.0,2.72,96.35
COI_MICOIntF_HCO2198,493383.0,2007.0,492145.0,2007.0,1234.0,493328.0,492094.0,2004.0,0.66,61.89
COI_fwhF2_Fol-degen-rev,493951.0,2727.0,493329.0,2727.0,618.0,493896.0,493278.0,2723.0,0.68,81.50
COI_mICOIintF_jgHCO2198,493629.0,2679.0,492969.0,2679.0,656.0,493574.0,492918.0,2675.0,0.67,80.31

In [26]:
import os

def check_taxon_in_fasta_headers(
    base_dir,
    target_folders,
    fasta_filenames,
    taxon_to_find
):
    found_matches = []

    for folder in target_folders:
        folder_path = os.path.join(base_dir, folder)
        # print(f"Checking folder: {folder_path}")
        for fasta_file in fasta_filenames:
            path = os.path.join(folder_path, fasta_file)
            # print(f"Checking file: {path}")
            if not os.path.isfile(path):
                continue

            with open(path, 'r') as f:
                for line in f:
                    if line.startswith('>'):
                        parts = line.strip().lstrip('>').split('|')
                        # print(parts[2].strip())
                        if len(parts) >= 3 and parts[2].strip() == taxon_to_find:
                            found_matches.append((path, line.strip()))
                            break  # One match per file is enough for reporting

    if found_matches:
        print(f"\n Found '{taxon_to_find}' in the following FASTA files:")
        for filepath, header in found_matches:
            print(f"- {filepath}")
    else:
        print(f"\n Taxon '{taxon_to_find}' not found in specified FASTA files.")


base_dir = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN"
target_folders = [
    "all_complete_pbs", "all_complete_pbs/filtered",
    "amplicon", "incomplete_pbs", "incomplete_pbs/filtered",
    "insert", "insert/filtered", "input_B"
]

fasta_filenames = ["COI_BF3_BR2.fasta", "COI_FwhF2_FwhR2n.fasta"]
taxon_to_search = "Abacarus oplismeni"

check_taxon_in_fasta_headers(base_dir, target_folders, fasta_filenames, taxon_to_search)

 Found 'Abacarus oplismeni' in the following FASTA files:
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/all_complete_pbs/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/all_complete_pbs/filtered/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/amplicon/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/incomplete_pbs/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/incomplete_pbs/filtered/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/insert/COI_FwhF2_FwhR2n.fasta
- /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/insert/filtered/COI_FwhF2_FwhR2n.fasta

In [1]:
from src.marker_scoring.metrics_system import MetricsSystemExecutor

output_folder = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN"
otl1 = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_phyl/ref-db/referencedatabase_taxonlist_bmi_harmonized.tsv"
primer_table='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi-primers.tsv'

cls = MetricsSystemExecutor(results_folder=output_folder, otl=otl1, primer_table='/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi-primers.tsv')

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/incomplete_pbs/filtered.

In [6]:
# Intake data
from src.reference_database.sequence_import import *

database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN/incomplete_pbs/filtered/COI_BF3_BR2.fasta"

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta(database_file, check_taxid=False)
data = custom_fasta_import.data
data.head()

,seq_id,sequence,length,taxa_info
0,AAGRE003-21,AATAAATAATATAAGTTTTTGATTACTACCCCCCTCATTAACCCTT...,418,Atylotus agrestis|Atylotus agrestis Wiedemann ...
1,ABEE094-17,AATAAATAATATTAGATTTTGATTATTACCACCATCATTAATCTTA...,418,Dioxys cinctus|Dioxys cinctus Jurine 1807|spec...
2,ABEE097-17,AATAAATAATATAAGATTTTGGCTACTCCCCCCTTCAATTCTAATT...,418,Andrena pilipes|Andrena pilipes Fabricius 1781...
3,ABEE104-17,AATAAATAATATAAGATTCTGATTACTAATTCCTTCTTTATTTTTA...,418,Halictus quadricinctus|Halictus quadricinctus ...
4,ABEE111-17,AATAAATAATATGAGATTCTGATTATTACCCCCATCATTAATTATA...,418,Hylaeus sinuatus|Hylaeus sinuatus Schenck 1853...

In [7]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta_database()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,AAGRE003-21,AATAAATAATATAAGTTTTTGATTACTACCCCCCTCATTAACCCTT...,418,Atylotus agrestis|Atylotus agrestis Wiedemann ...,Atylotus agrestis,Atylotus agrestis Wiedemann 1828,species,Animalia,Arthropoda,Insecta,Diptera,Tabanidae,Atylotus,Atylotus agrestis
1,ABEE094-17,AATAAATAATATTAGATTTTGATTATTACCACCATCATTAATCTTA...,418,Dioxys cinctus|Dioxys cinctus Jurine 1807|spec...,Dioxys cinctus,Dioxys cinctus Jurine 1807,species,Animalia,Arthropoda,Insecta,Hymenoptera,Megachilidae,Dioxys,Dioxys cinctus
2,ABEE097-17,AATAAATAATATAAGATTTTGGCTACTCCCCCCTTCAATTCTAATT...,418,Andrena pilipes|Andrena pilipes Fabricius 1781...,Andrena pilipes,Andrena pilipes Fabricius 1781,species,Animalia,Arthropoda,Insecta,Hymenoptera,Andrenidae,Andrena,Andrena pilipes
3,ABEE104-17,AATAAATAATATAAGATTCTGATTACTAATTCCTTCTTTATTTTTA...,418,Halictus quadricinctus|Halictus quadricinctus ...,Halictus quadricinctus,Halictus quadricinctus Fabricius 1776,species,Animalia,Arthropoda,Insecta,Hymenoptera,Halictidae,Halictus,Halictus quadricinctus
4,ABEE111-17,AATAAATAATATGAGATTCTGATTATTACCCCCATCATTAATTATA...,418,Hylaeus sinuatus|Hylaeus sinuatus Schenck 1853...,Hylaeus sinuatus,Hylaeus sinuatus Schenck 1853,species,Animalia,Arthropoda,Insecta,Hymenoptera,Colletidae,Hylaeus,Hylaeus sinuatus

In [8]:
mask = processed_data['genus'].str.contains('Dysdera', case=False, na=False)
Dysdera = processed_data[mask]

In [9]:
Dysdera

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
3806,NFN001-13,AATGAATAATTTAAGTTTTTGGTTGTTGCCTCCTTCTTTAATTTTA...,418,Dysdera crocata|Dysdera crocata C.L.Koch 1838|...,Dysdera crocata,Dysdera crocata C.L.Koch 1838,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera crocata
16146,ARONT178-09,AATGAATAATTTAAGTTTTTGGTTGTTGCCTCCTTCTTTAATTTTA...,418,Dysdera crocata|Dysdera crocata C.L.Koch 1838|...,Dysdera crocata,Dysdera crocata C.L.Koch 1838,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera crocata
341924,KROK062-19,TATAAATAATTTAAGCTTTTGACTTCTACCCCCATCGTTAGTGTTA...,418,Dysdera adriatica|Dysdera adriatica Kulczynski...,Dysdera adriatica,Dysdera adriatica Kulczynski 1897,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera adriatica
341929,KROK064-19,TATAAATAATTTAAGCTTTTGACTTCTACCCCCATCGTTAGTGTTA...,418,Dysdera adriatica|Dysdera adriatica Kulczynski...,Dysdera adriatica,Dysdera adriatica Kulczynski 1897,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera adriatica
341930,KROK065-19,TATGAATAATTTGAGTTTTTGGTTATTACCACCTTCTTTAATTCTT...,418,Dysdera ninnii|Dysdera ninnii Canestrini 1868|...,Dysdera ninnii,Dysdera ninnii Canestrini 1868,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera ninnii
341938,KROK063-19,TATGAATAATTTGAGTTTTTGGTTATTACCACCTTCTTTAATTCTT...,418,Dysdera ninnii|Dysdera ninnii Canestrini 1868|...,Dysdera ninnii,Dysdera ninnii Canestrini 1868,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera ninnii
341999,KROK139-20,TATAAATAATTTAAGCTTTTGACTTCTACCCCCATCGTTAGTGTTA...,418,Dysdera adriatica|Dysdera adriatica Kulczynski...,Dysdera adriatica,Dysdera adriatica Kulczynski 1897,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera adriatica
342001,KROK140-20,TATAAATAATTTAAGCTTTTGACTTCTACCCCCATCGTTAGTATTA...,418,Dysdera adriatica|Dysdera adriatica Kulczynski...,Dysdera adriatica,Dysdera adriatica Kulczynski 1897,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera adriatica
354035,MBBOL269-22,AATGAATAATTTAAGTTTTTGGTTGTTGCCTCCTTCTTTAATTTTA...,416,Dysdera crocata|Dysdera crocata C.L.Koch 1838|...,Dysdera crocata,Dysdera crocata C.L.Koch 1838,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera crocata
444772,SPIEU009-09,AATAAATAATTTGAGTTTTTGGTTGTTGCCTCCTTCTTTGGCTTTA...,418,Dysdera longirostris|Dysdera longirostris Dobl...,Dysdera longirostris,Dysdera longirostris Doblika 1853,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera longirostris
492541,UMAAI2655-22,AATGAATAATTTAAGTTTTTGGTTGTTGCCTCCTTCTTTAATTTTA...,417,Dysdera crocata|Dysdera crocata C.L.Koch 1838|...,Dysdera crocata,Dysdera crocata C.L.Koch 1838,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera crocata
492568,UMAAI2822-22,AATAAATAATTTGAGATTTTGGTTATTACCTCCATCTTTGATTTTA...,417,nan|Dysdera Latreille 1804|genus|Animalia|Arth...,nan,Dysdera Latreille 1804,genus,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,NaN
492569,UMAAI2823-22,AATAAATAATTTGAGATTTTGGTTATTGCCTCCATCTTTGATTTTA...,415,Dysdera erythrina|Dysdera erythrina Walckenaer...,Dysdera erythrina,Dysdera erythrina Walckenaer 1802,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera erythrina
492638,UMAAI3021-22,AATAAATAATTTGAGATTTTGGTTATTGCCTCCATCTTTGATTTTA...,417,nan|Dysdera Latreille 1804|genus|Animalia|Arth...,nan,Dysdera Latreille 1804,genus,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,NaN
493385,UNI54017-17,TATGAATAATTTAAGTTTTTGGTTGTTGCCTCCTTCTTTAATTTTA...,418,Dysdera crocata|Dysdera crocata C.L.Koch 1838|...,Dysdera crocata,Dysdera crocata C.L.Koch 1838,species,Animalia,Arthropoda,Arachnida,Araneae,Dysderidae,Dysdera,Dysdera crocata

In [10]:
with open('Dysdera-bf3-incomplete.fasta', "w") as file:
    for index, row in Dysdera.iterrows():
        file.write(
            f">{row['seq_id']}|{row['original_taxa_info']}|{row['scientificName']}|{row['rank']}|{row['kingdom']}|{row['phylum']}|{row['class']}|{row['order']}|{row['family']}|{row['genus']}|{row['species']}\n{row['sequence']}\n"
        )

In [2]:
from src.marker_scoring.metrics_system import OtlHandler

otlh = OtlHandler(otl='/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_phyl/Poland_taxonlist_bmi_harmonized.tsv')
otlh.validate_otl()
otlh.pre_process_otl()

In [7]:
poland_processed = otlh.otl.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG/BenthicMacroinvertebrates/OTL/Poland_taxonlist_bmi_harmonized.tsv", sep="\t", index=False)

In [3]:
# Check dtypes for all columns of a tsv file

import pandas as pd
import numpy as np
def check_dtypes_tsv(file_path):
    df = pd.read_csv(file_path, sep='\t')
    df.replace("-", np.nan)
    dtypes = df.dtypes
    print(dtypes)

check_dtypes_tsv("/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/filtered_phyl/Poland_taxonlist_bmi_harmonized.tsv")

taxa              object
scientificName    object
rank              object
kingdom           object
phylum            object
class             object
order             object
family            object
genus             object
dtype: object

/tmp/ipykernel_106471/635352360.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-", np.nan)

In [27]:
import os
import pandas as pd
from collections import defaultdict

folder_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-NEWRUN"

analysis_folders = [
    "all_complete_pbs", "all_complete_pbs/filtered",
    "amplicon", "incomplete_pbs", "incomplete_pbs/filtered",
    "insert", "insert/filtered", "input_B"
]

target_taxa = 'Abacarus Keifer 1944'

def count_sequences_as_dataframe(folder_path, analysis_folders, target_taxa):
    result_table = defaultdict(dict)

    for folder in analysis_folders:
        folder_path_full = os.path.join(folder_path, folder)
        if not os.path.exists(folder_path_full):
            continue

        for fasta_filename in os.listdir(folder_path_full):
            file_path = os.path.join(folder_path_full, fasta_filename)
            if not os.path.isfile(file_path):
                continue

            count = 0
            with open(file_path, 'r') as file:
                for line in file:
                    if line.startswith('>'):
                        parts = line.strip().lstrip('>').split('|')
                        if len(parts) >= 3 and parts[2].strip() == target_taxa:
                            count += 1

            primer = os.path.splitext(fasta_filename)[0]
            result_table[primer][folder] = count

    df = pd.DataFrame.from_dict(result_table, orient='index', columns=analysis_folders)
    df.fillna(0, inplace=True)
    df = df.astype(int)
    df.index.name = 'Primer'
    return df

df_counts = count_sequences_as_dataframe(folder_path, analysis_folders, target_taxa)

In [ ]:
# 75%
df_counts

,all_complete_pbs,all_complete_pbs/filtered,amplicon,incomplete_pbs,incomplete_pbs/filtered,insert,insert/filtered,input_B
Primer,,,,,,,,
COI_mICOIintF_jgHCO2198,21,0,0,21,21,0,0,0
COI_BF2_BR2,0,0,0,0,0,0,0,0
COI_BF3_BR2,1,1,0,1,1,0,0,0
COI_MG2-LCO1490_MG2-univR,1,1,0,1,1,0,0,0
COI_fwhF2_Fol-degen-rev,21,21,0,21,21,0,0,0
COI_FwhF2_EPTDr2n,28,28,8,8,8,8,8,20
COI_MICOIntF_HCO2198,18,18,0,18,18,0,0,0
COI_FwhF2_FwhR2n,47,47,39,39,39,39,39,8

In [ ]:
# 50%
df_counts

,all_complete_pbs,all_complete_pbs/filtered,amplicon,incomplete_pbs,incomplete_pbs/filtered,insert,insert/filtered,input_B
Primer,,,,,,,,
COI_mICOIintF_jgHCO2198,29,29,0,29,29,0,0,0
COI_BF2_BR2,29,29,0,29,29,0,0,0
COI_BF3_BR2,29,29,0,29,29,0,0,0
COI_MG2-LCO1490_MG2-univR,39,39,0,39,39,0,0,0
COI_fwhF2_Fol-degen-rev,29,29,0,29,29,0,0,0
COI_FwhF2_EPTDr2n,44,44,8,8,8,8,8,36
COI_MICOIntF_HCO2198,29,29,0,29,29,0,0,0
COI_FwhF2_FwhR2n,47,47,39,39,39,39,39,8