In [2]:
# Files
database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-primers.tsv"
run_name = 'diat-barcode-test-pga-headers'
otl_folder = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia'

In [2]:
# Intake data
from src.reference_database.sequence_import import *

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta()
data = custom_fasta_import.data
data.head()

/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta
mozaiko INFO: Cleaning FASTA headers in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta and saving to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta
mozaiko INFO: Processed 9233 sequence headers.
Retrieving taxonomy in header, from column 1 to column 10, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.

,seq_id,sequence,length,taxa_info
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...

In [3]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda

In [4]:
database_processed_path = custom_fasta_import.database_fasta_file

In [6]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification(database_processed_path, run_name=run_name)
insil.run_in_silico_analysis(primer_table)

mozaiko INFO: Checking if cutadapt is installed...
mozaiko INFO: cutadapt is installed.
mozaiko INFO: Checking if CRABS is installed...
mozaiko INFO: CRABS is installed.
mozaiko INFO: To continue the analysis, a set of primers is needed. This information should be uploaded as a TSV table and it should contain the following fields: ['target_group', 'barcode_region', 'assay_name', 'fwd_seq', 'rev_seq']
mozaiko INFO: All set. Running in-silico amplification...
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 646F_998R.
   --------   1/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-1.
   --------   2/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-2.
   --------   3/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-1.
   --------   4/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-2.
   --------   5/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-1.
   --------   6/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-2.
   --------   7/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/amplicon/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-pga-headers/insert/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F-DEG_R3-DEG.
   --------   8/8 processed   --------
/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta
mozaiko INFO: Cleaning FASTA headers in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta and saving to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta
mozaiko INFO: Processed 8860 sequence headers.
Retrieving taxonomy in header, from column 1 to column 10, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
mozaiko INFO: Number of inserts that were amplified successfully...
    For rbcL_708F1_R3-1, 4508 were retained.
    For rbcL_708F2_R3-2, 4652 were retained.
    For rbcL_708F-DEG_R3-DEG, 4774 were retained.
    For rbcL_708F1_R3-2, 4504 were retained.
    For rbcL_646F_998R, 4357 were retained.
    For rbcL_708F2_R3-1, 4656 were retained.
    For rbcL_708F3_R3-2, 4212 were retained.
    For rbcL_708F3_R3-1, 4214 were retained.
mozaiko INFO: Number of inserts with complete PBS that were not amplified...
    For rbcL_708F1_R3-1: 300 sequences were retained.
    For rbcL_708F2_R3-2: 300 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 300 sequences were retained.
    For rbcL_708F1_R3-2: 300 sequences were retained.
    For rbcL_646F_998R: 181 sequences were retained.
    For rbcL_708F2_R3-1: 300 sequences were retained.
    For rbcL_708F3_R3-2: 300 sequences were retained.
    For rbcL_708F3_R3-1: 300 sequences were retained.
    For rbcL_708F1_R3-1: 290 sequences were retained.
    For rbcL_708F2_R3-2: 146 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 24 sequences were retained.
    For rbcL_708F1_R3-2: 294 sequences were retained.
    For rbcL_646F_998R: 17 sequences were retained.
    For rbcL_708F2_R3-1: 142 sequences were retained.
    For rbcL_708F3_R3-2: 586 sequences were retained.
    For rbcL_708F3_R3-1: 584 sequences were retained.
mozaiko INFO: Number of inserts with incomplete PBS...
    For rbcL_708F1_R3-1: 590 sequences were retained.
    For rbcL_708F2_R3-2: 446 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 324 sequences were retained.
    For rbcL_708F1_R3-2: 594 sequences were retained.
    For rbcL_646F_998R: 198 sequences were retained.
    For rbcL_708F2_R3-1: 442 sequences were retained.
    For rbcL_708F3_R3-2: 886 sequences were retained.
    For rbcL_708F3_R3-1: 884 sequences were retained.
mozaiko INFO: In-silico amplification analysis completed.

In [1]:
otl_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

In [2]:
from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl_path)

otl = otl_handler.import_otl()
otl

,taxa,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,Achnanthes brevipes var. brevipes,Achnanthes brevipes var. brevipes,variety,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthaceae,Achnanthes,Achnanthes brevipes
1,Achnanthes brevipes var. intermedia,Achnanthes brevipes var. intermedia Kutzing Cl...,variety,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthaceae,Achnanthes,Achnanthes brevipes
2,Achnanthes coarctata,Achnanthes coarctata Brebisson ex W.Smith Grun...,species,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthaceae,Achnanthes,Achnanthes coarctata
3,Achnanthes curtissima,Achnanthes curtissima J.R.Carter 1963,species,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthidiaceae,Psammothidium,Achnanthes curtissima
4,Achnanthes exigua,Achnanthes exigua Grunow 1880,species,Chromista,Ochrophyta,Bacillariophyceae,Achnanthales,Achnanthaceae,Achnanthes,Achnanthes exigua
...,...,...,...,...,...,...,...,...,...,...
1981,Zygnema pectinatum,Zygnema pectinatum Vaucher C.Agardh,species,Plantae,Charophyta,Zygnematophyceae,Zygnematales,Zygnemataceae,Zygnema,Zygnema pectinatum
1982,Zygnema ralfsii,Zygnema ralfsii Hassall de Bary,species,Plantae,Charophyta,Zygnematophyceae,Zygnematales,Zygnemataceae,Zygnema,Zygnema ralfsii
1983,Zygnema sp.,Zygnema C.Agardh 1816,genus,Plantae,Charophyta,Zygnematophyceae,Zygnematales,Zygnemataceae,Zygnema,NaN
1984,Zygnema stellinum,Zygnema stellinum Vaucher C.Agardh,species,Plantae,Charophyta,Zygnematophyceae,Zygnematales,Zygnemataceae,Zygnema,Zygnema stellinum
1985,Zygnema vaucherii,Zygnema vaucheri C.Agardh,species,Plantae,Charophyta,Zygnematophyceae,Zygnematales,Zygnemataceae,Zygnema,Zygnema vaucheri

In [13]:
otl[otl['scientificName'].isna()]

Empty DataFrame
Columns: [taxa, scientificName, rank, kingdom, phylum, class, order, family, genus, species]
Index: []

In [3]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers'

for otl in os.listdir(otl_folder):
    otl_path = os.path.join(otl_folder, otl)

    country_name = otl.split('_')[0]
    output_path = os.path.join(output_folder, country_name + '_ranked_primers.tsv')
    print(" ---------------------")
    print("Processing OTL:", otl)
    mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
    ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)

 ---------------------
Processing OTL: Germany_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/incomplete_pbs/filtered/filtered_intersection.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
Retrieving taxonomy in header, from column 1 to column 11, considering the separator: '|'.
If this is not the case, please provide the correct columns using 'taxa_column_start' and 'taxa_column_end' within 'read_fasta'.
The count must start at 0.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-pga-headers/insert/multibarcode/multibarcode_input.tsv

KeyboardInterrupt: