In [1]:
# Files
database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi-primers.tsv"
run_name = 'bmi'
otl_folder = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi'

In [2]:
# Intake data
from src.reference_database.sequence_import import *

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta(database_file, check_taxid=False)
data = custom_fasta_import.data
data.head()

,seq_id,sequence,length,taxa_info
0,AASFB602-10,AACTTTATATTTAATATTTGGTGTATGATCTGCTATAGCGGGAACA...,658,nan|Ctenidae|family|Animalia|Arthropoda|Arachn...
1,AASFB633-10,TACTTTATATTTAATTTTTGGAGCTTGATCTGCTATAGTTGGAACA...,658,nan|Clubionidae|family|Animalia|Arthropoda|Ara...
2,AASFB645-10,TTCTTTGTATTTATTATTTGGTAGATGATCTGCTATAGTAGGAACA...,658,nan|Anyphaenidae|family|Animalia|Arthropoda|Ar...
3,AASFB649-10,AACTTTATATTTGGTATTTGGGGCTTGATCAGCTATAGTTGGAATA...,658,nan|Corinnidae|family|Animalia|Arthropoda|Arac...
4,AASFB654-10,AACACTTTATTTAGTTTTTGGAGCTTGATCAGCTATAGTTGGTACT...,658,nan|Salticidae|family|Animalia|Arthropoda|Arac...

In [3]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta_database()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,AASFB602-10,AACTTTATATTTAATATTTGGTGTATGATCTGCTATAGCGGGAACA...,658,nan|Ctenidae|family|Animalia|Arthropoda|Arachn...,nan,Ctenidae,family,Animalia,Arthropoda,Arachnida,Araneae,Ctenidae,NaN,NaN
1,AASFB633-10,TACTTTATATTTAATTTTTGGAGCTTGATCTGCTATAGTTGGAACA...,658,nan|Clubionidae|family|Animalia|Arthropoda|Ara...,nan,Clubionidae,family,Animalia,Arthropoda,Arachnida,Araneae,Clubionidae,NaN,NaN
2,AASFB645-10,TTCTTTGTATTTATTATTTGGTAGATGATCTGCTATAGTAGGAACA...,658,nan|Anyphaenidae|family|Animalia|Arthropoda|Ar...,nan,Anyphaenidae,family,Animalia,Arthropoda,Arachnida,Araneae,Anyphaenidae,NaN,NaN
3,AASFB649-10,AACTTTATATTTGGTATTTGGGGCTTGATCAGCTATAGTTGGAATA...,658,nan|Corinnidae|family|Animalia|Arthropoda|Arac...,nan,Corinnidae,family,Animalia,Arthropoda,Arachnida,Araneae,Corinnidae,NaN,NaN
4,AASFB654-10,AACACTTTATTTAGTTTTTGGAGCTTGATCAGCTATAGTTGGTACT...,658,nan|Salticidae|family|Animalia|Arthropoda|Arac...,nan,Salticidae,family,Animalia,Arthropoda,Arachnida,Araneae,Salticidae,NaN,NaN

In [4]:
database_processed_path = custom_fasta_import.database_fasta_file

In [17]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification(database_processed_path, run_name=run_name)
insil.run_in_silico_analysis(primer_table)

mozaiko INFO: Checking if cutadapt is installed...
mozaiko INFO: cutadapt is installed.
mozaiko INFO: Checking if CRABS is installed...
mozaiko INFO: CRABS is installed.
mozaiko INFO: To continue the analysis, a set of primers is needed. This information should be uploaded as a TSV table and it should contain the following fields: ['target_group', 'barcode_region', 'assay_name', 'fwd_seq', 'rev_seq']
mozaiko INFO: All set. Running in-silico amplification...
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...CCWGTWYTAGCHGGDGCWATYAC;min_overlap=23 --output data/output_data/bmi/amplicon/COI_FwhF2_FwhR2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...CCWGTWYTAGCHGGDGCWATYAC;min_overlap=23 --output data/output_data/bmi/insert/COI_FwhF2_FwhR2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for FwhF2_FwhR2n.
   --------   1/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g CCHGAYATRGCHTTYCCHCG;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi/amplicon/COI_BF3_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 560 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g CCHGAYATRGCHTTYCCHCG;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi/insert/COI_BF3_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 560 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for BF3_BR2.
   --------   2/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...RAHCGAATACCHYTATTTGTTTG;min_overlap=23 --output data/output_data/bmi/amplicon/COI_FwhF2_EPTDr2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...RAHCGAATACCHYTATTTGTTTG;min_overlap=23 --output data/output_data/bmi/insert/COI_FwhF2_EPTDr2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for FwhF2_EPTDr2n.
   --------   3/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi/amplicon/COI_mICOIintF_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi/insert/COI_mICOIintF_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for mICOIintF_jgHCO2198.
   --------   4/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGTCAACAAATCATAAAGATATTGG;min_overlap=25...TGATTTTTTGGTCACCCTGAAGTTTA;min_overlap=26 --output data/output_data/bmi/amplicon/COI_LCO1490_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 549 --discard-untrimmed --action retain
mozaiko WARNING: No amplicons retrieved for COI_LCO1490_HCO2198.
mozaiko INFO: Running cutadapt command as: cutadapt -g GGTCAACAAATCATAAAGATATTGG;min_overlap=25...TGATTTTTTGGTCACCCTGAAGTTTA;min_overlap=26 --output data/output_data/bmi/insert/COI_LCO1490_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 549 --discard-untrimmed --action trim
mozaiko WARNING: No inserts retrieved for COI_LCO1490_HCO2198.
mozaiko INFO: Completed analysis for LCO1490_HCO2198.
   --------   5/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g TCHACHAAYCAYAARGAYATYGG;min_overlap=23...CAYGCHTTYRTHATRATYTTYTTYATRGT;min_overlap=29 --output data/output_data/bmi/amplicon/COI_MG2-LCO1490_MG2-univR.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g TCHACHAAYCAYAARGAYATYGG;min_overlap=23...CAYGCHTTYRTHATRATYTTYTTYATRGT;min_overlap=29 --output data/output_data/bmi/insert/COI_MG2-LCO1490_MG2-univR.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for MG2-LCO1490_MG2-univR.
   --------   6/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...TGRTTYTTYGGNCAYCCNGARGTNTA;min_overlap=26 --output data/output_data/bmi/amplicon/COI_fwhF2_Fol-degen-rev.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...TGRTTYTTYGGNCAYCCNGARGTNTA;min_overlap=26 --output data/output_data/bmi/insert/COI_fwhF2_Fol-degen-rev.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for fwhF2_Fol-degen-rev.
   --------   7/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGATTTTTTGGTCACCCTGAAGTTTA ;min_overlap=27 --output data/output_data/bmi/amplicon/COI_MICOIntF_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 547 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGATTTTTTGGTCACCCTGAAGTTTA ;min_overlap=27 --output data/output_data/bmi/insert/COI_MICOIntF_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 547 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for MICOIntF_HCO2198.
   --------   8/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GCHCCHGAYATRGCHTTYCC;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi/amplicon/COI_BF2_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 560 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GCHCCHGAYATRGCHTTYCC;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi/insert/COI_BF2_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 560 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for BF2_BR2.
   --------   9/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g TITCIACIAAYCAYAARGAYATTGG;min_overlap=25...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi/amplicon/COI_JgLCO1490_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 549 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g TITCIACIAAYCAYAARGAYATTGG;min_overlap=25...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi/insert/COI_JgLCO1490_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi_database_idm_subset_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 549 --discard-untrimmed --action trim
Error filtering insert directory: division by zero
mozaiko INFO: Completed analysis for JgLCO1490_jgHCO2198.
   --------   10/10 processed   --------
mozaiko INFO: Number of inserts that were amplified successfully...
    For COI_mICOIintF_jgHCO2198, 3743 were retained.
    For COI_BF2_BR2, 6615 were retained.
    For COI_BF3_BR2, 6642 were retained.
    For COI_MG2-LCO1490_MG2-univR, 8094 were retained.
    For COI_fwhF2_Fol-degen-rev, 3807 were retained.
    For COI_LCO1490_HCO2198, 0 were retained.
    For COI_FwhF2_EPTDr2n, 120635 were retained.
    For COI_MICOIntF_HCO2198, 3054 were retained.
    For COI_JgLCO1490_jgHCO2198, 0 were retained.
    For COI_FwhF2_FwhR2n, 208071 were retained.
mozaiko INFO: Number of inserts with complete PBS that were not amplified...
    For COI_mICOIintF_jgHCO2198: 177344 sequences were retained.
    For COI_BF2_BR2: 176112 sequences were retained.
    For COI_BF3_BR2: 176085 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 108781 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 177431 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 33 sequences were retained.
    For COI_MICOIntF_HCO2198: 177229 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 2094 sequences were retained.
    For COI_mICOIintF_jgHCO2198: 915 sequences were retained.
    For COI_BF2_BR2: 569 sequences were retained.
    For COI_BF3_BR2: 560 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 284 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 861 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 80239 sequences were retained.
    For COI_MICOIntF_HCO2198: 1523 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 3840 sequences were retained.
mozaiko INFO: Number of inserts with incomplete PBS...
    For COI_mICOIintF_jgHCO2198: 178259 sequences were retained.
    For COI_BF2_BR2: 176681 sequences were retained.
    For COI_BF3_BR2: 176645 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 109065 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 178292 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 80272 sequences were retained.
    For COI_MICOIntF_HCO2198: 178752 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 5934 sequences were retained.
mozaiko INFO: In-silico amplification analysis completed.

In [2]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi'

for otl in os.listdir(otl_folder):
    otl_path = os.path.join(otl_folder, otl)

    country_name = otl.split('_')[0]
    output_path = os.path.join(output_folder, country_name + '_ranked_primers.tsv')
    print(" ---------------------")
    print("Processing OTL:", otl)
    mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
    ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)
    mex.sort_otl_level_results(subdirectory_name=country_name)

 ---------------------
Processing OTL: Sweden_taxonlist_bmi_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi/incomplete_pbs/filtered/filtered_intersection.
mozaiko WARNING: No matching amplicon found for insert ID ARCAE215-17 in COI_FwhF2_FwhR2n.fasta
mozaiko WARNING: No matching amplicon found for insert ID BMAD057-09 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID BMAD044-09 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID DBFWG004-20 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID GRAEL1347-22 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID GRAEL1383-22 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID NZLEP380-20 in COI_BF3_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID AODON330-20 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID BIBSA1320-15 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID BMAD057-09 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID BMAD044-09 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID DBFWG004-20 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID GRAEL1347-22 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID GRAEL1383-22 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching amplicon found for insert ID NZLEP380-20 in COI_mICOIintF_jgHCO2198.fasta
mozaiko WARNING: No matching sequences found between amplicon and insert files.

KeyError: "None of [Index(['seq_id', 'taxon', 'three_end_mismatch_sum'], dtype='object')] are in the [columns]"