In [1]:
# Files
database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-primers.tsv"
run_name = 'diat-barcode-test-cluster'
otl_folder = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia'

In [2]:
# Intake data
from src.reference_database.sequence_import import *

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta(database_file, check_taxid=False)
data = custom_fasta_import.data
data.head()

,seq_id,sequence,length,taxa_info
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...

In [3]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta_database()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,1688,Chlorogonium elongatum|Chlorogonium elongatum ...,Chlorogonium elongatum,Chlorogonium elongatum P.A.Dang.,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Haematococcaceae,Chlorogonium,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,1680,Fragilaria sp.|Fragilaria H.C.Lyngbye 1819|GEN...,Fragilaria sp.,Fragilaria H.C.Lyngbye 1819,genus,Chromista,Ochrophyta,Bacillariophyceae,Fragilariales,Fragilariaceae,Fragilaria,NaN
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,1659,Pandorina morum|Pandorina morum O.F.Mull. Bory...,Pandorina morum,Pandorina morum O.F.Mull. Bory,species,Plantae,Chlorophyta,Chlorophyceae,Volvocales,Volvocaceae,Pandorina,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,1636,Scenedesmus spinosus|Scenedesmus spinosus Chod...,Scenedesmus spinosus,Scenedesmus spinosus Chodat,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Desmodesmus,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,1638,Scenedesmus quadricauda|Scenedesmus quadricaud...,Scenedesmus quadricauda,Scenedesmus quadricauda Turpin Breb.,species,Plantae,Chlorophyta,Chlorophyceae,Sphaeropleales,Scenedesmaceae,Scenedesmus,Scenedesmus quadricauda

In [4]:
database_processed_path = custom_fasta_import.database_fasta_file

In [5]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification(database_processed_path, run_name=run_name)
insil.run_in_silico_analysis(primer_table)

mozaiko INFO: Checking if cutadapt is installed...
mozaiko INFO: cutadapt is installed.
mozaiko INFO: Checking if CRABS is installed...
mozaiko INFO: CRABS is installed.
mozaiko INFO: To continue the analysis, a set of primers is needed. This information should be uploaded as a TSV table and it should contain the following fields: ['target_group', 'barcode_region', 'assay_name', 'fwd_seq', 'rev_seq']
mozaiko INFO: All set. Running in-silico amplification...
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g ATGCGTTGGAGAGARCGTTTC;min_overlap=21...CAGTTGTWGGTAAATTAGAAGGTGATC;min_overlap=27 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_646F_998R.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 552 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 646F_998R.
   --------   1/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F1_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-1.
   --------   2/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTAAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F1_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F1_R3-2.
   --------   3/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F2_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-1.
   --------   4/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGTTAAAGGTTCWTAYTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F2_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F2_R3-2.
   --------   5/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CAGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F3_R3-1.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-1.
   --------   6/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAACTAAAGGTTCWTACTTAAA;min_overlap=27...CTGTTGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F3_R3-2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F3_R3-2.
   --------   7/8 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/amplicon/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g AGGTGAAGYWAAAGGTTCWTAYTTAAA;min_overlap=27...CWGTWGTWGGTAAATTAGAAGG;min_overlap=22 --output data/output_data/diat-barcode-test-cluster/insert/rbcL_708F-DEG_R3-DEG.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/diat-barcode-taxa_harmonized_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 0 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for 708F-DEG_R3-DEG.
   --------   8/8 processed   --------
mozaiko INFO: Number of inserts that were amplified successfully...
    For rbcL_708F1_R3-1, 4508 were retained.
    For rbcL_708F2_R3-2, 4652 were retained.
    For rbcL_708F-DEG_R3-DEG, 4774 were retained.
    For rbcL_708F1_R3-2, 4504 were retained.
    For rbcL_646F_998R, 4357 were retained.
    For rbcL_708F2_R3-1, 4656 were retained.
    For rbcL_708F3_R3-2, 4212 were retained.
    For rbcL_708F3_R3-1, 4214 were retained.
mozaiko INFO: Number of inserts with complete PBS that were not amplified...
    For rbcL_708F1_R3-1: 300 sequences were retained.
    For rbcL_708F2_R3-2: 300 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 300 sequences were retained.
    For rbcL_708F1_R3-2: 300 sequences were retained.
    For rbcL_646F_998R: 181 sequences were retained.
    For rbcL_708F2_R3-1: 300 sequences were retained.
    For rbcL_708F3_R3-2: 300 sequences were retained.
    For rbcL_708F3_R3-1: 300 sequences were retained.
    For rbcL_708F1_R3-1: 290 sequences were retained.
    For rbcL_708F2_R3-2: 146 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 24 sequences were retained.
    For rbcL_708F1_R3-2: 294 sequences were retained.
    For rbcL_646F_998R: 17 sequences were retained.
    For rbcL_708F2_R3-1: 142 sequences were retained.
    For rbcL_708F3_R3-2: 586 sequences were retained.
    For rbcL_708F3_R3-1: 584 sequences were retained.
mozaiko INFO: Number of inserts with incomplete PBS...
    For rbcL_708F1_R3-1: 590 sequences were retained.
    For rbcL_708F2_R3-2: 446 sequences were retained.
    For rbcL_708F-DEG_R3-DEG: 324 sequences were retained.
    For rbcL_708F1_R3-2: 594 sequences were retained.
    For rbcL_646F_998R: 198 sequences were retained.
    For rbcL_708F2_R3-1: 442 sequences were retained.
    For rbcL_708F3_R3-2: 886 sequences were retained.
    For rbcL_708F3_R3-1: 884 sequences were retained.
mozaiko INFO: In-silico amplification analysis completed.

In [6]:
otl_path = "/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/dia/Austria_taxonlist_diatoms_harmonized.tsv"

In [7]:
from src.marker_scoring.metrics_system import *

otl_handler = OtlHandler(otl_path)

otl = otl_handler.import_otl()
otl

(1861,
 {'Lemanea fucina Bory de Saint-Vicent',
  'Diploneis minuta J.B.Petersen 1928',
  'Eunotia formicina H.Lange-Bertalot 2011',
  'Platessa montana Krasske H.Lange-Bertalot 2004',
  'Cymbella simonsenii Krammer 1985',
  'Microspora quadrata Hazen',
  'Navicula occulta Krasske 1929',
  'Gomphonema olivaceum var. olivaceum',
  'Cosmarium margaritiferum Menegh. ex Ralfs',
  'Naviculadicta vaucheriae J.B.Petersen Lange-Bertalot 1994',
  'Aphanocapsa C.Nageli 1849',
  'Nitzschia intermedia Hantzsch ex Cleve  Grunow 1880',
  'Batrachospermum keratophytum Bory de Saint-Vincent',
  'Psammothidium rechtense L.Leclercq Lange-Bert.',
  'Naviculadicta schaumburgii H.Lange-Bertalot  G.Hofmann 2004',
  'Nitzschia fruticosa Hustedt 1957',
  'Cosmarium pachydermum var. aethiopicum West  G.S.West West  G.S.West',
  'Hantzschia graciosa Lange-Bertalot 1993',
  'Cocconeis euglyptoides Geitler H.Lange-Bertalot 2004',
  'Cocconeis placentula var. lineata Ehrenberg van Heurck 1885',
  'Epithemia frickei Krammer 1987',
  'Eunotia bilunaris Ehrenberg Schaarschmidt 1880',
  'Stauroneis alpina Hustedt',
  'Navicula obsoleta Hustedt 1942',
  'Eucocconeis quadratarea strup Lange-Bertalot 1999',
  'Luticola dismutica Hustedt D.G.Mann 1990',
  'Nitzschia gisela Lange-Bertalot 1987',
  'Placoneis clementis Grunow E.J.Cox 1987',
  'Spirogyra communis Hassall Kutz.',
  'Cladophora glomerata L. Kutz.',
  'Navicula expecta VanLandingham',
  'Encyonema distinctum Lange-Bertalot  Krammer 1997',
  'Neidiopsis levanderi var. capitata Krasske H.Lange-Bertalot 1999',
  'Palmella mucosa Kutz.',
  'Planothidium minutissimum Krasske Lange-Bertalot 1999',
  'Planothidium frequentissimum Lange-Bertalot Lange-Bertalot 1999',
  'Scytonema myochrous C.Agardh ex Bornet  Flahault',
  'Encyonema ventricosum Van Heurck 1880-1885',
  'Navicula lanceolata Agardh Kutzing',
  'Psammothidium lauenburgianum Hustedt Bukhtiyarova  Round 1996',
  'Stauroneis acidobionta H.Lange-Bertalot  U.Wydrzycka 2001',
  'Coleodesmium wrangelii Borzi ex Geitler',
  'Achnanthidium F.T.Kutzing 1844',
  'Coleochaete soluta Breb. Prings.',
  'Surirella visurgis Hustedt 1957',
  'Navicula pseudosilicula Hustedt',
  'Petalonema alatum Borzi ex Bornet  Flahault Correns',
  'Gomphonema olivaceoides',
  'Fragilaria pinnata Ehrenberg 1843',
  'Halamphora oligotraphenta Lange-Bertalot Levkov 2009',
  'Navicula rostellata Kutzing',
  'Nitzschia frequens Hustedt 1957',
  'Nitzschia flexoides Geitler 1968',
  'Tabellaria C.G.Ehrenberg ex F.T.Kutzing 1844',
  'Navicula notha Wallace',
  'Oedogonium sociale Wittr.',
  'Aphanocapsa grevillei Berk. Rabenh.',
  'Cymbopleura rupicola Grunow Krammer 2003',
  'Cymbopleura geofriedana Reichardt 2004',
  'Luticola nivaloides Bock Denys  de Smet',
  'Placoneis gastrum Ehrenberg Mereschkovsky 1903',
  'Cocconeis placentra 1941',
  'Pinnularia obscura Krasske 1932',
  'Oedogonium cymatosporum Wittr.  Nordst.',
  'Hydrurus foetidus Villars Trevisan',
  'Pinnularia gigas Ehrenberg 1843',
  'Achnanthidium macrocephalum Hustedt Round  Bukhtiyarova 1996',
  'Pinnularia lata Brebisson W.Smith 1853',
  'Navicula symmetrica Patrick',
  'Closterium striolatum Ralfs',
  'Eunotia arcus Ehrenberg 1837',
  'Cymbella helmckei Krammer 1982',
  'Gomphonema pala E.Reichardt 2001',
  'Nitzschia valdestriata Aleem  Hustedt 1951',
  'Achnanthes minuscula Hustedt 1945',
  'Komvophoron constrictum Szafer Anagn.  Komarek',
  'Craticula halophila Grunow D.G.Mann 1990',
  'Pinnularia anglica K.Krammer 1992',
  'Nitzschia commutata Grunow 1880',
  'Pinnularia subcapitata var. subcapitata',
  'Krasskella R.Ross  P.A.Sims 1978',
  'Fallacia lenzii Hustedt Lange-Bertalot 2004',
  'Nitzschia pumila Hustedt 1954',
  'Leptolyngbya frigida F.E.Fritsch Anagn.  Komarek',
  'Rhopalodia O.Muller 1895',
  'Phormidium subfuscum Kutz. ex Gomont',
  'Amphora indistincta Levkov 2009',
  'Paralemanea torulosa Roth Sheath  Sherwood',
  'Brachysira procera Lange-Bertalot  Gerd Moser 1994',
  'Chamaepinnularia muscicola J.B.Petersen M.S.Kulikovskiy Lange-Bert.  Witkowski 2010',
  'Phaeoplaca thallosa Chodat',
  'Sellaphora bacillum Ehrenberg D.G.Mann 1989',
  'Stauroneis lundii Hustedt 1959',
  'Eunotia septentrionalis strup 1897',
  'Cymbella parva W.Sm. Wolle',
  'Microcostatus J.R.Johansen  J.C.Sray 1998',
  'Navicula tenelloides Hustedt',
  'Naviculadicta absoluta Hust. Lange-Bert.',
  'Enteromorpha flexuosa Wulfen J.Agardh',
  'Navicula normaloides Cholnoky',
  'Surirella splendida Ehrenb.',
  'Pseudanabaena catenata Lauterborn',
  'Palmella Lyngbye 1819',
  'Karayevia kolbei Hudtedt Bukhtiyarova 1999',
  'Rivularia haematites C.Agardh ex Bornet  Flahault',
  'Reimeria uniseriata S.E.Sala J.M.Guerrero  M.E.Ferrario 1993',
  'Naviculadicta multiconfusa Lange-Bertalot 1996',
  'Tetracyclus J.Ralfs 1843',
  'Diploneis fontium Reichardt  Lange-Bertalot 2004',
  'Nitzschia fossilis Grunow Grunow 1881',
  'Zygnema insigne Hassall Kutz.',
  'Karayevia ploenensis Hustedt Bukhtiyarova 1999',
  'Chamaesiphon oncobyrsoides Geitler',
  'Platessa hustedtii Krasske Lange-Bertalot 2004',
  'Gomphonema anjae Lange-Bertalot  Reichardt 1991',
  'Denticula elegans Kutzing 1844',
  'Navicula bremeyeri Hustedt 1939',
  'Navicula platystoma Ehrenberg',
  'Stichococcus Nageli 1849',
  'Cymbella compacta strup 1910',
  'Pinnularia marchica Ilka Schonfelder 2000',
  'Navicula porifera Hustedt',
  'Frustulia vulgaris Thwaites De Toni 1891',
  'Achnanthidium druartii Rimet  Coute 2010',
  'Encyonema alpinum M.Heribaud 1862',
  'Gomphonema insigne Gregory 1856',
  'Hippodonta coxiae Lange-Bertalot 2001',
  'Cymbopleura subaequalis var. subaequalis',
  'Nitzschia tropica Hustedt 1949',
  'Tychonema tenue Skuja Anagn.  Komarek',
  'Gomphonema olivaceolacuum Lange-Bertalot  Reichardt Lange-Bertalot  Reichardt 2004',
  'Chamaepinnularia hassiaca Krasske Cantonati  Lange-Bertalot 2009',
  'Gomphonema C.G.Ehrenberg 1832',
  'Nitzschia sociabilis Hustedt 1957',
  'Closterium dianae Ehrenberg ex Ralfs 1848',
  'Closterium tumidum L.N.Johnson',
  'Mayamaea ingenua Hust. Lange-Bert.  Hofmann 2011',
  'Eolimna H.Lange-Bertalot  W.Schiller 1997',
  'Navicula vandamii Schoeman  Archibald',
  'Encyonema neogracile Krammer 1997',
  'Navicula lucidula Grunow',
  'Nitzschia parvula W.Smith 1853',
  'Oedogonium cyathigerum Wittr.',
  'Mayamaea excelsa Krasske Lange-Bertalot 1997',
  'Diploneis modica Hustedt 1945',
  'Chaetophora flagellifera Kutz.',
  'Achnanthidium subhudsonis Hustedt H.Kobayasi 2006',
  'Geissleria ignota Krasske Lange-Bertalot  Metzeltin 1996',
  'Encyonema reichardtii Krammer D.G.Mann 1990',
  'Navicula catalanogermanica Lange-Bertalot  G.Hofmann',
  'Cymbopleura K.Krammer K.Krammer 1999',
  'Oedogonium capillare Kutzing ex Hirn',
  'Jaaginema subtilissimum Kutz. ex Forti Anagn.  Komarek',
  'Nitzschia subtilis Kutzing Grunow 1880',
  'Fragilaria atomus Hustedt 1931',
  'Stauroneis siberica Lange-Bertalot  Metzeltin 1996',
  'Navicula leistikowii Lange-Bertalot',
  'Chamaesiphon confervicola A.Braun',
  'Cymbella scotlandica Krammer 2002',
  'Cymbella affinis Kutzing 1844',
  'Pleurosigma angulatum Queckett W.Smith 1852',
  'Amphora inariensis Krammer 1980',
  'Eunotia intermedia Krasske Norpel  Lange-Bertalot 1993',
  'Gyrosigma kuetzingii Grunow Cleve 1894',
  'Neidium affine Ehrenberg Pfizer 1871',
  'Diploneis separanda Lange-Bertalot 2004',
  'Tribonema minus Wille Hazen',
  'Achnanthidium temniskovae P.Ivanov  L.Ector 2006',
  'Nitzschia draveillensis Coste  Ricard 1980',
  'Characiopsis acuta A.Braun Borzi',
  'Hildenbrandia rivularis Liebman J.Agardh',
  'Pinnularia lagerstedtii Cleve Cleve-Euler 1934',
  'Lemanea Bory de Saint-Vincent 1808',
  'Geissleria cummerowi L.Kalbe Lange-Bertalot 2001',
  'Neidium bisulcatum var. bisulcatum',
  'Tolypothrix Kutzing ex Bornet  Flahault 1886',
  'Nitzschia archibaldii Lange-Bertalot 1980',
  'Nitzschia vermicularis Kutzing Hantzsch 1860',
  'Psammothidium subatomoides Hustedt L.Bukhtiyarova  Round 1996',
  'Diatoma polonica M.Bak H.Lange-Bertalot J.Nosek Z.Jakubowska  M.Kielbasa 2014',
  'Spirulina major Kutz. ex Gomont',
  'Fallacia lucinensis Hustedt D.G.Mann 1990',
  'Hippodonta capitata Ehrenberg Lange-Bertalot Metzeltin  Witkowski 1996',
  'Nitzschia clausii Hantzsch 1860',
  'Tolypothrix penicillata Thur. ex Bornet  Flahault',
  'Cyanostylon Geitler 1928',
  'Chamaesiphon minutus Rostaf. Lemmerm.',
  'Placoneis subplacentula Hustedt E.J.Cox 2003',
  'Closterium jenneri Ralfs',
  'Nitzschia tenuis W.Smith 1853',
  'Caloneis westii W.Smith Hendey 1964',
  'Navicula semen Ehrenberg',
  'Navicula integra Grunow ex Cleve Fricke 1902',
  'Closterium tumidum var. nylandicum Gronblad',
  'Cymbopleura amphicephala Nageli Krammer 2003',
  'Spirogyra majuscula Kutz.',
  'Eunotia fallax A.Cleve 1895',
  'Eunotia rhynchocephala Hustedt 1936',
  'Klebsormidium rivulare Kutz. M.O.Morison  Sheath',
  'Cyanophanon Geitler 1955',
  'Stauroneis subgracilis Lange-Bertalot  K.Krammer 1999',
  'Navicula exilis Kutzing',
  'Pinnularia grunowii Krammer 2000',
  'Oscillatoria princeps Vaucher ex Gomont',
  'Achnanthidium affine Grunow Czarnecki 1994',
  'Pseudophormidium Forti Anagnostidis  Komarek 1988',
  'Characium acuminatum A.Braun',
  'Pinnularia borealis var. borealis',
  'Stauroneis reichardtii H.Lange-Bertalot P.Cavacini N.Tagliaventi  S.Alfinito 2003',
  'Pinnularia esoxiformis Fusey 1951',
  'Entomoneis costata Hustedt Reimer 1975',
  'Eunotia arcubus Norpel  Lange-Bertalot 1993',
  'Gomphocymbellopsis ancyli Cleve K.Krammer 2003',
  'Encyonopsis lanceola Grunow Krammer 1997',
  'Ulothrix zonata F.Weber  D.Mohr Kutz.',
  'Prasiola crispa Lightf. Kutz.',
  'Navicula krammerae Lange-Bertalot',
  'Psammothidium altaicum Poretzky L.Bukhtiyarova 1996',
  'Gomphonema zellense E.Reichardt 1999',
  'Platessa rupestris Krasske Lange-Bertalot 2004',
  'Pleurocapsa minor Hansg.',
  'Gomphonema acidoclinatum Lange-Bertalot  Reichardt 2004',
  'Nitzschia dubia W.Smith 1853',
  'Navicula reinhardtii Grunow Grunow',
  'Nupela W.Vyverman  P.Compere 1991',
  'Pinnularia gibba Ehrenberg 1843',
  'Eunotia formica Ehrenberg 1843',
  'Mastogloia grevillei W.Smith 1856',
  'Navicula pseudolanceolata Lange-Bertalot',
  'Eunotia varioundulata Norpel  Lange-Bertalot 1996',
  'Tetraspora cylindrica Wahlenb. C.Agardh',
  'Batrachospermum skujae Geitler',
  'Nitzschia calida Grunow',
  'Hantzschia subrupestris Lange-Bertalot 1993',
  'Nitzschia lange-bertalotii Coste  Ricard 1982',
  'Closterium venus Kutz. ex Ralfs',
  'Encyonopsis alpina Krammer  Lange-Bertalot 1997',
  'Hyella fontana Huber  Jardin',
  'Hydrocoleum homoeotrichum Kutz. ex Gomont',
  'Gomphonema minusculum A.Cleve-Euler 1949',
  'Gomphonema subclavatum Grunow Grunow 1884',
  'Cocconeis neodiminuta Krammer 1990',
  'Nitzschia nana Grunow 1881',
  'Fragilaria rumpens Kutzing G.W.F.Carlson 1913',
  'Cymbopleura tynnii Krammer Krammer 2003',
  'Gomphosphenia H.Lange-Bertalot 1995',
  'Pinnularia islandica strup 1918',
  'Closterium ehrenbergii Menegh. ex Ralfs 1848',
  'Stauroneis thermicola J.B.Petersen Lund 1946',
  'Neidium paraffine H.Lange-Bertalot P.Cavacini N.Tagliaventi  S.Alfinito 2003',
  'Navicula simulata Manguin 1942',
  'Gloeotrichia J.Agardh ex Bornet  Flahault 1886',
  'Stenopterobia densestriata Hustedt Krammer 1987',
  'Diploneis oculata Brebisson Cleve 1894',
  'Cymbella laevis Nageli 1863',
  'Achnanthidium linearioides Lange-Bert. Lange-Bert.',
  'Pinnularia transversa A.Schmidt Mayer 1939',
  'Eunotia tenella Grunow Hustedt 1913',
  'Encyonopsis aequalis W.Smith Krammer 1997',
  'Leptolyngbya foveolara Gomont Anagn.  Komarek',
  'Navicula muraloides Hustedt',
  'Surirella subsalsa W.Smith 1853',
  'Eunotia bidens Dalla Torre  Sarnthein 1901',
  'Pinnularia silvatica J.B.Petersen 1935',
  'Nitzschia fibula-fissa Lange-Bertalot 1980',
  'Kobayasiella okadae Skvortzov Lange-Bertalot 1999',
  'Sellaphora mutatoides H.Lange-Bertalot  D.Metzeltin 2002',
  'Stauroneis undata Hustedt 1939',
  'Batrachospermum Roth 1797',
  'Aneumastus minor Lange-Bertalot 1993',
  'Pinnularia gibba var. gibba',
  'Nitzschia rectiformis Hustedt 1943',
  'Psammothidium rossii Hustedt L.Bukhtiyarova  Round 1996',
  'Epithemia turgida var. turgida',
  'Eunotia incisa W.Smith ex W.Gregory 1854',
  'Caloneis permagna Bailey Cleve 1894',
  'Gomphonema lapponicum A.Cleve Cleve-Euler',
  'Nitzschia valdecostata Lange-Bertalot  Simonsen 1978',
  'Chlorogloea Wille 1900',
  'Nitzschia dealpina Lange-Bertalot  Hofmann 1993',
  'Aphanothece stagnina Spreng. A.Braun',
  'Fragilaria gracilis strup 1910',
  'Placoneis ignorata Schimanski Lange-Bertalot 2000',
  'Platessa ziegleri Lange-Bertalot H.Lange-Bertalot 2004',
  'Surirella gracilis OMeara 1867',
  'Encyonema lacustre C.Agardh Pant.',
  'Tolypothrix rivularis Hansg.',
  'Eunotia seminulum Norpel-Schempp  Lange-Bertalot 1996',
  'Achnanthidium eutrophilum Lange-Bertalot Lange-Bertalot 1999',
  'Navicula digitoconvergens Lange-Bertalot',
  'Nitzschia oligotraphenta H.Lange-Bertalot H.Lange-Bertalot',
  'Simonsenia H.Lange-Bertalot 1979',
  'Gomphonema capitatum Ehrenberg 1838',
  'Nitzschia supralitorea Lange-Bertalot 1979',
  'Stauroneis parathermicola Lange-Bertalot 2011',
  'Mayamaea lacunolaciniata Lange-Bertalot  K.Bonik Lange-Bertalot 1997',
  'Caloneis aerophila W.Bock 1963',
  'Sellaphora stroemii Hustedt H.Kobayasi 2002',
  'Navicula viridula var. linearis Hustedt',
  'Parlibellus E.J.Cox 1988',
  'Cladophora rivularis L. Kuntze',
  'Limnothrix',
  'Nitzschia bavarica Hustedt 1953',
  'Achnanthidium saprophilum H.Kobayasi  S.Mayama Round  L.Bukhtiyarova 1996',
  'Caloneis thermalis Grunow Krammer 1985',
  'Achnanthes semiaperta Hustedt 1945',
  'Amphora hemicycla Stoermer  J.J.Yang',
  'Gomphonema brebissonii Kutzing 1849',
  'Sellaphora mutata Krasske Lange-Bertalot 1996',
  'Psammothidium punctulatum Simonsen L.Bukhtiyarova  Round 1996',
  'Navicula amphiceropsis Lange-Bertalot  U.Rumrich',
  'Oedogonium itzigsohnii de Bary',
  'Stigonema ocellatum Thur. ex Bornet  Flahault',
  'Pinnularia nodosa Ehrenberg W.Smith 1856',
  'Gomphoneis transsilvanica Pantocsek Krammer 1985',
  'Stauroneis smithii Grunow 1860',
  'Tribonema vulgare Pascher',
  'Cosmarium biretum Breb.',
  'Navicula cariocincta Lange-Bertalot',
  'Schizothrix lacustris A.Braun ex Gomont',
  'Fallacia subhamulata Round et al. 1990',
  'Nitzschia homburgiensis Lange-Bertalot 1978',
  'Gomphonema angusticephalum E.Reichardt  H.Lange-Bertalot 1999',
  'Lemanea rigida Sirodot De Toni',
  'Brachysira garrensis Lange-Bertalot  Krammer Lange-Bertalot 1994',
  'Eunotia faba Ehrenb.',
  'Diatoma ehrenbergii Kutzing 1844',
  'Navicula hofmanniae Lange-Bertalot',
  'Naviculadicta elorantana Lange-Bertalot 1996',
  'Cymbella stigmaphora strup 1910',
  'Pinnularia subrostrata K.E.Lohman  G.W.Andrews 1968',
  'Closterium pseudolunula Borge',
  'Planothidium granum M.H.Hohn  Hellerman Lange-Bertalot 1999',
  'Ammatoidea normanii G.S.West  C.West',
  'Karayevia laterostrata Hustedt Round  Bukhtiyarova 1996',
  'Oscillatoria subbrevis Schmidle',
  'Draparnaldia mutabilis Roth Bory',
  'Closterium kuetzingii Breb.',
  'Pinnularia castraregina Krammer 2000',
  'Geitleribactron periphyticum Komarek',
  'Bulbochaete C.Agardh 1817',
  'Delicata minuta K.Krammer 2003',
  'Amphora copulata Kutzing Schoeman  R.E.M.Archibald 1986',
  'Cymbopleura incertiformis K.Krammer 2003',
  'Navicula radiosa Kutzing',
  'Plectonema Thuret ex Gomont 1892',
  'Fragilaria martyi Heribaud-Joseph Lange-Bertalot 1993',
  'Phormidium calcareum Kutz.',
  'Compsopogon coeruleus Balb. ex C.Agardh Mont.',
  'Hippodonta linearis strup Lange-Bertalot Metzeltin  Witkowski',
  'Muelleria gibbula Cleve S.A.Spaulding  E.F.Stoermer 1997',
  'Chamaesiphon amethystinus Rostaf. Lemmerm.',
  'Prasiola fluviatilis Sommerf. Aresch. ex Lagerst.',
  'Neidium iridis Ehrenberg Cleve 1894',
  'Nitzschia soratensis E.A.Morales  M.L.Vis 2007',
  'Caloneis silicula Ehrenberg Cleve 1894',
  'Cymatopleura W.Smith 1851',
  'Palmellopsis gelatinosa Korshikov',
  'Fragilaria austriaca Grunow Lange-Bertalot 2000',
  'Pinnularia isselana K.Krammer 2000',
  'Prasiola Meneghini 1838',
  'Fragilaria ulna var. ulna',
  'Halamphora holsatica Hustedt Levkov 2009',
  'Aneumastus stroesei strup D.G.Mann 1990',
  'Schizothrix heufleri Grunow ex Gomont',
  'Cocconeis placentula var. klinoraphis Geitler 1927',
  'Phormidium irriguum Kutz. ex Gomont Anagn.  Komarek',
  'Surirella minuta Brebisson 1849',
  'Cymbella vulgata Krammer 2002',
  'Pleurosigma W.Smith 1852',
  'Encyonema semilanceolatum Krammer 1997',
  'Karayevia F.E.Round  L.Bukhtiyarova ex F.E.Round 1998',
  'Eolimna utermoehlii Hustedt H.Lange-Bertalot M.Kulikovskiy  A.Witkowski 2010',
  'Stauroneis anceps Ehrenberg 1843',
  'Pinnularia alpina W.Smith 1853',
  'Gomphonema cuneolus Reichardt 1997',
  'Encyonema vulgare var. vulgare',
  'Encyonopsis cesatii Rabenhorst Krammer 1997',
  'Coleochaete irregularis Pringsh.',
  'Monostroma bullosum Roth Thur.',
  'Eunotia fennica Hustedt Lange-Bertalot 2004',
  'Pinnularia neomajor K.Krammer 1992',
  'Cyanophanon mirabile Geitler 1955',
  'Eunotia meisterioides H.Lange-Bertalot 2011',
  'Luticola cohnii Hilse D.G.Mann 1990',
  'Phormidium chlorinum Kutz. ex Gomont Umezaki  Watanabe 1994',
  'Encyonema kuelbsii Lange-Bertalot  Krammer 1997',
  'Frustulia amphipleuroides Grunow A.Cleve 1934',
  'Gomphonema coronatum Ehrenberg 1840',
  'Navicula tripunctata O.F.Muller Bory',
  'Stigonema hormoides Bornet  Flahault',
  'Navicula gottlandica Grunow',
  'Craticula vixnegligenda Lange-Bertalot 1993',
  'Chamaesiphon subglobosus Rostafinski Lemmermann 1910',
  'Nitzschia vixnegligenda H.Lange-Bertalot  G.Hoffmann 2000',
  'Campylodiscus hibernicus Ehrenberg 1845',
  'Adlafia aquaeductae Krasske Gerd Moser Lange-Bertalot  D.Metzeltin 1998',
  'Navicula germainii Wallace',
  'Diploneis puella Schumann Cleve 1894',
  'Eunotia meisteri Hustedt 1930',
  'Vaucheria borealis Hirn',
  'Surirella terricola Lange-Bertalot  E.Alles 1996',
  'Cocconeis placentula var. euglypta Ehrenb. Cleve',
  'Fragilaria construens f. construens',
  'Ulothrix tenerrima Kutz. Kutz.',
  'Navicula scutum Schumann',
  'Adlafia minuscula var. muralis Grunow Lange-Bertalot 1999',
  'Chroococcopsis Geitler 1925',
  'Sellaphora americana Ehrenberg D.G.Mann 1989',
  'Symplocastrum penicillatum Kutz. ex Gomont Anagn.',
  'Cosmarium turpinii Breb. 1856',
  'Navicula dealpina Lange-Bertalot',
  'Eunotia ruzickae Bily  Marvan 1962',
  'Chamaesiphon polymorphus Geitler',
  'Binuclearia Wittrock 1886',
  'Hapalosiphon hibernicus W.West  G.S.West',
  'Gomphonema ventricosum Skabichevskii 1985',
  'Audouinella Bory de Saint-Vincent 1823',
  'Rhopalodia gibberula Ehrenberg Otto Muller 1895',
  'Planothidium joursacense Heribaud-Joseph Lange-Bertalot 1999',
  'Scytonema C.Agardh ex Bornet  Flahault 1886',
  'Nupela tenuicephala Hustedt Lange-Bertalot 1993',
  'Aphanochaete repens A.Braun',
  'Batrachospermum turfosum Bory de Saint-Vincent',
  'Caloneis fontinalis Grunow Cleve-Euler 1932',
  'Phormidiochaete fusca Starmach Komarek',
  'Stauroneis tackei Hustedt Krammer  Lange-Bertalot 2001',
  'Rhoicosphenia abbreviata C.Agardh Lange-Bertalot 1980',
  'Craticula minusculoides Hustedt Lange-Bertalot 2001',
  'Pseudanabaena frigida Fritsch Anagn.',
  'Placoneis hambergii Hustedt K.Bruder 2007',
  'Nitzschia diversa Hustedt 1959',
  'Mayamaea destricta Hustedt Lange-Bertalot 1997',
  'Fragilaria pectinalis Ehrenberg 1838',
  'Naviculadicta obdurata Hohn  Hellermann Lange-Bertalot  Metzeltin 1996',
  'Nitzschia tubicola Grunow 1880',
  'Gomphonema pumilum var. elegans E.Reichardt  Lange-Bert. 1997',
  'Closterium acerosum Schrank Ehrenb. ex Ralfs 1848',
  'Psammothidium kryophilum Petersen E.Reichardt 2004',
  'Gongrosira schmidlei P.G.Richt.',
  'Geissleria similis Krasske Lange-Bertalot  Metzeltin 1996',
  'Oedogonium macrandrium Wittr.',

In [9]:
otl

'Portugal_taxonlist_diatoms_harmonized.tsv'

In [8]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster'

for otl in os.listdir(otl_folder):
    otl_path = os.path.join(otl_folder, otl)

    country_name = otl.split('_')[0]
    output_path = os.path.join(output_folder, country_name + '_ranked_primers.tsv')
    print(" ---------------------")
    print("Processing OTL:", otl)
    mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
    ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)

 ---------------------
Processing OTL: Germany_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Germany_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Germany_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Ireland_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Ireland_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Ireland_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Czech_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Czech_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Czech_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Finland_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Finland_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Finland_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: france_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/france_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/france_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: poland_taxonlitst_diatom_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/poland_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/poland_taxonlitst_diatom_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Austria_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Austria_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Austria_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Sweden_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Sweden_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Sweden_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.
 ---------------------
Processing OTL: Portugal_taxonlist_diatoms_harmonized.tsv
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/amplicon/filtered and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode/multibarcode_input.tsv
mozaiko INFO: MultiBarcodePipeline completed. Output in /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/insert/multibarcode
mozaiko INFO: Primer Ranking results saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Portugal_ranked_primers.tsv.
mozaiko INFO: Intermediate ranks saved to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/diat-barcode-test-cluster/Portugal_taxonlist_diatoms_harmonized_intermediate_ranks.tsv.