In [2]:
import pandas as pd
import numpy as np

In [ ]:
!cut -f 1,8,15,18,21,22,26,67,68,71 /home/camilababo/Documents/DNAquaIMG/BOLD_Public.29-Nov-2024/BOLD_Public.29-Nov-2024.tsv | gzip -c - > bold-selected.tsv.gz

In [3]:
path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/external_scripts/bold-selected.tsv"
bold = pd.read_csv(path, on_bad_lines="skip", sep="\t")

/tmp/ipykernel_20620/1837559620.py:2: DtypeWarning: Columns (1,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  bold = pd.read_csv(path, on_bad_lines="skip", sep="\t")

In [4]:
bold.tail()

,processid,bin_uri,phylum,family,genus,species,identification_method,nuc,nuc_basecount,marker_code
17862992,ZYGMO209-10,BOLD:AAJ5548,Arthropoda,Zygaenidae,Adscita,Adscita obscura,NaN,AACACTTTACTTTATTTTTGGTATTTGATCAGGAATAGTTGGAACA...,658.0,COI-5P
17862993,ZYGMO290-10,BOLD:AAO1273,Arthropoda,Zygaenidae,Rhagades,Rhagades predotae,NaN,----------------------------------------------...,608.0,COI-5P
17862994,ZYGMO294-10,BOLD:AAO0371,Arthropoda,Zygaenidae,Zygaenoprocris,Zygaenoprocris minna,NaN,AACACTTTATTTTATTTTTGGAATTTGATCAGGAATAATTGGTACA...,658.0,COI-5P
17862995,ZYGMO295-10,BOLD:AAN9389,Arthropoda,Zygaenidae,Zygaenoprocris,Zygaenoprocris rjabovi,NaN,AACACTTTATTTTATCTTTGGAATCTGATCAGGAATAATTGGAACA...,658.0,COI-5P
17862996,ZYGMO296-10,BOLD:AAN9389,Arthropoda,Zygaenidae,Zygaenoprocris,Zygaenoprocris rjabovi,NaN,AACACTTTATTTTATCTTTGGAATCTGATCAGGAATAATTGGAACA...,658.0,COI-5P

In [18]:
non_null_id = bold[bold['identification_method'] == '68']
non_null_id

,processid,bin_uri,phylum,family,genus,species,identification_method,nuc,nuc_basecount,marker_code
798703,BCHYM17398-18,BOLD:ADF1766,Arthropoda,Chalcididae,Brachymeria,NaN,68,TATAAGATTTTGATTATTACCTCCTAGGTTATTTATATTAATTTGT...,403.0,COI-5P

In [10]:
bold.shape

(17862997, 10)

In [12]:
count = bold['marker_code'].str.contains('COI-5P', na=False).sum()
int(count)

14790363

In [13]:
unique_idm = bold['identification_method'].unique()

In [ ]:
np.savetxt("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/external_scripts/idm.txt",
           unique_idm, fmt='%s')

In [15]:
unique_mc = bold['marker_code'].unique()

In [ ]:
np.savetxt("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/DNAquaIMG/external_scripts/mc.txt",
           unique_mc, fmt='%s')

In [7]:
average_length = bold['nuc'].astype(str).apply(len).mean()

In [8]:
int(average_length)

610